### ISSUE TITLE
When deleting a study: Services are stopped from the client

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#1008]
When deleting a study from the study browser, a for loop is going through all nodes in the workbench for that study, issuing an API call for every interactive service that must be closed.

This should be done on the server side, once the study is deleted, all its orphan services should be stopped with no client interaction needed.

**Comment by sanderegg** [comment]
this has been fixed in [#1161](https://github.com/ITISFoundation/osparc-simcore/pull/1161)
