### ISSUE TITLE
Jupyter notebook with blackfynn API

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-simcore#1016]
**USER STORY:**

Would it be possible to have a jupyter notebook with blackfynn python api installed, so user can access dataset in a more flexible way and can address more complicate logics in files/data/records retrieval?

Thanks
Max

**Comment by sanderegg** [comment]
@nitrosx 
Definitely possible. I will discuss with @mguidon what it implies.

You can already install the blackfynn python package using
```
!pip install blackfynn
```
Or is there something missing there as well? in which case I can also add this stuff.

**Comment by nitrosx** [comment]
@sanderegg 
I just tried and I get an error that gcc is missing.
I think you guys need to do it, unless I'm allowed to install gcc on the container running in the back.

**Comment by nitrosx** [comment]
Sorry to bug you again, what is the status for this request? If it has been accepted, do you have an ETA?
IF I can have this notebook, I can start to working on a couple of projects and testing oSPARC right away.
Thank you so much

**Comment by sanderegg** [comment]
@nitrosx 
sorry for not answering before, had some other issues to solve in between. I think I should be able to add this this Friday. I'll let you know as soon as this is up.
In the meantime, you could maybe try using the jupyter-scipy version, it might have more things already pre-installed [scipy notebook description](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html) and maybe among other gcc. but anyway I'll update the base notebook.

**Comment by nitrosx** [comment]
@sanderegg 
No worries!!! 
I followed your suggestion and run pip install blackfynn on a scipy notebook and it worked!!! 
Thank you so much

Nevertheless, I think it would be awesome to have just a notebook with blackfynn installed. 
Thank you again

**Comment by sanderegg** [comment]
@nitrosx glad to hear that!
I'll update the base notebook nevertheless, but then maybe lower on the priority list if that is ok for you. I'll schedule that for next week.

**Comment by nitrosx** [comment]
@sanderegg 
No rush at this point. Take your time.
Are you going to prepare a notebook with blackfynn python api installed together with GCC?
Do you think we should have a jupyter notebook where gcc is installed by default, too?

Let me know
Thanks
Max

**Comment by sanderegg** [comment]
@nitrosx 
well I was thinking at least blackfynn. now I don't know about GCC, would that be desirable?
Is it installed on scipy? or maybe it's just that numpy, pandas and so on are pre-installed and it does not need to compile anything...

**Comment by nitrosx** [comment]
@sanderegg 
gcc is installed on scipy notebook. 
When you run pip install, some packages require gcc to be able to install (such as blackfynn).
So, if you need to install a package that requires gcc, having a notebook with the compiler, would be helpful. That said, I'm not sure which are the security implications of it, given that I'm not familiar with the system back end.

Thank you once more

**Comment by sanderegg** [comment]
@nitrosx 
blackfynn is now installed in all the notebooks (version 2.13.0)
