### ISSUE TITLE
Can not halt notebook

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-simcore#1024]
I'm working in a jupyter notebook block.
I cannot halt and close the notebook that I have open.
Can you please check and let me know?

Also, can you run multiple notebooks within the same osparc block?

Thanks

**Comment by sanderegg** [comment]
@nitrosx 
you mean selecting "close and halt" does not work? I can reproduce this.

Workaround for now:
1. Press "Open", and shutdown by selecting the notebook in the list
or
2. Press "close and halt", then the restart button on top brings back to the list

**Comment by nitrosx** [comment]
@sanderegg 
You are correct!!!
I tried your solutions, but I cannot stop notebooks. They keep showing as running in the files tab, but not in the running tab.

Let me know
Thanks

**Comment by sanderegg** [comment]
outdated, stale.
