### ISSUE TITLE
Document CIs workflow

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1032]
- Every developer shall understand all the variants of CI workflows

Please read https://github.com/ITISFoundation/osparc-services/pull/33 and then close

Main doc is in [osparc-services/ops](https://github.com/ITISFoundation/osparc-services/tree/master/ops)

**Comment by sanderegg** [comment]
Documentation for all repositories involved in the process were improved/added.

**Comment by pcrespov** [comment]
OK with me!

**Comment by pcrespov** [comment]
@odeimaiz @mguidon @ignapas please comment
