### ISSUE TITLE
Activity Manager API

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1034]
Requirements from the client side require the following implementations in the backend:
* Display
  * Hardware usage for dynamic and computational services (CPU and Memory)
  * Queue status
* Actions
  * On queues
    * ?
  * On the execution pipeline. Stopping or running one or several individual computational services at once.

For this, one(?) API has to be exposed. An activity API has been created that will serve all the data for the frontend to display. To act on the execution of services and to trigger changes in the queues, more endpoints have to be defined.

AAU I want to see the state of my monitoring queue. This is the server side and shall be connected with the front end.

- check how flower works

Expose some of the celery stuff to user (queues, state in queue).
- Monitoring state of runs in queues. 
- Prepare to expose some queue settings (e.g. priority, etc) 
- Sidecars, lots of them, better slow than unresponsive

**Comment by mguidon** [comment]
- [ ] Define what resources to display
- [ ] Define what actions to allow
- [ ] API spec
- [ ] Implementation

**Comment by ignapas** [comment]
Currently working on getting queueing data from Celery
