### ISSUE TITLE
Define workflows to integrate 3rd party services 

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1037]
- how to submit?
- define workflow for the integration of external services 
   - document different *starting point*, validations, storage, contiguous curations, ... 
- start with opencor user case
- check other services already in use

**Comment by KZzizzle** [comment]
Some Guidelines as a first pass

https://git.speag.com/oSparc/documentation/blob/master/osparc-integration/guidelines.md

**Comment by KZzizzle** [comment]
Mockup of website for entering code for new services:

https://kzzizzle.github.io/inputform/

**Comment by KZzizzle** [comment]
Closing for now until we update the process for submitting new services.
