### ISSUE TITLE
passing files between notebooks

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-simcore#1045]
I have 2 notebooks where I connected the output of the first one to the input of the second.

In the first I have the following code:
```
from simcore_sdk import node_ports
PORTS = node_ports.ports()
output_file.write_text(json.dumps(datavis))
await PORTS.outputs[0].set(output_file)
```
and it runs fine.

in the second I have the following code:
```
from simcore_sdk import node_ports
PORTS = node_ports.ports()
input_file_name = await PORTS.inputs[0].get() 
input_text = input_file_name.read_text()
```
and I get the following error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-4-4b417dba4abb> in <module>
----> 1 input_text = input_file_name.read_text()

AttributeError: 'NoneType' object has no attribute 'read_text'
```

can you please advice and let me know what I'm doing wrong ?
Thanks

**Comment by odeimaiz** [comment]
Hi @nitrosx,

Looks to me like the the connections between nodes was done but ports were missing.

When you are in the second notebook, you need to connect the first output port (index 0) of node1 to the first input port of the node 2:
![image](https://user-images.githubusercontent.com/33152403/64229515-44981f00-ceea-11e9-9749-b50fcdd36a54.png)

Thanks a lot for your efforts
