### ISSUE TITLE
custom registry service

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#1054]
When testing we lack the ability to check workflows that include pipelines because the test runner has no access to a registry. Currently registries are internal and setup by hand.

We wish that:
- registry service shall be part of simcore stack?
- can pull pipeline services from archive registry (e.g. dockerhub) into this registry 
- simcore stack can get pipeline service from one or more registries

**Comment by pcrespov** [comment]
Tip: new stacks developed in ITISFoundation/osparc-ops repository (related to #1047 ) would allow to deploy registry stacks seemlessly

**Comment by pcrespov** [comment]
we have a registry in dev mode now. Obsolete
