### ISSUE TITLE
B3.e: Reference inconsistencies across pages in the sparc Portal

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1057]
Data and paper citation is not consistent across pages (e.g., references for
https://data.sparc.science/sim/#/dataset/8 vs. https://data.sparc.science/sim/#/dataset/4)

From SparcPostal user testing. Team Blue to DRC. Started @ISAN, finalized September 5, 2019 document.

**Comment by ignapas** [comment]
PRed
