### ISSUE TITLE
DRC feedback/issue collection and tracking (Infrastructure) - J-D21

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#1065]
- [x] A DRC-wide issue/feedback/support collection and tracking system is established to collect feature requests and bug reports from users, prioritize their implementation, and provide feedback to the users; 
- [x] it shall be transparent to NIH

**Comment by KZzizzle** [comment]
Some points to address listed by David:
* DRC-wide feedback/issue tracking for SPARC community 
* Team Blue is just one of the products being delivered by the DRC. 
* The goal is to have a single place that makes it easy for users to give feedback: bug reporting, feature requests, general questions. 
* Integrate/link to specific templated feedback forms from the Portal, the documentation, Blackfynn, Discover, and oSPARC. 
* These issues would then be verified/confirmed and passed through to the appropriate development tracker.
 * This will also serve as the single point of reference for the DRC wide coordination of development also for DRC Project Coordinator
 * Once the DRC agrees we can start looking at specific implementation.

**Comment by KZzizzle** [comment]
Requirements for the issue tracker are outlined with the DRC here: 
https://docs.google.com/document/d/1rKU96J9-Y6s_N1M_a7l8eZ4onjI24F-n-j9QyPkaFp4/edit#heading=h.79cbszge23sq

**Comment by KZzizzle** [comment]
Wrike is set up to receive feedback from users external to DRC
Feedback Form:  https://www.wrike.com/form/eyJhY2NvdW50SWQiOjMyMDM1ODgsInRhc2tGb3JtSWQiOjI2NzEzMn0JNDcyNjExODQ3MzYwNAkwNThiMjdhMTdlOTZmODgyZGU3MzQ2MmY4MjA2N2IyZTFhYjRjOGNlZTgzNmUwNDFiM2IzZGYxNDdiZjFlMjZj

Created a slide deck to show Github integration:

https://docs.google.com/presentation/d/1q7CwsZpOhzwqP_CnEeWTP-TfXzDBNgJge8f-McqSHGo/edit?usp=sharing
