### ISSUE TITLE
Portal hard launch

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#1068]
establishing of a document specifying the functionality of the SPARC portal at its hard launch date
hard launch of the SPARC Portal;
this includes communication, and ascertained the necessary stability, testing, and monitoring functionality

**Comment by mguidon** [comment]
Status before Mythos:

- Porting of existing simcore part to the new framework
- Content: Google Drive
- Documentation migration
- Curation: what do we need to do?
- Review all 8 studies and make them great again

**Comment by odeimaiz** [comment]
duplicated #31
