### ISSUE TITLE
OpenCOR / CellML module & PMR S-D2, M2

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#1069]
this tasks serves to make the collection of computational models in the PMR (particularly the ones related to organ control) available to the SPARC community, e.g., for the purpose of virtual studies, and meets the requirements of the MAP-CORE team

- [x] OpenCOR simulation service that accepts CellML models and allows to setup (incl. initial values for parameters, which are only dynamically known) and run OpenCOR simulations
- [x] service module to permit selection and import of CellML models from the PMR (physiome model repository)

**Comment by KZzizzle** [comment]
That was a mistake  - should not have been closed...

**Comment by KZzizzle** [comment]
Computational service created that can take .cellml or .sedml files from the FilePicker service and create a .csv file that can be read and plotted by 2Dplot

![image.png](https://images.zenhubusercontent.com/5d63b175d8bef7000118d535/6472fcf7-0831-4f4f-a615-fd403b3aacce)

![image.png](https://images.zenhubusercontent.com/5d63b175d8bef7000118d535/fc3f7357-f131-41fd-88a4-3fa65cbc3871)

Three parameters are exposed to the user: starting time of the simulation, ending time and the time increment.

![image.png](https://images.zenhubusercontent.com/5d63b175d8bef7000118d535/d2e2c086-347d-4dca-93bb-953a18d5fc5a)
