### ISSUE TITLE
dedicated UI for sim4life

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1078]
UI that is able to consume a smash-like dataset and represent it in r/w mode on a GUI that looks and feels like s4l desktop

- UI replicate simulation tab in front-end
   - all components must be reusable
- backend service with API: 
   - that can navigate the smash file 
   - can r/w to all parts of the smash file

DOD:

- create project with 3d entities in S4L desktop
- osparc study with file-picker and s4l modeler node
- upload smash to study
- open s4l modeler node: renders content of smash file.
- can read/modify properties (visibility, transparency, color)
- can download smash and reopened in S4L desktop

- Optional: can combine remote rendering case

**Comment by odeimaiz** [comment]
deprecated
