### ISSUE TITLE
o2S2PARC for general use, S-D23, Y3M11,5

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#1084]
useo2S2PARC is made fully accessible and usable for the entire SPARC community for general use. o2S2PARC will be made available to anyone in SPARC who wants to use it for hosting their models or analysis tools by Y3M5. 

In general, we will open oSPARC to the SPARC community in a first step and will then gradually open it for general public access during Y3. However, it should be noted that some solvers and services are licensed.

- [x] o2S2PARC is made accessible to SPARC members for general use (M5)
- [ ] o2S2PARC is made accessible to general public (M11)

**Comment by pcrespov** [comment]
duplicated
