### ISSUE TITLE
CI in master broken from commit 3d01935

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1085]
This [commit](https://github.com/ITISFoundation/osparc-simcore/commit/3d01935a530d715aa95197278d5ccbe4fb2ca9eb) breaks CI

See https://travis-ci.org/ITISFoundation/osparc-simcore/builds/590347140?utm_source=github_status&utm_medium=notification

I cannot explain why the CI fails in master and did not fail during PR. Please investigate whether there are some flaws in our CI system. 
Thx

**Comment by ignapas** [comment]
Nothing has been pushed to dockerhub (webserver) in 11 jours. In PRs, it is build on the fly, but for the master build, last image is taken from dockerhub.
