### ISSUE TITLE
Port NeuroS4L simulator and python tooling

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1118]
Sooner or later we gonna need neurons4l running under python3. sim4life needs that as well. 

- Add the neuron-yale python3 kernel on windows #1137
- Adapt the build system to what we did on linux (ccache #1136, ninja #1136, dockerfiles #1138 #1139, makefile)
- Looking into this c to python wrapper library in case we actually still need that #1137

**Comment by colinRawlings** [comment]
- [ ] Merge master into ninja branch, re-run CI for configs
  - [ ] MSVC
  - [ ] MSVC + clcache support
  - [ ] Ninja
  - [ ] Ninja + clcache support
- [ ] Discuss with PC python wrapper library.
  - [ ]
