### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#1119]
Logout does not really logout. I guess cookie is removed client-side but not invalidated server-side.
![not-logout.gif](https://images.zenhubusercontent.com/5caefb2eecad11531cc41380/e9030eb2-13c5-4040-8301-39481f235b53)

**Comment by pcrespov** [comment]
this is normal. every browser keeps the session in separate cookie

**Comment by pcrespov** [comment]
obsolete
