### ISSUE TITLE
Sharing studies with other users

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1121]
1. UI for sharing (a la google docs)
2. clone the study to the other user by creating a link for that user within an e-mail (notification in the frontend)
(3. easily extendable to sharing services)

**Comment by pcrespov** [comment]
Consider re-defining this as an import/export operation as grafana does with the dashboards

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/d55bfaf0-04ec-46a3-bf66-ab9044255f90)

- a full study (document+data) can be exported from the UI. It produces a token that represent the export (i.e. points to the study, has expiration/access rules etc). Token can be imported into another's user session by inserting it in the UI
- a study document (i.e. a project, not data) can be exported as a json from the UI (download json or copy to clipboard)

**Comment by odeimaiz** [comment]
deprecated
