### ISSUE TITLE
Standardize websocket communication

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1124]
- Document sharing (notified about actions from other user)
1. Notify user
2. send modifications of the study

Use-case:
1. Open 2 tabs of a shared study
2. change one 1 tab are notified on the second tab

**Comment by ignapas** [comment]
Start by checking current use of websockets.
* Keep connection open
* Use same connection for progress and logs
* Trigger communication from different parts of the application
