### ISSUE TITLE
docker-compose configs are not supported by auto-deployer

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1127]
the auto-deployer agent does not support docker-compose files that use configs.

To allow for support it should:
- discover the configs in the docker-compose file
- upload the config files to the portainer endpoint

**Comment by pcrespov** [comment]
is this up to date? otherwise please close

**Comment by sanderegg** [comment]
yes it is up to date, but we do not need it as no one uses that for now.
