### ISSUE TITLE
New Issue link in menu opens a broken page

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1148]
- open **safari** browser
- wanna create an issue
![Image Pasted at 2019-10-31 14-35.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/95e0b912-03df-4644-96a3-97deafed04fd)
- broken link?
![Image Pasted at 2019-10-31 14-36.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/ab80646c-83f3-40d9-b3dd-e800a9f81acc)

- the same procedure with chrome seems to work.

If we want to find gaps/bugs between browsers, the first thing it should work fine is the issue creator.
When done, please report to SyR
thx

**Comment by odeimaiz** [comment]
Not sure if it's browser related... might be that the user is not logged in in GitHub

**Comment by ignapas** [comment]
Yes, it looks like that is exactly the problem, the user needs to be previously log in for the link to work. I will fix it by first showing a dialog preventing the user about this.
