### ISSUE TITLE
Landing page does not display version in master deploy

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1173]
Front-end does in master deploy display "undefined" version!

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/c8351575-b778-40dc-980a-b3b69e52ec2a)

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/22dc8a47-dd5c-42fb-82d8-89b8112fba45)

**Comment by pcrespov** [comment]
Bug persists in master deploy ... 
![image](https://user-images.githubusercontent.com/32402063/73773706-ee722500-4782-11ea-8f34-e8fee883ccf6.png)

**Comment by ignapas** [comment]
It is working now I think, can you please check again?
![Screenshot from 2020-02-05 09-46-25.png](https://images.zenhubusercontent.com/5caefb2eecad11531cc41380/926f1896-7769-4f9d-be8e-5c81143286f1)

**Comment by pcrespov** [comment]
Excellent! Yes it works ... I wonder if my browser was using some cache? GREAT! :-)
