### ISSUE TITLE
``/project/{project_id}?run=[true|false]`` is never called in front-end

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1176]
Front-end NEVER calls query ``run`` in ``/project/{project_id}?run=[true|false]`` 
Is this feature really needed?
Review this logic in the backend and add some tests that define rationale

See [Resources.js](https://github.com/ITISFoundation/osparc-simcore/blob/63645a98af86da778a6b4fdd1a684b940285a9e7/services/web/client/source/class/osparc/data/Resources.js#L114) fixem note

**Comment by odeimaiz** [comment]
deprecated
