### ISSUE TITLE
Sidecar logs error to pull sleepers during tests/integration/computation/test_computation

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1187]
Steps to reproduce:

- Run tests/integration/computation/test_computation.py::test_start_pipeline
- When services/web/server/src/simcore_service_webserver/computation_handlers.py::start_pipeline is called, 
the **sidecar** log shows a failure

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/6ee14760-81e8-4b1f-af6a-78541bc6c984)

**I guess the problem is that [unsecured access to the registry is not allowed](https://docs.docker.com/registry/insecure/)? ** Shall we add a certificate during testing? But, why the fixture allows to push/pull a sleeper test image though?? Is it because
The test succeeds because it does not check errors in the logs of sidecar

**Comment by sanderegg** [comment]
this is a known issue and is due to the fact the registry is insecured.

to alleviate this:
- secure the registry, or
- set the registry as allowed insecure registry in the /etc/docker/daemon.json

**Comment by sanderegg** [comment]
shall we close this @pcrespov ?
