### ISSUE TITLE
Hide tokens in preference menu

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1189]
Preferences -> Security

- [ ] Make sure that all sensitive issue is hidden
- [ ] Review that no other data is visible. 

Imagine that you are doing a presentation and everybody is looking and recording your screen. Ask yourself: what data should be hidden??

**Comment by odeimaiz** [comment]
There should be a way for the user to name the given token (similar to what DAT-core when you create tokens)
