### ISSUE TITLE
/me query to db needs to be retried

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#1229]
![image.png](https://images.zenhubusercontent.com/5caef102ecad11531cc412f0/cfa6a2c2-e104-4351-8d2d-2b11522f7034)

**Comment by pcrespov** [comment]
I wonder whether this is the reason why the connection was closed. This is the log of the postgres server
```
2020-01-10 13:06:13.975 UTC [14915] LOG:  could not receive data from client: Connection reset by peer
```

**Comment by pcrespov** [comment]
Shall produce a warning, not an error ...
![image](https://user-images.githubusercontent.com/32402063/72157622-ac8ad480-33b8-11ea-80ca-def284c86989.png)
