### ISSUE TITLE
Bug: "simcore" bucket must exist in S3

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#1230]
A useless "simcore" bucket needs to be present in s3 in order to fetch datasets from "master-simcore" bucket. Otherwise this error happens:
![image.png](https://images.zenhubusercontent.com/5caef102ecad11531cc412f0/01e92145-00d9-4164-a883-866e68cc7eb7)

**Comment by sanderegg** [comment]
obsolete
