### ISSUE TITLE
Tune DB migration

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#1233]
Put Alembic DB migrations to work and make sure they are used consistently.
**TODO**
Run migration each time make up is done, or find a good solution...

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Automatic DB migration when deploying

**Comment by sanderegg** [comment]
added a recipe in Makefile to manually upgrade the DB to latest. see if this is enough for now.
