### ISSUE TITLE
reloading a project also re-retrieve data that is already in the services, and it can be very long!

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1252]
user-case:
1. create a project with file-picker+3d-viewer
2. select a big dataset in the file-picker (e.g. jeduk)
3. link it in the 3d-viewer -> transfer of data (slowish but done)

4. close the project
5. re-open the project -> all the services are restarted and the data is retrieved again... although the data is the same (again very long, and unnecessary)

**Comment by pcrespov** [comment]
Let's follow up on this.

**Comment by sanderegg** [comment]
staled closing
