### ISSUE TITLE
Deleting a project

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1253]
I think that the UX to delete/create a project is not smooth

To delete a project:
- I cannot simply press delete
- Need to move the mouse at least three times and long distances: I have to select a project, go to the delete button, then go to the confirmation window (which btw does not has the focus)

![delete-study.gif](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/c4abaeb1-f8c8-4568-8f01-d031d1f586a0)

One possible way to go is using menus embedded in the project:

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/7f59abb7-6e7b-4f5d-be28-f424752edc91)

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/aca7c31d-4431-4f9b-9902-070d9ce56414)

**Comment by ignapas** [comment]
That wouldn't work for deleting multiple elements at the same time for what you need common action buttons.
![gdrivedelete](https://user-images.githubusercontent.com/4764217/72716366-5bc26b00-3b72-11ea-990a-6177542feb45.gif)
Google drive uses a very similar approach to ours, only that they don't ask for confirmations.
If moving the mouse is too much of a problem, we could render the confirmation dialog closer to the button...

**Comment by ignapas** [comment]
I think this would be a nice solution:
Current actions in the Dashboard are: select studies, open them, save them as templates, edit them and delete them.
* Selection stays the same
* Create a distinguished actions bar that will display the different actions depending on the current selection: open (only one selected), delete (at least one selected), save as template (one user study selected).
* In the detail view, only the edit button will stay.
* Confirmation dialog for deleting a study will be rendered just below the delete button.
Let me know your thoughts @sanderegg @odeimaiz @pcrespov
