### ISSUE TITLE
Some questions about [tests/e2e](tests/e2e)

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1254]
Some questions related the design of [tests/e2e](tests/e2e) system testing

-  What is tests/e2e/.env-devel used for? 
- Why ``ci/travis/system-testing/e2e install`` needs to override package.json and package-lock.json in the root folder? It is inconvenient to run these tests in development machine. 
- can we capture log the backened services upon test failure?
-  is [tests/e2e/.eslintrc.js](tests/e2e/.eslintrc.js) is compatible with [.eslintrc.json](.eslintrc.json) ?

**Comment by sanderegg** [comment]
@pcrespov I think all these points are fixed now.
