### ISSUE TITLE
Initial Python Service (Accepts Script as Input)

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#13]
**User story**

As a **user** i want to have the possibility to use my python scripts as part in the pipeline to do, for example, postprocessing.

**Definition of done**
- [ ] Docker service that accepts a python script as input and runs it as a service on the osparc platform
- [x] Optional: provide a window in which the python script can be edited (guess what that is gonna be)

**Comment by mguidon** [comment]
@esraneufeld Editor? Output?
