### ISSUE TITLE
Improvements on tests/e2e setup

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1367]
After using tests/e2e, I would like to propose some improvements:

## Makefile MUST work locally

``make TARGET`` must work locally, not only for the ``e2e.bash``.  Now, it needs of some config provided in the ``ci/*/system-testing/e2e.bash``. 
A developer shall be able to run tests locally in a similar manner throughout all modules and without any hack. Other services/packages follow the same workflow
```
make devenv
source .venv/bin/activate

cd mymodule
make install-dev # or any flavor or make install
make tests
```

## Tests MUST NOT change host config

When running tests locally, it MUST NOT globaly install anything. This changes the installation of the host computer!
If it cannot be installed locally (e.g. virtualenv, pyenv, node_modules, etc) then try using docker

For instance:
  - ``sudo apt install -y postgresql-client`` in ``e2e.bash`` installs psql client! Can this be done within a docker??
  - ~~``127.0.0.1==registry``: integrate setup_env_insecure_registry.bash in Makefile, otherwise it does NOT work. If this case is unavoidable, make sure to undo the changes after recipe is finished.~~ in PR #1620

## ~~Avoid duplication~~ [PR #1620]

Since we have a script per CI system, i.e.
- ci/github/system-testing/e2e.bash
- ci/travis/system-testing/e2e.bash
try moving relevant/common functionliaty in the local Makefile

**Comment by sanderegg** [comment]
@pcrespov : is this completed now?

**Comment by pcrespov** [comment]
> @pcrespov : is this completed now?

@sanderegg I crossed what it is implemented

**Comment by sanderegg** [comment]
@pcrespov can we close this now? I think what is not crossed is not valid anymore
