### ISSUE TITLE
Unidirectional Pipelining

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#14]
**User story**

As a **developer**, I want to create a pipeline of dependent jobs that are scheduled via a distributed queuing system. Those jobs are computational services and consist of a input descriptor, a link to a docker image with the actual kernel and an output descriptor. Consecutive jobs are assumed to be compatible with each other. To reduce data traffic, parts of the pipeline can run on the same node.

**Definition of Done**
- [x] Define json descriptors for input and output data structures for typical data types (such that they can later on be interpreted for UI elements)
- [x] The queue allows for dependent jobs
- [x] Jobs can be aborted and there is a possibility to access logs and progress
- [x] When a job is done, a notification will be sent to listeners
- [x] Input/Output descriptors are attached to the docker images and can be queried by the frontend later on

**Bonus**
- [x] The computational backend is integrated into the qx/tornado framwork

**Use case**

Generalize the prototype workflow example (function parser + evaluator). The rendering should be a second, dependent job.

**Comment by mguidon** [comment]
- workbench view (Tripetto )
- available services from director together with meta information
- use python/octave interpreter service --> animation

**Comment by drniiken** [comment]
* MaG

* setup of tasks, scheduling, handling from left to right
* would cover all the use cases for the MVP

* full pipeline closed for the first time
* qxd frontend

* visual graph showing tasks and status
* progress

* including services, sidecars, databases, etc.

* workers number can be scaled, increased

* still todo
- frontend has to query meta data
- full GUI is missing

**Comment by pcrespov** [comment]
- [ ] Introduce PostgresQL database
- [ ] API to get description of the pipelines so that we can display the pipeline
- [ ]

**Comment by drniiken** [comment]
* flow of tasks
* dismantled and cleaned
* show a demo on We

**Comment by odeimaiz** [comment]
https://github.com/mguidon/simcore-comp-backend/tree/computational_pipeline
