### ISSUE TITLE
find a good logger that centralizes all logs

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#141]
Evaluate some popular loggers:
- fluentd
- sematext
- graylog
- syslog
- elkstack
and integrate one in the platform

child of #575

**Comment by mguidon** [comment]
https://logz.io/blog/docker-logging/
https://github.com/deviantony/docker-elk

**Comment by sanderegg** [comment]
also got that from some swisscom buddy:
[splunk](https://www.splunk.com/en_us/download/splunk-enterprise.html?utm_campaign=google_emea_tier3_en_search_brand&utm_source=google&utm_medium=paidsearch&utm_content=Splunk_Enterprise_Demo&utm_term=splunk_bk=splunk&_bt=341217592059&_bm=e&_bn=g&_bg=75654873308&_bk=splunk&gclid=CjwKCAjw0N3nBRBvEiwAHMwvNvuDsg43Xc9j1HkbbavZ19Dvaa-wQUF7ey6xKAKmMGphfBtSItKalBoCcdgQAvD_BwE)

**Comment by sanderegg** [comment]
integrate graylog
loki might be worth cause it is simpler
