### ISSUE TITLE
platform stability

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1426]
reduce issues with the platform on master/staging/production. Includes cases referring:
- deploys malfunctions (when something goes wrong in the deployed environs)
- design upgrades of key component aiming greater stability
- monitoring & diagnostics tooling (configuring or implementing tools to detect issues or help investigating them)
- maintenance services: ops services to maintain running framework stable. E.g. cron jobs to clean hosts/databases/storage; auto-restarting unhealthy services;  etc
- testing services/tooling: to ensure stability during development  e.g. new e2e, mock fixtures, ...

**Comment by sanderegg** [comment]
## Update on [Dim Sum](https://github.com/ITISFoundation/osparc-simcore/milestone/22) sprint for [review](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20200406_DimSum.md)


### Current status
- improved logging from oSparc micro-services
- refactored sidecar to use async libraries
- set-up diagnose tool in webserver to detect async exception, slow tasks and better analysis of memory consumption

### Ongoing development
- separate traefik service for reverse-proxy

**Comment by sanderegg** [comment]
## Update on [Zhongzi](https://github.com/ITISFoundation/osparc-simcore/milestone/23)

# Current status
- separated internal reverse proxy from webserver microservice. now a separate instance of traefik is responsible for it.

# Ongoing development
- improve garbage collector: remove anonymous users storage space/database entries
- improve garbage collector: clean up services around when webserver crashes
- fix code coverage metric
- use new monitoring to explore the cause of slowdown (still not fully resolved)
- test webserver scaling
extend python docker-image base to webserver

**Comment by sanderegg** [comment]
## Update on sprint [Chrigel Maurer](https://github.com/ITISFoundation/osparc-issues/milestone/6)

# Current status
- improved garbage collector: #1509 
- zero downtime deployment: #1451 
- active logout removes services after faster timeout: #1527 
- fixes in CC services to improve stability: #1500 
- fixes in storage when Blackfynn is down: #1506 
- director nenew cache in background: #1496 
- libraries upgrade
- synchronisation of all deploys ops service versions (master, staging/production)
- new deployment of staging platform
- new release [v0.0.21](https://github.com/ITISFoundation/osparc-simcore/releases/tag/v0.0.21)
- improvements on grafana monitoring dashboards (hard-disk left + Metrics)

# Ongoing development

# Open points
- new sidecar (for dynamic services, improve platform stability when 3rd party service is bad, security, access rights, simpler integration of services)
- test webserver scaling
- fix code coverage metric (unit testing)
- use new monitoring to explore the cause of slowdown (still not fully resolved)

**Comment by sanderegg** [comment]
## Update on sprint [Huo Guo](https://github.com/ITISFoundation/osparc-issues/milestone/7)

# Current status
- improvements on synchronisation mechanism to deploy 3rd party services to each platform (speed, reliability) [#37](https://github.com/ITISFoundation/dockerfiles/issues/37)
- cookiecutter enhancements (fix some code-generation issues, added docker base images) [#33](https://github.com/ITISFoundation/cookiecutter-osparc-service/pull/33)
- updated osparc-ops repository with latest changes from master deployment [#69](https://github.com/ITISFoundation/osparc-ops/pull/69)
- updated osparc-ops for osparc api new endpoint (now deployed on master) #1474 
- fix code coverage metric generation #1568 

# Ongoing development
- new sidecar (for dynamic services, improve platform stability when 3rd party service is bad, security, access rights, simpler integration of services) #244 


# Open points
- test webserver scaling
- use new monitoring to explore the cause of slowdown (still not fully resolved)
- filter e2e testing from metrics #1561 
- metrics monitoring issue (data size to generate some metrics causes issue) [#1599](https://github.com/ITISFoundation/osparc-simcore/issues/1599)

**Comment by GitHK** [comment]
## Update on sprint [Da Jia](https://github.com/ITISFoundation/osparc-issues/milestone/9)

# Current status
- fixed sidecar async code error handling [1694](https://github.com/ITISFoundation/osparc-simcore/pull/1694)
- fixed sidecar unit test which failed randomly [1694](https://github.com/ITISFoundation/osparc-simcore/pull/1694)
- trapped two previously unhandled errors which caused computational services to be frozen [1692](https://github.com/ITISFoundation/osparc-simcore/pull/1692)
- computational services no longer result frozen when external resources are unavailable [1692](https://github.com/ITISFoundation/osparc-simcore/pull/1692)
- sidecar will report more rich errors in the UI logs for better issue reporting and faster debugging [1690](https://github.com/ITISFoundation/osparc-simcore/pull/1690)
- sidecar retries on pull errors, avoids connectivity issues with the registry [1688](https://github.com/ITISFoundation/osparc-simcore/pull/1688)
- it is now possible to totally delete users by setting their role to GUEST [1683](https://github.com/ITISFoundation/osparc-simcore/pull/1683)
- storage service speed improved by an order of magnitude [1659](https://github.com/ITISFoundation/osparc-simcore/pull/1659)
- director service only lists services from its stack [1538](https://github.com/ITISFoundation/osparc-simcore/pull/1538)


# Ongoing development
- new sidecar (for dynamic services, improve platform stability when 3rd party service is bad, security, access rights, simpler integration of services) #244 


# Open points
- test webserver scaling
- use new monitoring to explore the cause of slowdown (still not fully resolved)
- filter e2e testing from metrics #1561 
- metrics monitoring issue (data size to generate some metrics causes issue) [#1599](https://github.com/ITISFoundation/osparc-simcore/issues/1599)

**Comment by pcrespov** [comment]
## Update on sprint [Nephelai](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20200925_Nephelai.md)
![image](https://user-images.githubusercontent.com/32402063/94554276-25d59a80-025a-11eb-9846-609539b9b014.png)

A snapshot of the stability cases follows:
![image](https://user-images.githubusercontent.com/32402063/94554038-beb7e600-0259-11eb-9bbc-7048fd387acd.png)

The board above is accessible via [zehnhub](https://app.zenhub.com/workspaces/osparc---scrum-wall-5c9260f3d76ef51f6b0fe78d/board?epics=118596920_1426&filterLogic=any&repos=118596920,210862626,135289610) (requires github account)

**Comment by sanderegg** [comment]
## Update on sprint [Wankel](https://github.com/ITISFoundation/osparc-issues/milestone/12)

# Current status
- Fixed redis version in deploys (#1913)
- Added image digests to postgres docker image (#1914)
- Fixing duplicate key error in comp_pipelines table (#1934)
- Added timeout for director/filemanager (#1936)
- Ensure only one DB connection acquisition per request in FastAPI servers (#1966)
- Fix issue closing studies (#1937 + #1972)
- Fix issue GUI not showing correctly output port updates + persistency of outputs ([#312](https://github.com/ITISFoundation/osparc-issues/issues/312) + #1972)
- Fix study will fail after deleting a computation service ([#367](https://github.com/ITISFoundation/osparc-issues/issues/367))

# Ongoing development



# Open points
- long delays fetching s3 data when runs increased #1638 
- test webserver scaling #1522 
- monitoring to explore the cause of slowdown (still not fully resolved)
- filter e2e testing from metrics #1561 
- metrics monitoring issues #1915 #1923 #1599

**Comment by sanderegg** [comment]
## Update on sprint [Alfred Büchi](https://github.com/ITISFoundation/osparc-issues/milestone/13)

# Current status
- Report errors during user cleanup #2013 
- Fixed creating a group breaks a study #2038 
- Improve test of e2e in local development #2056 
- Fixed async call to start pipelines #2043 
- Configured more meaningful timeouts for http clients #1918 
- Fix closing of study (lock issue) #2004 
- Avoid setting null on Filepicker output #2000 

# Ongoing development



# Open points
- long delays fetching s3 data when runs increased #1638 
- test webserver scaling #1522 
- monitoring to explore the cause of slowdown (still not fully resolved)
- filter e2e testing from metrics #1561 
- metrics monitoring issues #1915 #1923 #1599 
- node ports to retry upload/download in case of failure #2035

**Comment by sanderegg** [comment]
## Update on sprint [Chronos](https://github.com/ITISFoundation/osparc-issues/milestone/14)

# Current status
- bugfix: director-v2 is implicitely converting float values to int, preventing kember from running #2081 
- #2090 
- #2088 
- #2096 
- #2097 
- E2E tests: added new tests #2083 
- P2P tests: added kember test #2082 
- bugfix: address issue acquiring MPI lock in sidecar #2093 
- E2E testing: start template instead of service #2100 
- #2087 
- #2105 
- #396
- #2113 
# Ongoing development



# Open points
- long delays fetching s3 data when runs increased #1638 
- test webserver scaling #1522 
- filter e2e testing from metrics #1561 
- metrics monitoring issues #1915 #1923 #1599 
- node ports to retry upload/download in case of failure #2035

**Comment by sanderegg** [comment]
## Update on sprint [The White Rabbit](https://github.com/ITISFoundation/osparc-issues/milestone/15)

# Done
- Fixes on catalog/services section of the web-API #2151 
- e2e: added MPI test #2149 
- fixes awaitables and broad-exceptions in garbage collector #2104 
- Fixes aiopg hanging or raising error #2138 

# Ongoing
- Maintenance tasks: #2148 (ongoing task)
- API-to-end testing #1580 
- update python to 3.8 #1412 
- improve scheduling of computational tasks #2164 

# Open points
- increase postgres clients #2012 
- test service resilience #1039 
- images registry: failures in images at the registry #2020 
- long delays fetching s3 data when runs increased #1638 
- sidecar logs when pulling #1187 
- test webserver scaling #1522 
- filter e2e testing from metrics #1561 
- metrics monitoring issues #1915 #1923 #1599 
- node ports to retry upload/download in case of failure #2035

**Comment by sanderegg** [comment]
## Update on sprint [Red Panda](https://github.com/ITISFoundation/osparc-issues/milestone/16)

# Done

# Ongoing
- [Maintenance tasks](https://github.com/ITISFoundation/osparc-simcore/pulls?q=is%3Apr+is%3Amerged+%22maintenance%3A+%22+label%3At%3Amaintenance)
- API-to-end testing #1580 
- update python to 3.8 #1412 
- improve scheduling of computational tasks #2164 

# Open points
- increase postgres clients #2012 
- test service resilience #1039 
- images registry: failures in images at the registry #2020 
- long delays fetching s3 data when runs increased #1638 
- sidecar logs when pulling #1187 
- test webserver scaling #1522 
- filter e2e testing from metrics #1561 
- metrics monitoring issues #1915 #1923 #1599 
- node ports to retry upload/download in case of failure #2035

**Comment by sanderegg** [comment]
The list of changes for stability/maintenance tasks will be moved to [osparc-issues#428](https://github.com/ITISFoundation/osparc-issues/issues/428)

**Comment by KZzizzle** [comment]
should we close this issue since everything is now under https://github.com/ITISFoundation/osparc-issues/issues/428

**Comment by sanderegg** [comment]
yes
