### ISSUE TITLE
devops: add a cron job that cleans the nodes periodically

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1434]
@sanderegg commented on [Mon Mar 30 2020](https://github.com/ITISFoundation/cookiecutter-osparc-service/issues/17)

run
```docker system prune -a``` on the nodes to prevent accumulation of images that take up all the space

- IF space over a threshold: Remove bottom x% of most used services  images (Check usage stats see ITISFoundation/osparc-issues#166)

**Comment by mrnicegyu11** [comment]
Closed due to move of ticket. Ticket moved to ops-ticket repo (Ticket 177).
