### ISSUE TITLE
Shall disable delete in template projects

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1437]
## Long story short

Shall disable delete in template projects

![image](https://user-images.githubusercontent.com/32402063/78558633-3e1cad80-7813-11ea-96f3-02fa82c50023.png)

Tried to delete this project (see above) but nothing happened ... then I noticed it was a template
I am not sure if the way to solve it is disabling delete action or simply separating more the templates from my own projects

**Comment by odeimaiz** [comment]
This is a bug. Only template owners can delete their own templates.
