### ISSUE TITLE
Symbols not rendering properly in Tissue Properties table

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1439]
Some of the symbols do not render properly. See e.g. units of thermal conductivity in column title below:

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/4fc7cef7-999c-45c8-b7d5-818499079706)

**Comment by sanderegg** [comment]
@odeimaiz is this still something active? or shall we close?

**Comment by odeimaiz** [comment]
Closing....
