### ISSUE TITLE
jupyter  opencor service

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1446]
Use python interface to run opencor engine 

- [x] create kernel and install in docker w/ opencor installation: use opencor own distro for python_client.
   - [x] integrate https://github.com/KZzizzle/opencor_auto
- [x] jupyterlab+opencor in a single docker possible?
- [ ] add examples

**Comment by pcrespov** [comment]
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/9820a2cb-28af-4866-ab5b-768f84e887ed)

**Comment by pcrespov** [comment]
Current version in master fails

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/f2db6a44-9c6b-44ae-bcba-3faaab95c192)

**Comment by pcrespov** [comment]
@KZzizzle ? This is not interesting anymore right? your solution overcomes the benefits of an interactive service ... may I close this?

**Comment by KZzizzle** [comment]
yes close it

**Comment by pcrespov** [comment]
Remove jupyter opencor from master registry and repo and close

**Comment by pcrespov** [comment]
- [ ] service integration code removed from internal repo
- [ ] image removed from master/staging/production
