### ISSUE TITLE
Set public API entrypoints and set traffik to route it to api-gateway service

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1474]
osparc will publish two **independent** entrypoints to access the system: one serves the website and the other offers a public RESTful API.

Configure traffik to publish appropirate entrypoints for each deployed environment. I propose:
 - webserver:  ``osparc.io``, ``staging.osparc.io`` and ``master.osparc.io``
 - public api:    ``api.osparc.io``,  ``staging.api.osparc.io`` and ``master.api.osparc.io`` 

The public api urls shall be routed to the ``api-gateway:8000`` (default port for all fastapi-based services) service.

### local

I guess this shall be configured in the edge traffik service and not the one in the simcore stack. If that is the case, the development setup can expose the webserver as ``localhost:9081`` and the api-gateway is a different port ``localhost:????``.  

Review ports conventions:
 - 9081:8080 
 - ?:8080: aiohttp based services
 - ?:8000: fast-api based services
 - 300X:3000: debugger 
 - ...

**Comment by sanderegg** [comment]
these 2 are now re-directed to osparc.io.
- api.osparc.io
- api.staging.osparc.io

**Comment by pcrespov** [comment]
please close this as soon as you have the entrypoints defined in staging & production
THX

**Comment by sanderegg** [comment]
Ayeaye sir!
