### ISSUE TITLE
CC fails in master: sync outputs issue

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1479]
https://git.speag.com/oSparc/e2e-portal-testing/-/jobs/157076

- setup test with sidecar fixtures
- graylog dashboard

**Comment by pcrespov** [comment]
![Screen Shot 2020-05-04 at 18.12.19.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/5e512626-3fcf-459b-8305-0279e81b9fdb)

**Comment by GitHK** [comment]
#1692 fixed some errors which could cause the same outcome

**Comment by pcrespov** [comment]
obsolete
