### ISSUE TITLE
New User and Project Models (schemas)

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#148]
New schema define:
- Update services APIs to new schema
  - [x] director 
  - [x] webserver
  - [x] sidecar
  - [x] labels ``io.simcore.inputs`` and ``io.simcore.outputs`` in images need to update . In computational services.
- [x] Update packages (mostly ``nodeports``)
- [x] Update front-end (web client)
- [x] shared models among apis (check if openapi supports this)
- [x] fix the cc2d case

child of #184

**Comment by pcrespov** [comment]
New model schemas currently under ``web/client/source/resources/qxapp/*json``

**Comment by sanderegg** [comment]
models are currently under:
```
services/web/client/source/resource/qxapp/node-meta-v0.0.1.json
services/web/client/source/resource/qxapp/project-v0.0.1.json
services/director/src/simcore_service_director/.oas3/v1/schemas
services/director/src/simcore_service_director/.oas3/v1/parameters
```

The director currently holds a copy of node-meta-v0.0.1.json. All the models should be shared among the services and should be moved in a top level directory.
