### ISSUE TITLE
pressing on Export while on the main group shows no reaction

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1486]
![Screenshot from 2020-05-05 15-31-04.png](https://images.zenhubusercontent.com/5c9260c7d76ef51f6b0fe785/2d4f4b1a-cc49-4b5b-89fc-54c58f1c0d4b)

clickin on Export shows no feedback whatsoever.

I would expect either:
1. it works
2. Export is disabled.
3. a message appears.

**Comment by odeimaiz** [comment]
For the moment I would go for the second option
