### ISSUE TITLE
iSeg -> Open Source

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#15]
**USER STORY**

As **external contributor** I would like to get access to iSeg code and add features or fix issues.

**DEFINITION OF DONE**

- [x] Code is cleaned up (using what metric?)
- [x] Carfully check 3rd party dependencies for legal issues w.r.t. to the iseg license (tbd)
- [x] The code is published somewhere
- [x] we assume that Esra is able to check out/compile and run it only being provided with the github repository link

**As outcome from the review:**
- [x] also provide precompiled version of it on github
- [x] still needs some minor cleanup and renaming

**BACKGROUND**

As part of our agreement, iSeg shall be openly available for the public.

**Comment by mguidon** [comment]
iSeg is using the SuperMash licensing model
Expected delivery end of March
create osparc-iseg repository
simple to compile
check licensed features and third party tools in current version

**Comment by odeimaiz** [comment]
Third party libraries currently used by iSeg:
- [Boost](http://www.boost.org/users/license.html): BSD-like
- Flexlm: Proprietary
- [HDF5](https://support.hdfgroup.org/products/licenses.html): BSD
- [ITK](https://itk.org/ITK/project/licenseversion1.html): Apache 2.0 
- [VTK](https://www.vtk.org/licensing/): BSD
- [Qt](https://www1.qt.io/licensing/): GPL and LGPLv3
- [zlib](http://zlib.net/zlib_license.html): BSD-like

**Comment by mguidon** [comment]
0. Check list above for completeness/correctness
1. Remove proprietary stuff
2. Clean up
3. Push to osparc-iseg
4. Automated build procedure for iSeg and 3rd party libs
5. Requirements for build tools

**Comment by drniiken** [comment]
* SA

* via github
* osparc iseg

* license under MIT terms

* see dedicated website, + documentation, readme

* commercial mirror in our gitlab repo

* also provide precompiled version of it on github
* still needs cleanup and renaming

* maybe look at build automation too

* to become popular, it needs to be very easy to compile, use, extend, etc. !

**Comment by sanderegg** [comment]
pre-compiled binaries located in: https://github.com/ITISFoundation/osparc-iseg/releases/tag/opensource-v1.0

**Comment by drniiken** [comment]
* closed completely
* use internally now
* check mac version

* how to market iSeg
* plugin system
* we need to market it, tell the world
* BL+Nik, come up with action items

* icons being updated
