### ISSUE TITLE
use gitops to deploy osparc in a single branch with 2 repositories

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1508]
deployment of multiple platform is difficult to maintain up to date between the branches since we currently create one branch per deployment platform.

moving to a gitops way: https://www.gitops.tech/
maybe using the following package: https://github.com/swarm-pack/swarm-sync
or extending the deployer to be able to cope with multiple stacks

**Comment by mrnicegyu11** [comment]
Moved this ticket to the ops-ticket repo (nr. 178). Closing.
