### ISSUE TITLE
Improve iframe's loading info

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1520]
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/e5d03358-361d-45d2-a968-e928ccae5b9d)

- logo of service loading (if available) instead of osparc's. Otherwise, service name and version (in small)
- different states steps, e.g. pulling image, starting service, etc ... 
- orthography: capitalization, ellipsis, etc

**Comment by odeimaiz** [comment]
deprecated
