### ISSUE TITLE
Webserver scaling

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#1522]
**USER STORY:**

As a developer I would like to support webserver scaling.
To achieve this the following are mandatory:
1. migrate Redis to work with the webserver at scale, [some work has been done here](https://github.com/GitHK/osparc-simcore-forked/tree/webserver-scaling)
1. the garbage collector task needs to only trigger once per service (not once per container)
1. the task which mirrors comp_tasks in project table  also needs to trigger once per service (not once per container)

To address points  **2.** and **3.** the following #1521 must be resolved first.

**Comment by pcrespov** [comment]
duplicate see #2008
