### ISSUE TITLE
filepicker does not auto-expand to the selected file

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1534]
When I upload a file using drag/drop and open the resulting filepicker I expect to see my selected file.

Actual result:
the file is selected but not expanded.

Expected behaviour:
as a user I have no clue where my file is, so it would be very nice if the file path was expanded.

**Comment by odeimaiz** [comment]
Unable to reproduce it. It might be related to the already fixed #1506
