### ISSUE TITLE
Synchronization minio -> filedatabase

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#1559]
Storage does not know when minio deletes/adds/moves files. At the moment, every time file metadata  is required there is a synchronization step from databse to minio. This scales with the number of files and could be the reason why, if a user has a large amount of files, the system becomes slow. (Odei reports more than 10 seconds for a request)

Think about creating a dedicated storage database.

For notifications minio-->postgres

https://blog.minio.io/part-5-5-publish-minio-events-via-postgresql-50f6cc7a7346

**Comment by pcrespov** [comment]
I will start this case by upgrading storage and then will pass to @GitHK
