### ISSUE TITLE
Service submission email has wrong subject

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#1567]
Someone submitted a new service candidate and the mail's subject shows the prefix ``TEST: ``, which should only be used in testing environments.

**Comment by KZzizzle** [comment]
Could I add two feature requests if you are working on the submission form here:

- Email attaches .json file in addition to nicely formatted email (so I can automatically parse)
- Addition of "units" field for each input and output, though the field can be optional (for your input validation)

Let me know if I should create separate issues for these features

**Comment by ignapas** [comment]
> Could I add two feature requests if you are working on the submission form here:
> 
> * Email attaches .json file in addition to nicely formatted email (so I can automatically parse)
> * Addition of "units" field for each input and output, though the field can be optional (for your input validation)
> 
> Let me know if I should create separate issues for these features

noted. I will add this in my next PR... although I remember I already did the json file attachment part... Idk where it ended up
