### ISSUE TITLE
Add username

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1574]
In view of the comments in PR #1572, the design of users-api and the constraints imposed on the database needs a deep review to avoid inconsistencies of dangling projects/groups

- move from email to username as unique identifier of a user (a user can still login with one/multiple emails in the future)
- can be used to reference any user in chats/notes by using `@username` : api to search user

Review as well:
- [x]  see ``_get_user_name`` during registration
- [x] split ``name`` into ``first_name``, ``surname`` and leave the latter for a potential ``username``. Create migration
- [x] functions to format human-readable names/surnames to address users in communications

**Comment by sanderegg** [comment]
@pcrespov still a thing?
