### ISSUE TITLE
Duplicate key value violates unique constraint "comp_pipeline_pkey"

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#1579]
When running the Sleepers template, sometimes fails starting pipeline.

postgres complaining:
https://monitoring.osparc.io/graylog/messages/graylog_1/a9c53390-b517-11ea-8475-0242ac120012

webserver complaining:
https://monitoring.osparc.io/graylog/messages/graylog_1/a9becaf1-b517-11ea-8475-0242ac120012

**Comment by sanderegg** [comment]
deprecated. now director-v2 does it.
