### ISSUE TITLE
PySONIC integration

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1587]
Support to integrate https://c4science.ch/diffusion/4670/repository/master/

@pcrespov checks this issues:

- [x] ``pip install git+https://c4science.ch/diffusion/4670/pysonic.git`` 
   - packages needs data (pulled via  git-lfs) but it is not packaged in the setup.py
- [x]  check dependencies and ensure it works in jupyter-math (basic jupyterlab service we have)

**Comment by KZzizzle** [comment]
Now public on osparc.io (https://git.speag.com/oSparc/sparc-internal/-/tree/master/services/jupyter-pysonic)
