### ISSUE TITLE
Refactoring of storage service

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1588]
After the upgrade of this service, many improvements seem necesary in order to achieve a maintainable service.

Most of the small issues are just marked as ``TODO:`` or ``FIXME:`` directly in the code and the most relevant are:

- install [blackfynn agent](https://developer.blackfynn.io/python/latest/agent.html) and use it in the code. For the moment, this feature is disabled (look for ``us_agent=False`` flag).
- refactor blackfynn wrappers layers ``dsm -> datcore_wrapper -> dat_core``. There is a lot of room for improvement there to make it more maintainable and not so verbose. 
- do not use protected api in blackfynn library e.g. ``bf._api.io.upload`` 
- Prefer ``None`` to ``""`` (empty strings) in returns when something
- add annotations

**Comment by GitHK** [comment]
Both of you should know more about the state of this issue.

**Comment by pcrespov** [comment]
Outdated and replaced by backlog at #2396
