### ISSUE TITLE
Two different clients can edit same study at the same time

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#1596]
When two different users open the same study (I reproduced it by opening the dashboard in two tabs and quickly clicking on the same study in both), the study can be edited by both users without any visible error.

This comes from the PR review https://github.com/ITISFoundation/osparc-simcore/pull/1591#pullrequestreview-441561922

A strategy is needed to avoid that situation, that can lead to inconsistent (and maybe corrupt?) studies.

**Comment by sanderegg** [comment]
@odeimaiz , @ignapas :
yes, this is expected to happen. I still need to find a way to prevent that from happening.
Also the same user can currently open the same study in several tabs which could lead to the same issues (study corruption). For this we should have yet another event to ensure the tabs are updated (i'll open another issue for this).

**Comment by sanderegg** [comment]
Delete of a shared project returns a 500
