### ISSUE TITLE
Default name of service "box" should include a version info

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1606]
If would be very useful to include a reference to the service version in the default name. this way, the user can create a study with multiple versions of the same service (e.g. for testing or legacy limitations)

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/491efcd7-b171-4eb9-b684-0486e896c980)

This could also partially overcome the UX of retrieving service info: one needs several clicks to reach that info which makes the whole UX very cumbersome.

**Comment by pcrespov** [comment]
In single-node studies, it is also more informative while loading

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/be66a116-a69c-4ed4-a003-80cfa47eedf1)

**Comment by odeimaiz** [comment]
We don't want to populate the node with more UI elements.

The service version is shown in the secondary column and also in the dynamic services at the start up loading page.
