### ISSUE TITLE
LDAP auth for osparc

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1611]
single login in front-end
in backend, we check first 3rd party auth and then local

- connect to z43 ldap server to authenticate
- multiple ldap auth endpoints at a time

PROS:
- "bunch auth": any full organization (e.g. z43) can be authorized at once vs user by user
-  auth reusable for other services in the backend e.g. gitlab 

CONS:
- adds complexity

**Comment by GitHK** [comment]
currently not a thing
