### ISSUE TITLE
User displayed text should be generated by the frontend

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#1616]
As a developer I would like to have all the text displayed to the user generated by the frontend.

It might be desirable to because:
- it is easier to search for user facing text
- it would be simpler to add support for multiple languages

**Comment by pcrespov** [comment]
Can you have a look at this? thx

**Comment by odeimaiz** [comment]
Well... this interferes with the concept of "display the errors that come from the backend".

I would say that the rest of texts shown in the frontend are ready for being [translated](http://qooxdoo.org/qxl.apiviewer/latest/#qx.locale.MTranslation).

**Comment by sanderegg** [comment]
obsolete
