### ISSUE TITLE
Send event to the backend when user closes tab

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#1617]
Referencing https://github.com/ITISFoundation/osparc-simcore/pull/1598#issuecomment-655361299

When a user closes the the tab/window it is desirable to inform the backend about this. The event needs to be properly delivered in order to remove the lock when using multiple windows.

[This StackOverflow answer](https://stackoverflow.com/a/52412486/2855718) has an interesting implementation suggestion. I would also use the polyfill.

**Comment by ignapas** [comment]
@sanderegg wasn't this already handled? when the websocket connection closes (the tab is closed) the server should know without the need of a specific event. I believe the event is called ``disconnect`` and it is issued by the socket.io library itself. ut maybe it is different with the python server library

**Comment by sanderegg** [comment]
@ignapas yes this is the case. the disconnect event is handled and currently then implies a 15min timeout before the project is effectively closed by the backend. The only drawback is that the backend cannot differentiate between a user that effectively wants to close a tab or a network failure. maybe this should be rephrased at some point.

**Comment by odeimaiz** [comment]
Done
