### ISSUE TITLE
project locking more efficient

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1618]
currently the aioredlock library is used to lock calls to the redis database such as when a user opens a project the following happens:
- acquire lock (if not project is considered locked)
- find any user using the project (is some other user is found -> project is locked)
- add the project to the user resources

Problems are:
- the lock is kept a while (during finding operations + adding resource to the user)
Solution:
- create a aioredlock using the project uuid directly (this will make finding the lock much faster and will scale much better)
- the lock shall be created when the user X successfully opens the project
- the lock shall be removed when the user X closes the project
- the lock shall be extended using the user X heartbeat
- after some time without extension the lock is removed and the project is again openable by another user
- if user X appears after that time he shall be moved back to the dashboard

**Comment by GitHK** [comment]
> * the lock shall be created when the user X successfully opens the project

I think it would be safer to acquire the lock while the user is trying to open the project. If there is an error during this phase then it gets released.

**Comment by sanderegg** [comment]
not applicable anymore.
