### ISSUE TITLE
refactoring and improvements on e2e testing

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1621]
- [ ] unit-tests to detect early changes in selectors identifiers ``osparc-test-id=``
- [ ] after logout /me is called multiple times 
   ![](http://i.imgur.com/FjkIhxA.png)
- [ ] why package-lock.json changes after ``npm install``?
- [ ] if slowmotion, deactivate tests-step timeout
- [ ] why not using jest to run tutorial?

**Comment by sanderegg** [comment]
obsolete
