### ISSUE TITLE
Maintenance status on Simcore

### ISSUE THREAD

**Issue by Surfict** [ITISFoundation/osparc-simcore#1635]
**USER STORY:**

Having a maintenance mode on Simcore in case of maintenance. It could be set with an ENV variable. When it is activated, there is a message on the login page saying that Osparc is in maintenance and it's not possible to log in anymore. 
This would be used when maintenance is ongoing on Osparc, making sure no one is using the portal in the same time.

**DEFINITION OF DONE:**

- New env variable for maintenance mode
- When set to 1, a message saying "Osparc is in maintenance" is displayed on the login page"
- It is not possible to log in any more as long as the variable is set to 1.

**Comment by pcrespov** [comment]
@odeimaiz I guess the banner resolves this issue, right?

**Comment by odeimaiz** [comment]
> * When set to 1, a message saying "Osparc is in maintenance" is displayed on the login page"

@pcrespov. connecting the maintenance page is still missing

**Comment by pcrespov** [comment]
> @pcrespov. connecting the maintenance page is still missing

@odeimaiz this cannot be part of the simcore stack since the maintenance page is a separate stack that is only accessible from operations. 

@mrnicegyu11 @Surfict I guess you can assign this case to you and take it on from here...

**Comment by Surfict** [comment]
@pcrespov We would need to discuss what we want here. I am not sure that we want this to be automatically deployed/stopped

**Comment by pcrespov** [comment]
> I am not sure that we want this to be automatically deployed/stopped

@Surfict you created the issue. What did you have in mind?
