### ISSUE TITLE
Long delay fetching s3 data when runs are increased

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1638]
- [ ] auto-scale sidecars:  all tutorials x2 ... only CC needs 8 sidecars to run. The rest have to wait. How to manage resource allocation per user? 
- [ ] some projects in db have faulty sharing props. e.g. project non-template shared with everyone appears in "Studies panel" 
    - open via Study copies access rights "shared with all" but if open via discover, it works file. Make sure copying projects using both ways, produces the same access rights for the copies
- [ ] open project with lots of sleepers. Press several times run. server tries to run everything. pipeline in front end stops running and user does not receive any information of what is going on. Could extend activity manager or use that info on top of services 
- [ ] LONG delays retrieving outputs from service (storage + s3) SEE ``https://osparc01.speag.com/v0/storage/locations/0/files/metadata?uuid_filter=254538cf-0bf5-519d-a254-aec4741e8d37`` takes 3.6s for this
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/2844d642-71b5-49e2-a030-65c456f5dea3). It increases when study is run multiple times ...

**Comment by sanderegg** [comment]
obsolete.
storage was refactored, as the comp. backend.
