### ISSUE TITLE
Show services status to user

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#168]
One of the issues we have at the moment is that the client is not aware of what services were started/linked for that particular project or session and what their status is. Would be nice if we could show (maybe for troubleshooting purposes) that information.

For that, the director could ask for a heartbeat to all services that are supposed to be up and running and push the result (traffic light-like, zB) to the client.

In the same line, we could also have a super-debug-verbose mode in the logger where everything outputted by the pieces in our puzzle is displayed.

**Comment by oetiker** [comment]
sounds like a useful addition

**Comment by sanderegg** [comment]
sounds good, and would also be useful for services that take time to start such as the modeler... maybe we could have something like in waffle.io

**Comment by pcrespov** [comment]
feature already released. issue obsolete
