### ISSUE TITLE
Hardcore Modeling Operations

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#17]
**User story**

As a **user** I can model and place an "electrode" onto a ViP model/mesh.

**Definition of done**
- [ ] I can load a ViP model into the 3D framework.
- [ ] I can pan and rotate it smoothly.
- [ ] I can snap onto the surface/mesh of the ViP model.
- [ ] I can draw a spline onto the surface of the ViP model using snapping and drawing points/elements of the spline.
- [ ] In this sense, I can interactively draw a cylinder (= "electrode") normal to the surface of the ViP model at a selected location.
- [ ] Or I can draw the cylinder somewhere else and then use rotation and translation to bring it close to the ViP model surface.

**Comment by KZzizzle** [comment]
Duplicate of #505
