### ISSUE TITLE
unit-testing webserver takes >30minutes

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1710]

**Comment by GitHK** [comment]
I've got some good performance with MongoDB + Redis with "in memory" solutions (Well they actually setup the abs for you on the fly).
These links might help:
- for Postgres https://pypi.org/project/testing.postgresql/ 
- for Redis https://pypi.org/project/redislite/

I think we also need to do something similar with RabbitMQ

**Comment by GitHK** [comment]
Also, this might be considered https://pypi.org/project/pytest-parallel/
