### ISSUE TITLE
computational tasks know where they were scheduled

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#1716]
As a developer I would like to be able to have and environment variable inside my computational task informing me on the type of queue the service was scheduled on.

The `SC_COMP_SERVICES_SCHEDULED_AS` variable will be injected in the container runtime of all computational services; current values:
- `CPU` no special features available on the node
- `GPU` the node has access to a GPU
- `MPI` the node can run MPI tasks

**Comment by GitHK** [comment]
@mguidon here is the issue for the request

**Comment by mguidon** [comment]
Thats excatly what I need. Thanks
