### ISSUE TITLE
catalog shall filter services based on deploy location

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1717]
use-case: 1 registry is used that provides docker containers to several simcore platforms. 

Production shall only show released services in the service catalog.
Staging shall show pre-released services in the service catalog together with released services.

# Solution 1 - Use catalog full privacy
1. when the new service is discovered, the catalog shall set access rights **only** to the owner, no one else can see it
2. it is then the responsability of the owner to share the service or not
Needs: 
- modification of the catalog automatic rights definition for new services (will be done anyway)

# Solution 2 - Add a decorator to the service version (e.g. alpha,beta,rc)
1. if the service contains a decorator, it is filtered out by production simcore at the director level
2. it is then the responsability of the owner to share the service or not (same as above)
Needs: 
- modifications of the node.json schema to cope with decorators to accept image tags with decorators
- modifications of the director to allow for strict versioning (currently filters out anything not following strict rules)
- modifications of the director service starting mechanism (currently does not cope with keys not following the current rules)
- modifications of the osparc-services-cookiecutter versioning system

**Comment by mguidon** [comment]
Solution 1 suffices for production/staging. How about sim4life.io or ti-solutions.io? How do you suggest to filter there?
