### ISSUE TITLE
Garbage collect sidecars shared folder

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#1747]
**USER STORY:**

```input```, ```output``` and ```log``` folders are kept after the sidecar stops a child container. At that point, all relevant data is already pushed to S3/DB. And the ```job_id``` folder can be erased. This can be done by the sidecar himself of a cron job on every computational node.

**Comment by sanderegg** [comment]
agreed proposal:
- mount /etc/host in the sidecar, so the sidecar can log which node it is running on (helps for debugging and might be useful info)
- create the volume on the fly before running the service
- delete the volume after the service finishes to release storage

￼
the logs are anyway uploaded to S3
