### ISSUE TITLE
sidecar shall unzip input files

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1791]
unzip the inputs if the MIME type is not /zip

[isolve_input.h5](https://git.speag.com/oSparc/z43-manual/-/blob/master/docs/Tutorials/isolve_input.h5) is a valid input file for isolve.

Passing the input to isolve using the file picker will work.
Passing the input to isolve as the output of a jupyter service (e.g. jupyter-math) won't work

**Comment by GitHK** [comment]
After a lot digging the culprit is the webserver, which before starting a pipeline it removes all existing `comp_tasks` and replaces them with new ones because *(quote)*: **# prune database from invalid tasks**.
