### ISSUE TITLE
remove usage of pytest-docker

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1805]
this library is not really needed, plus it creates unwanted dependencies to docker-compose

**Comment by pcrespov** [comment]
Actually I think it is needed. I do not find an easier way to replace:
- ``postgres-database``: used to create fixture with postgres service
- ``s3wrapper``: used to create fixture with minio service
- ``servicelib``: creates fixtures with postgres service
- ``simcore-sdk``
- ``api-server``
- ``catalog``
- ``storage``
- ``webserver``
