### ISSUE TITLE
Issues with access rights to storage in shared studies

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1862]
Steps to reproduce:
- Jupyter lab
- Place file in output
- Clicks folder icon in upper-right ("Files") and can see that output was uploaded to s3
- Save and share study with user A
- User A opens study
- can use jupyterlab but when opening upper-right folder icon ("Files"), no outputs are displayed

Another way to see is that in Data section, 
 - tree nodes corresponding to shared studies DO NOT show files
![Screen Shot 2020-10-06 at 18.17.16.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/b610ff6b-5aea-44be-aa37-1ccf6a55fa34)

Possibly there is a bug in the sharing permissions in calls with storage service.

**Comment by sanderegg** [comment]
this was fixed right @pcrespov ?

**Comment by sanderegg** [comment]
@pcrespov we can close this right?

**Comment by sanderegg** [comment]
@pcrespov  feel free to close this one
