### ISSUE TITLE
Delete shared studies should remove "deleter" from the sharing list

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1864]
Currently if I have a study shared with me and I am not the owner, I am not allowed to delete it. This makes sense since you are not the owner. Nonetheless, I might have decided that it is time to remove it from my list and I should be able to do it.

I would suggest that in this case, the user presses delete and the system could warn that this is shared with other users and you will be removed from the user's sharing list. If confirmed, the study will "effectively" be removed from your dashboard panel because you are not a shared user anymore

**Comment by odeimaiz** [comment]
This already works if the study was explicitly shared with you. If you get access to it via an organization, you will still see it.
