### ISSUE TITLE
new director that orchestrates ALL sidecars

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1875]
- [x] create new director service (fastapi based)
- it spawns dynamically sidecars
- move add execution of comp services from webserver here
- ...

--- 

**Note: the below section still WIP**

# Extended specifications for dynamic sidecar

As a developer I'd like the director to:
- start a dynamic service with the new **service-sidecar**
- isolate the spawned dynamic service inside its own network
- associate a reverse proxy to access the dynamic service via pattern like **uuid.services.deployment.address**
- stop the dynamic service
- retrive logs from the dynamic service

**Comment by sanderegg** [comment]
director-v2 added: currently takes care of the computational services and forward all dynamic services call to director-v0

**Comment by pcrespov** [comment]
@GitHK @sanderegg only moving functionality from old to new director + catalog (#1988) would close this case. Let's take it as a maintenance case and implement this together by beginning of next year.

**Comment by sanderegg** [comment]
@pcrespov we can close this case, #1988 already handles what is remaining ok?
