### ISSUE TITLE
Release jupyters to deployed systems

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1883]
After the recent changes to the jupyters you are responsible for 2 out of 3.
For the following services:
- jupiter-ocatave-python-math with current published version 1.4.1 (on dalco) and 1.4.0 in aws staging and production (check this link) 
- jupyter-smash with current published version of 2.2.4 (version is only for dalco) please check here

I would propose a release to the fowling versions an all the target platforms:
- jupiter-ocatave-python-math release version 1.4.3 (available on master for testing)
- jupyter-smash release version 2.2.5 (available on master for testing)

You would need to do the following:
- [x] check that the new services function as expected and especially that their nodeports are working correctly @pcrespov 
- [x] I will step in and sync them to the target release platforms @GitHK 
- [x] you will then give the access rights to all the people who need to use these services on all the platforms @pcrespov 

Hope this was helpful!

Regards,

**Comment by pcrespov** [comment]
This is the test setup with latest version (1.4.3) of jupyter Math

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/0cb563b5-9d2a-4518-8465-06207986c4c7)

1. drop file -> turns into file-picker
2. connect jupyter Math
    - input from file picker found in /input folder ✓
3. drop 1 file in jupyter Math output folder
4. connect Jupyter Math 2
    - input from previous jupyter math (the one added in 3.) is found in /input folder ✓
5. drop 2 more files in jupyter Math output folder
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/18ea6478-a47d-4ffa-883b-a484a38854fb)
6. they do not appear in Jupyter 2!!! ❌
7. Jupyter Math 3 and 4 are connected after but only receive first file
8. check output of Jupyter Math
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/c3c5c2ab-8937-4411-bfc5-f080a8697d8f)
     - it is clear that Jupyter Math does NOT upload all files in its output ❌

**Comment by GitHK** [comment]
@pcrespov could you please tell me on which environment did you test these? Could you also give me access to these so I can see exactly what is happening?

**Comment by pcrespov** [comment]
> @pcrespov could you please tell me on which environment did you test these? Could you also give me access to these (share them with me) so I can see exactly what is happening?

upps sorry I forgot to share them (in master environ). ✅

**Comment by GitHK** [comment]
@pcrespov they work for me. But they have some inconveniences.:
- You must use the retrive button to fetch the outputs after chaining them upstream.
![Screenshot 2020-10-21 at 13 28 50](https://user-images.githubusercontent.com/5694077/96713742-5ca65880-13a1-11eb-9a97-63086338f8a0.png)
- Also you have to exit to go in the previous directory and back again to make files appear in the notebooks

**Comment by pcrespov** [comment]
> @pcrespov they work for me. But they have some inconveniences.:
> 
> * You must use the retrive button to fetch the outputs after chaining them upstream.
>   ![Screenshot 2020-10-21 at 13 28 50](https://user-images.githubusercontent.com/5694077/96713742-5ca65880-13a1-11eb-9a97-63086338f8a0.png)

@GitHK That did not work for me. Check adding files in the output at different times

> * Also you have to exit to go in the previous directory and back again to make files appear in the notebooks
I see.

Nonetheless, notice that I was checking directoy in our output explorer
![](https://camo.githubusercontent.com/5ad727b61d015705bbf1719d8794fd69f028351c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563616566383138656361643131353331636334313336342f63336335633261622d383933372d343431312d626663352d663038306138363937643866)

**Comment by GitHK** [comment]
@pcrespov I've observed the same thing, initially. Then after a bit of time the files were there.

**Comment by pcrespov** [comment]
@GitHK so can you then move them to staging? (see step 2 in description above) and when done, I will then share (step 3). thx

**Comment by GitHK** [comment]
@pcrespov all services have been published to the requested deployments, you may proceed now.

**Comment by pcrespov** [comment]
@GitHK , I see in master many more version of jupyter smash. Do I understand that v2.2.5 (referered above) is THE LAST one that was done "by hand". The other, based on the description, seem to be autogenerated by the CI

**Comment by pcrespov** [comment]
shared jupyter math (1.4.3) with everybody in master, dalco staging+production and aws-staging
shared juipyter smash (2.2.5) and everybody in master, dalco staging+production

Updated also thumbnails (should be automatic soon)
