### ISSUE TITLE
Auto scaling for AWS and dalco stack

### ISSUE THREAD

**Issue by Surfict** [ITISFoundation/osparc-simcore#1889]
**USER STORY:**

A way to propose more compute on-demand has to be implemented. Following these different use-cases : 

- Antonino use-case: A user wants to run a service using external resources. He will create his workflow and then ask it to run. The portal will give an estimation of the cost, and, if the user validates it, launch one or several new instances that will be automatically connected to the swarm. Then, the service will run on the new host(s) and the result communicated to the user. Finally, the new host(s) will be killed after the services concerned finished their tasks.

- Overloaded use-case: The swarm number of hosts will automatically decrease or increase following some metrics (for example, CPU global usage, RAM global usage..)

Problems to solve : 

- What if services take longer than expected and the user wants to stop it while it's running?

**Comment by sanderegg** [comment]
stale and done for AWS
