### ISSUE TITLE
mixing computational and dynamic services not working as expected

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#1898]
Suppose the below situation is defined by a user:

![Screenshot 2020-10-20 at 11 46 21](https://user-images.githubusercontent.com/5694077/96570514-c4d63b00-12ca-11eb-86b2-9c0fbfbc3577.png)

Due to how we are currently creating the execution graph, all dynamic services are removed from the graph before creating the scheduled tasks to run.

That translates to ending up with the following situation when the graph is processed:
![Screenshot 2020-10-20 at 11 45 44](https://user-images.githubusercontent.com/5694077/96570495-bc7e0000-12ca-11eb-95a1-096f09c8438c.png)

Graph structure:
- sleeper [no dependencies]
- sleeper_2 [depends on **sleeper**]
- sleeper_3 [no dependencies]

The **sleeper** and **sleeper_3** are scheduled to run in parallel. After **sleeper** is done, **sleeper_2** is finally executed.

The desired result for the sequential execution of: **sleeper**, **sleeper_2** and **sleeper_3** in the order they are listed.

**Comment by sanderegg** [comment]
obsolete
