### ISSUE TITLE
Multi-User Framework Setup

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#19]
Goal:
To setup a general multi-user web platform framework.

As a user:
- [x] I want to see a form where I can register.
- [x] Typical login, name, pass, etc. setup ... recovery, etc. ... email sent, etc.
- [x] When accessing the platform, i do so by login and i will then only get access to services/data/models for which i have corresponding rights
- [x] Optional (not so urgent): I can define specific user levels/rights.
- [x] Later: relate these accounts to the DAT-CORE accounts

user story:
- as a user i log in, and i can see the studies that i own. in addition, i can access studies from others, provided i have corresponding rights (look at pipeline and results, run pipeline, create a modifiable copy, modify parameters in the original study and run, modify even the study setup). for that purpose, it should be possible to provide other users or user groups with access to one's project at the corresponding level (e.g., by specifying an invitation with rights in the dash board that gets sent by mail to users) i only get access to services for which i have access permission.
- for isan, we only need limited functionality: 1) access a non-login (default user) that can only access predefined studies (Ward, Clancy, Bornstein for now), (tbd: modify parameters and run the studies), and look at results. 2) access with a user login that provides access to own studies and to all services we decide to make available to beta users. see as well #640.

**Comment by mguidon** [comment]
Use this case to setup the full workflow front/backend

**Comment by drniiken** [comment]
4. Multi-User Framework Setup
PC

* showing login interface
* for multiple users
* communicate with websockets
* multiple people can work at the same time
* e.g., in the 3D window
* basic functionality
* everything working in the network
* next sprint -> put it into qxdoo
* putting together different technologies, get things more together

* link to logins of DAT CORE, can be done ?

* we need to define more and more how the GUI shall look like in August
* set expectations for SPARC early enough, too
* mockups
* massage expectations

**Comment by mguidon** [comment]
Think about a use case for concurrent features

**Comment by pcrespov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WAM](https://trello.com/c/VH6nhwBi/130-wam)

**Comment by drniiken** [comment]
* PC

* masu.speag.com
* port 8000

* multi user setup

* start with some basic concepts

* login button
* name, email etc.
* receiving email to confirm
* can modify my credentials, details
* etc.

* maybe transfer to qooxdoo at one point
* also connect to auto auth server (EHZ)

* basics all there and running

* demos could all be put there at one point

**Comment by pcrespov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WAM](https://trello.com/c/VH6nhwBi/130-wam)

**Comment by drniiken** [comment]
* progress made
* PC

* demo

* user login
* pass
* entry page

* continue with different logins
* NIH, etc.

* entering dashboard
* account settings
* tokens to dat core

* themes can be selected and changed
* design and dev can be in parallel, themes

* setting up new project
* 1st screen kind of workbench

* add modeler
* double click
* settings
* workflow centric

* then open simulation, colleen
* connect to model

* it's up to you if that model is injected into this box or multiple ones
* data flows from one box to the next

* every box has different settings

* all own widgets
* we need pipeline definitions !



* SA

* cloud system running in the basement

* portainer.io

* checking machines and services
* how will the instanced be killed ? make concept
* next sprint

* registry
* system where docker services are stored

* versioning
* things can now be updated instantly

* release strategy
* validation QA strategy

**Comment by mguidon** [comment]
Caprica Milestone - dev notes
- [ ] Add password recovery and registration sites
- [ ] Complete and connect the back-end to the front-end
- [ ] Create a simple User Model

**Comment by sanderegg** [comment]
** Gemenon
- [ ] Stand-alone login in qx connecting with web API for authentication. Two entries to represent standard
- [ ] Preferences pannel to store user profile and token
- [ ] MaG creates a postgres database and we create users there
- [ ] Complete and connect the back-end to the front-end
- [ ] Create a simple User Model ( and fake server&data for dev&testing)

**Comment by sanderegg** [comment]
- [ ] model 
  - [ ] tables definition
  - [ ] database migration
- [ ] authentication
- [ ] authorizations

**Comment by drniiken** [comment]
REVIEW

SA

* showing the login window
* any email will log you in
* backend still needs to be wired

* good progress
* merge it to master still
* finish linking

**Comment by drniiken** [comment]
Nik and Esra need to review this and generate a proper user story and bullet points.
Deadline: before the next planning I meeting !
