### ISSUE TITLE
Draft reverse proxy

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#190]
Create a Proxy that can be mounted as a handler on a route. 

NOTES:
- IS has a url:port, that is rendered in a IFrame
- Front-end public_url/service_token 
- Server maps public_url/service_token to service_url:service_port
- Reverse proxy works for web-sockets as well
- Reverse proxy problem: web-server re-routes calls from front-end to interactive services (e.g. notebooks)

Child of #184

**Comment by pcrespov** [comment]
Try reverse-proxying a notebook served by https://mybinder.org/

**Comment by oetiker** [comment]
I implemented reverse proxying for a jupyter notebook running on our docker ... it almost works ... see #207
