### ISSUE TITLE
Metrics for "Total number of anonymous users who are redirected to OSPARC from the SPARC portal" is empty

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1915]
The metrics is based on data from the DB in simcore.

Since the garbage collector appeared this data is now thoroughly cleaned. the side-effect is that the history of logins disappeared as well.

Proposal:
1. create a metrics from the webserver that prometheus can check,
2. or create a special history table with all the logins

**Comment by elisabettai** [comment]
I @sanderegg, I would close this one. For the metric "Total number of anonymous users who are redirected to OSPARC from the SPARC portal" the only thing that needs to be fixes is filtering the p2e, which is underway.

We have #731 with linked the relevant PRs.

**Comment by sanderegg** [comment]
fully agree. it is old.
