### ISSUE TITLE
Code submission form does not send files - error processing data

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-simcore#1942]
When submitting the service submission form with an attachment, we get an error message "a problem occurred while processing your data". This does not happen when there is no file attachment. 

For the webinar on Nov 19th this should be working (which is why I marked high priority) but if it cannot be fixed by then I suggest removing the button to upload and I will instruct to send via email.

![image](https://user-images.githubusercontent.com/28002886/98437887-5e348800-20e6-11eb-8f76-253307c76797.png)

**Comment by ignapas** [comment]
I will check this
