### ISSUE TITLE
Move logger into comp service node-view

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#1950]
**USER STORY:**

![Image Pasted at 2020-11-10 10-37](https://user-images.githubusercontent.com/33161876/98656613-283f1000-2341-11eb-8ffe-ee94b7b5ab15.png)

**Comment by odeimaiz** [comment]
@mguidon Given the new GUI, can we close this?

**Comment by mguidon** [comment]
Totally. Yes.
