### ISSUE TITLE
Give feedback on the status of a study (open, opening, closing, closed)

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1952]
It would also be nice to know what the status of that resource is. In case of a study if it's open or being closed.

_Originally posted by @odeimaiz in https://github.com/ITISFoundation/osparc-simcore/pull/1939#discussion_r520622999_

**Comment by pcrespov** [comment]
User gets no information when the project is locked. This case will inform the user why the project is locked (e.g. is being copy, ...)

**Comment by GitHK** [comment]
I would also take the opportunity to add proper locking to resources at this point in the backend.

**Comment by odeimaiz** [comment]
> I would also take the opportunity to add proper locking to resources at this point in the backend.

Can we do this in two different steps?
