### ISSUE TITLE
setInterval in inactive tabs

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#1955]
## Issue description

Considering that:

1. All major browser implementation of the `windows.setInterval()` API creates a slow down if the current tab is not active.
1. Typical user workflow of the oSPARC platform: a user will launch their computation or work on their study with breaks from focusing the browser window (for various reasons).
1. To detect if a user is still connected the backend relies on "heartbeat" calls from the frontend and expects them at regular intervals.

The `setInterval()` period will increase over time surpassing the threshold where the Garbage Collector kicks in to clean the project data. The project will be considered closed at this time and all resources will be removed. This implies that the dynamic services will be closed. This is what happens in https://github.com/ITISFoundation/osparc-issues/issues/375

## Suggested solution

Using a web worker should do the trick. It should be able to provide a proper **timer** which will generate events at regular intervals, fixing the issue.

## Related issues
closes https://github.com/ITISFoundation/osparc-issues/issues/375

**Comment by sanderegg** [comment]
@GitHK not sure I understand the issue here.
A logged in user has an Alive key with a TTL of 900 seconds. Even if the garbage collector triggers, it should first check that TTL before removing the project. Do you say the heartbeat interval gets beyond 15 minutes?

**Comment by GitHK** [comment]
Yes, that is the case. This happens when your browser window with your tab opened is not currently active, is hidden in the background. All browsers do this. Safari is very aggressive into doing this, but it alo happens on Chrome and Firefox. It is known side effect of `setInterval`
