### ISSUE TITLE
Investigate the use of Airflow or Prefect.io

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1992]

**Comment by sanderegg** [comment]
this is now completed.
Airflow:
++ defines DAGs as python files in an easy way
++ is compatible with a lot of different platforms using Executor objects
++ reuses our Celery infrastructure
-- slow
-- scheduler runs only once every X seconds, running a pipeline is slower
-- every executor needs to have access to the DAG files --> needs a distributed storage
-- no API to access the UI (in general the API is very reduced)

**Comment by pcrespov** [comment]
An overview on [what we have built](https://docs.google.com/presentation/d/1fsqBdeTyeTY-B_ThTQA3AukWAqP7RwCTlPxJUyMlarc/edit?usp=sharing)
A comparison [table](https://docs.google.com/spreadsheets/d/1H0gcKv_LrpKAvx1geOqwOAnSpXkmrRX0AOP4GUR99ns/edit#gid=0) 
[DAR](https://docs.google.com/spreadsheets/d/1hZVnnWbvKKjeLBRskYUphYD9X32hHZ565Yce0U5EZH0/edit#gid=0) on workflow systems
