### ISSUE TITLE
Properties/Settings Input (Window)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#20]
**User Story**

As a **user** I want to be able to select from a list of available services. When selecting one I expect to have access to the specific input parameters for this service and I can edit them.

**Definition of Done**
- [x] A properties window is available
- [x] Following input data types can be edited: floats, integer, strings, files (uploadable)
- [x] User is able to select an input port as setting instead of typing it in

**Use Case**

Start with mockup data but keep MVP in mind (Clancy).

**Comment by drniiken** [comment]
* GUI related
* demo

(see demo part)

**Comment by pcrespov** [comment]
## [Caprica](https://github.com/ITISFoundation/osparc-simcore/milestone/4) Milestone - dev notes
- [ ] AutoForm widget: given model data -> render UI form
- [ ] Prototype in Jupyter 2D plots from data Clancy model. Start simple, then create [widgets](http://jupyter.org/widgets).
