### ISSUE TITLE
Catalog -> Director timeout

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#2003]
Set a reasonable timeout in catalog's communication with the director. Often, when working locally, many requests get cancelled because they reach the defaulted timeout.

**Comment by pcrespov** [comment]
@GitHK Can you please consider this in your PR #1918 ?? Thx.

**Comment by pcrespov** [comment]
director responses are slow which causes the client in the catalog to timeout, creating a chain effect that reaches the front-end.

The httpx client used to communicate with the director API uses [default timeout](https://www.python-httpx.org/advanced/#setting-a-default-timeout-on-a-client) of 5 secs. 

[This call](https://github.com/ITISFoundation/osparc-simcore/blob/master/services/catalog/src/simcore_service_catalog/services/director.py#L110) was timing out. But it might happen to any from from this client as well.

A first trial showed that [disabling the timeout](https://www.python-httpx.org/advanced/#setting-a-default-timeout-on-a-client) (i.e. setting timeout option to None) allowed the calls to succeed
