### ISSUE TITLE
increase postgres clients

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2012]
- increase number of clients in postgres service (see [notes](https://stackoverflow.com/questions/30778015/how-to-increase-the-max-connections-in-postgres) about memory)
- dimension number of client needed in postgres service provided which service. Currently: web-server, director1&2, storage, sidecar, api-server AND dynamic services via simcore-sdk have **connection pools** to the pg database. 
- some services are CRITICAL (e.g. garbage collection) should we have reserved/exclusive connections??
- pgbouncer?: https://dzone.com/articles/postgresql-connection-pooling-with-pgbouncer

@sanderegg, @GitHK  FYI

**Comment by sanderegg** [comment]
increased the number of clients to 413 like in AWS
