### ISSUE TITLE
dragging the workbench when zoomed

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2016]
As a user I would like to have the possibility to drag the workbench by pressing the **center mouse button** (wheel) when the  workbench is zoomed (the bars are showing).

I think this will help a lot with usability.

**Comment by odeimaiz** [comment]
@KZzizzle says:
https://github.com/ITISFoundation/osparc-simcore/pull/2006#issuecomment-737898108
