### ISSUE TITLE
Jupyter displays "Directory not found" menu permanently

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2017]
POssible causes
- Garbage collector stops service?
- User downloads several GB to inputs (S3 timeout?)

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/bai4583fq3ry7bixo1hwmmg9xe) *by `@newton`*._

**Comment by GitHK** [comment]
There is fix for this https://github.com/ITISFoundation/osparc-simcore/pull/1956
Please make sure it is deployed on the environment where it emerged.

**Comment by pcrespov** [comment]
> There is fix for this #1956
> Please make sure it is deployed on the environment where it emerged.

- FIX #1956 is already in production. See [release notes](https://github.com/ITISFoundation/osparc-simcore/releases/tag/v1.4.0)
<img width="825" alt="Screen Shot 2020-12-03 at 11 09 56" src="https://user-images.githubusercontent.com/32402063/100995459-16bfe100-3558-11eb-81d1-c80b04a648d4.png">

**Comment by pcrespov** [comment]
- 2.2.30 is latest release ...

<img width="215" alt="Screen Shot 2020-12-03 at 11 15 46" src="https://user-images.githubusercontent.com/32402063/100996060-e7f63a80-3558-11eb-91aa-7faf49927be7.png">

includes changes by ANE 

<img width="474" alt="Screen Shot 2020-12-03 at 11 15 31" src="https://user-images.githubusercontent.com/32402063/100996024-ddd43c00-3558-11eb-8f0a-ea2d6afc99dc.png">

![image](https://user-images.githubusercontent.com/32402063/100996236-1d028d00-3559-11eb-94ac-cf08e1c50ea6.png)

**Comment by GitHK** [comment]
I can also confirm that the heartbeat is working. As it is being sent every 2 seconds, so all is deployed.

![Screenshot 2020-12-03 at 11 21 16](https://user-images.githubusercontent.com/5694077/100996700-ac0fa500-3559-11eb-8398-6beb931bc154.png)

**Comment by pcrespov** [comment]
log [webserver around 18h yesterday](https://monitoring.osparc.speag.com/graylog/search?q=container_name%3Aproduction%5C-z43%5C-simcore_production_web%2A&rangetype=absolute&from=2020-12-02T16%3A08%3A28.931Z&to=2020-12-02T20%3A04%3A29.501Z) shows problems stopping services because service itself was already closed!?

**Comment by pcrespov** [comment]
Takes 4 mins to download data… it might be that the server un-responsive!?

**Comment by mguidon** [comment]
https://github.com/jupyterlab/jupyterlab/issues/6782

Might be a similar issue since we tend to move files around in the background

**Comment by pcrespov** [comment]
Issue moved to [ITISFoundation/osparc-issues #412](https://github.com/ITISFoundation/osparc-issues/issues/412) via [**ZenHub**](https://www.zenhub.com/)
