### ISSUE TITLE
Check swap on AWS staging

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2028]
*from SAN's comment:*

so we found that on staging AWS:
- storage was trapped in some loop, using CPU > normal (found on grafana dashboards)
- restarted storage did the trick
- fixed the Nodes dashboard in grafana by the way
--> @allexandre I think with the migration to STRIDES, the SWAP in the machines on AWS disappeared. it's back to 0B might be the catch? We had the issue of machines failing during week-ends before you changed it last time...

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/bwge9fxtobdd7boqcfm4gewi1e) *by @sanderegg*._

**Comment by GitHK** [comment]
as discovered with @sanderegg this might have caused issues with storage.

**Comment by Surfict** [comment]
Corrected.
- Added swap in the stacks
- Corrected the ansible scripts
