### ISSUE TITLE
Organizations Menu Navigation is Very Laggy/Buggy

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-simcore#2042]
When I try to create or edit an organization, it is often difficult to get the list of the organization's users. When clicking on an organization name, sometimes nothing loads and sometimes it loads but after multiple clicks/switching organizations and back. Then, trying to switch to a different organization will often take a long time or will not work.  See gif below:

![organization_bug](https://user-images.githubusercontent.com/28002886/101769979-13909c00-3ae8-11eb-8bbf-6dd191065a45.gif)
![image](https://user-images.githubusercontent.com/28002886/101769985-155a5f80-3ae8-11eb-88ba-1496fb0b6bc2.png)

**Comment by odeimaiz** [comment]
Workaround: click on the empty spaces of the organization card
