### ISSUE TITLE
GUI: arrow does not follow the mouse

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#2068]
- use osparc in a non-maximized window (not sure if that is the problem?)
- create a link from a service node

--> observe the arrow is shown about one node to the left of the mouse.

![arrow_issue.gif](https://images.zenhubusercontent.com/5c9260c7d76ef51f6b0fe785/e8cea52a-ab91-4ec2-8fd8-c9a20ee3cbe7)

**Comment by odeimaiz** [comment]
@sanderegg can we close this one?

**Comment by sanderegg** [comment]
not seen in ages. seems fixed.
