### ISSUE TITLE
Review global exceptions catch within coroutines

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2084]
As can be seen in this [commit], catching ``Exception`` have the risk of suppressing ``CancellationError`` and a code like

```python
# setup
background_task = asyncio.create_task(background_fun)
...
# tear-down
background_task.cancel()
await background_task # <----
```
have the risk of waiting forever.

- Search for broad except in repo, i.e. ``except Exception`` and analyze whether it is
- Review exception handling techniques in asyncio (shield, exception_handler, etc)
- A solution, in case we do not know the exceptions, it to avoid ``CancellationError`` but catch-and-reraise ... but not very elegant. Prefers to catch the right exceptions

[commit]:https://github.com/ITISFoundation/osparc-simcore/pull/2079/commits/757ecbcc07b2a3659a6134101a5404b0907b6013

**Comment by sanderegg** [comment]
CancellationError is a BaseException, so it would not be catched. we can close right @pcrespov ?

**Comment by pcrespov** [comment]
> CancellationError is a BaseException, so it would not be catched. we can close right @pcrespov ?

@sanderegg I guess so. This is from the times when CancellationError was still a subclass of Exception and not BaseException :-)
