### ISSUE TITLE
zipping/unzipping takes a looong time

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#2124]
in the dynamic services that save their state (such as jupyter-lab), the state is saved following this process:
- zipping work folder
- uploading zip file to S3
- some files in the outputs are missing after unzip

And the same in reverse when re-starting the service.

The zipping process is *hyper* slow and the upload/download much faster.

It would be nice to have some acceleration. is the zip in the jupyter compressing?? is there a faster mechanism??

**Comment by GitHK** [comment]
addressed by https://github.com/ITISFoundation/osparc-simcore/pull/2192 where compression was disabled
