### ISSUE TITLE
Front-end notifies of a new version available

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2128]
**USER STORY:**

A new version of the platform/UI is deployed but the user does not get any notification so e.g. it has an old UI

**DEFINITION OF DONE:**

- User has version 1
- Platform deploys a new version ( version 2)
- Front-end gets notified (or can check the version polled in health-check which incorporates real version of the service)
- Front-end shows a message to the user notifying it about the update
- Ask to update the browser
- (BONUS) 
    - the notification includes a link to [the specific release notes](https://github.com/ITISFoundation/osparc-simcore/releases) and are also added somewhere in the preferences
    - the footer includes the version (not only the git SHA) and a link to release notes

**EXAMPLE:**

Behaviour is similar to mattermost notifications or

**Comment by odeimaiz** [comment]
connected to https://github.com/ITISFoundation/osparc-simcore/issues/1828

**Comment by odeimaiz** [comment]
Done
