### ISSUE TITLE
Share studies via link

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#2136]
I want to share studies via link.

I give access to a user on a study making him/her owner/collaborator/viewer, but I also want to get a link to send it.
![image](https://user-images.githubusercontent.com/33152403/106909288-6e1d3180-6700-11eb-9dc7-80dcb6bbfffb.png)

**Comment by pcrespov** [comment]
Issue moved to [ITISFoundation/osparc-issues #408](https://github.com/ITISFoundation/osparc-issues/issues/408) via [**ZenHub**](https://www.zenhub.com/)
