### ISSUE TITLE
Duplicate should use the mechanism of the templates instead of exporting/importing

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#2152]
Current duplication of projects in the backend works as:
- export the project to duplicate in the webserver service in /tmp
- re-import that project

This is ok for small project size but for bigger one is going to be:
- an issue maybe with storage availability in the webserver
- unnecessary creation of data that could be very big depending on the projects

For duplication I think the best way is to go through the same path as when a project is created from a template. but doing it from a standard project instead. Most of the mechanisms should already be available.
Pros are:
1. directly duplicates the data in the DB, S3 without first downloading and uploading
Some things that might need to be taken in account are:
1. duplication of the nodes runHash in case of nodes that ran already successfully must be handled (like for the current importer)
1. handling of the files eTag (might actually also be a problem with duplication from template)

Possible improvements
- maybe think of copy on modification instead of copying everything

**Comment by pcrespov** [comment]
I fully agree. All operations involving copying studies should follow similar path, i.e. 
- project document duplicated in database: currently, responsibility of **projects module app**, which will evolve into a separate service at some point ....
- study data duplicated  in s3 : delegated to **storage** (referred in point 1)

both operations can be coordinated by the projects module app but SHALL NOT be executed by the webserver.

**Comment by pcrespov** [comment]
@GitHK please comment on this

**Comment by mguidon** [comment]
This sounds very reasonable. I concur with @sanderegg suggestion.

**Comment by pcrespov** [comment]
consider to implement ITISFoundation/osparc-issues#560

**Comment by pcrespov** [comment]
Will resolve bug #558

**Comment by sanderegg** [comment]
this is now implemented.
