### ISSUE TITLE
Show LOCAL tag upon in UI when deployed locally

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2182]
When the simcore stack is deployed locally, I would like to see the correct mode in the label instead of ``MASTER``

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/0e291c6e-902c-4a96-899e-486f17088515)

Suggestions:  ``LOCAL:PROD`` and  ``LOCAL:DEV``
This info can be provided in the statics from the backend if necessary since the server knows this via environmetn variables ``SC_BOOT_MODE`` or ``SC_BUILD_TARGET``

![Screen Shot 2021-03-02 at 13.12.37.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/565ab288-72e9-4042-a1ca-750c47bbf3e1)

**Comment by odeimaiz** [comment]
For displaying such a tag, the frontend uses the ```stackName``` variable provided in the ```statics``` resource.
Unfortunately, both local and master deployments provide the same ```master-simcore```. Therefore, the frontend can't distinguish them.

**Comment by pcrespov** [comment]
New release tags are sufficient
