### ISSUE TITLE
More version info on welcome page

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2183]
As a user, I would like to know exactly what is the version deployed without having to login

Following #2182, I would like to have more information about the version in the welcome page

- link to git repo at the exact commit (already in place)
- name of the environment (e.g. ``production``/``staging``/``master``/``local:dev``/``local:prod``). Almost in place
- if production or staging, then include the tag name (i.e. = the release name) and a link to the release notes/changelog. eg. [f80fe6a](https://github.com/ITISFoundation/osparc-simcore/tree/staging_TheWhiteRabbit1) (staging - [TheWhiteRabbit1](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_TheWhiteRabbit1))

One possibility would be to be including all that in the footer:
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/55e75497-63cd-4880-b1b2-b6f0b4d5a047)

PS: we could add more info in the statics served from the backend

**Comment by odeimaiz** [comment]
related to https://github.com/ITISFoundation/osparc-simcore/issues/2183

**Comment by pcrespov** [comment]
> related to #2183

@odeimaiz i think you misspelled the issue number :-D

**Comment by sanderegg** [comment]
this is available
