### ISSUE TITLE
Examine Web/Online 3D Solid Modeling Packages

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#22]
Goal:
In order to facilitate the assessment of web/online modeling capabilities, it would be great to examine existing state of the art solutions. This is about the question of how close we can push the user experience of an online modeling/simulation solution to the desktop experience, e.g., similar to the one in S4L - with respect to 3D solid modeling in combination and handling of heavy models, e.g., a ViP model.

This shall encompass:

- [x] have a look at www.onshape.com
- [x] look for alternative packages, check what is industry standard, etc.
- [x] generate a login, dig into it, check the loading and handling of heavy models and meshes, snapping, drawing capabilities, etc.
- [x] check what 3D modeling libraries/packages are used within these solutions ... what import export formats do they support, etc. ... licensing/ open source restrictions for these libraries, etc.
- [x] examine the user experience when doing modeling operations on heavy models/meshes ... latency, delays, slow down, etc.
- [x] is the user experience similar to a desktop solution ?

**Comment by mguidon** [comment]
1. check vtk
2. check open source tools (MaG provides link)

**Comment by drniiken** [comment]
2. Online Modeling Tools
SA

* see slides
* OnShape, most professional one for modeling
* comparison of capabilities
* three.js for rendering
* paraviewweb.js
* I/O of CAD -> on shape most advanced one
* modeling, >1m -> getting slow, crashing
* doing things mostly in the browser, locally
* plugin systems are popular for tools
* large meshes, problem !?

**Comment by sanderegg** [comment]
Review of 3D modeling applications:
[SprintReviewMeeting Issue 22 - Modeling state of the art.pptx](https://github.com/ITISFoundation/osparc-simcore/files/1766301/SprintReviewMeeting.Issue.22.-.Modeling.state.of.the.art.pptx)
