### ISSUE TITLE
Change how service have dependencies

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#222]
The modeler service is made of 2 separate docker container: one running as a linux container that provides the frontend and one running as a windows container that provides computations with the xrpcworker.

The frontend container depends on the backend container to run. The dependency is currently defined by their location in the registry.

Change this to a docker label where the key:version to the dependency is defined.

**Comment by odeimaiz** [comment]
@sanderegg With the changes we made in the modeler/webserver, can we close this one?
