### ISSUE TITLE
User with full access to study renders as "viewer"

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2272]
User from a group with read/write/delete access to a study appears as "viewer" in osparc.io

See study "concore.py cvx text" shared with two users and a group. Three of them have full access. 

<img width="469" alt="Screen Shot 2021-04-14 at 09 52 38" src="https://user-images.githubusercontent.com/32402063/114674105-2b329800-9d07-11eb-859b-11920cdcb0bd.png">

**Comment by odeimaiz** [comment]
Correct, this happens when a study is shared with an organization but not with that specific user.
