### ISSUE TITLE
Enforce codestyle in ci on all projects

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2277]
same as above. it would be nice to have everywhere? not possible to set that in the base makefile?

_Originally posted by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/2271#discussion_r613077697_

**Comment by pcrespov** [comment]
``codestyle`` makefile recipe was discontinued and split into
- make codeformat
- make pyupgrade
- make mypy

SEE https://github.com/ITISFoundation/osparc-simcore/blob/master/scripts/common.Makefile#L112-L135
