### ISSUE TITLE
sync python package version in requirements

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#234]
Goals of this case:
- Guarantee maximum compatibility among all requirements in simcore projects
- Guaranteed compatibility with python distributions >=3.6
- Define a workflow to define requirements. E.g. author can leave version open and at a given point, some tool freezes the version to provide guarantees described above (see tools described in comments).

### Update libraries
-  ~packages/director-sdk~ won't do. it is auto-generated
- [x] packages/s3wrapper
- [x] packages/service-library
- [x] packages/simcore-sdk
- [ ] Shortcuts for CI, dev and prod: ``pip install -r mylib/requirements/[ci|dev|prod].txt`` 
- [ ] update ops/travis with ``ci shortcuts``

### Update services
- [x] services/webserver
- [x] services/sidecar
- [x] services/storage
- [ ] services/director

**Comment by mguidon** [comment]
simcore-service-sidecar 0.0.1 has requirement docker==3.3.0, but you'll have docker 3.5.0 which is incompatible.
simcore-service-director 0.1.0 has requirement requests==2.19.1, but you'll have requests 2.19.0 which is incompatible.

**Comment by pcrespov** [comment]
- Start to have incompatibilities with later versions of python. e.g. pica has issues with python3.7. Should we activate cox to test compatibility >=3.6?

**Comment by pcrespov** [comment]
References:
- [mozilla-approach](https://blog.mozilla.org/webdev/2013/01/11/switching-to-pip-for-python-deployments)
