### ISSUE TITLE
Redis database persistence

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#2364]
currently the redis database is wiped out if restarted.

**Comment by sanderegg** [comment]
@mrnicegyu11 , @Surfict we should look into how to persist the redis database between restarts.
when the table is wiped out, then anyone can open a project that someone else already has opened.

**Comment by mrnicegyu11** [comment]
Possibly https://github.com/p/redis-dump-load running when doing `make up` or `make down`

**Comment by sanderegg** [comment]
@mrnicegyu11 this has been implemented right? can we close this?

**Comment by mrnicegyu11** [comment]
Yes this has been implemented. Before closing it maybe restart redis on master and check it works as expected, I am not sure if this was ever really assessed. Thanks @sanderegg

**Comment by sanderegg** [comment]
tested today. working as expected. after restart all keys are still around.
