### ISSUE TITLE
qx-py-s4l boilerplate

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#24]
- [x] Hello world button in qooxdoo
- [x] Python based Web server serving qooxdoo HelloWorld website
- [x] Web socket connecting Server and Client
- [x] Connection between Server and S4L
- [x] Everything is in containers
- [x] Use this as an example to create a protocol for creating an automated landing page for the review

**Comment by odeimaiz** [comment]
- [ ] Hello world button in qooxdoo
- [ ] Python based Web server serving qooxdoo HelloWorld website
- [ ] Web socket connecting Server and Client
- [ ] Connection between Server and S4L

**Comment by pcrespov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [boilerplate qx-tornado-S4LaaS](https://trello.com/c/ObWgHs6H/101-boilerplate-qx-tornado-s4laas)

**Comment by pcrespov** [comment]
https://github.com/pcrespov/oSPARC_Test/tree/master/templates/boilerplate
