### ISSUE TITLE
Comply to dockerhub open-source policies

### ISSUE THREAD

**Issue by Surfict** [ITISFoundation/osparc-simcore#2425]
In the process of being considered as an open-source project by docker-hub, in order to be able to not have to pay for our amount of pull, we need to satisfy the following requirements ;

- [ ] Become a Docker public reference for press releases, blogs, webinars, etc
- [ ] Create joint blogs, webinars and other marketing content
- [ ] Create explicit links to their Docker Hub repos, with no ‘wrapping’ or hiding sources of their images
- [ ] Include information about Docker on the website and in documentation

I believe that only the last one (having information about docker on the website) would need some work.

**Comment by odeimaiz** [comment]
[ ] Add powered by Docker everywhere @KZzizzle

**Comment by Surfict** [comment]
Ask more details for " Create joint blogs, webinars and other marketing content"
