### ISSUE TITLE
Public API job logs

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2451]
Currently there is no way for the user to have access to the logs fo the solver started via the API.

It would be helpful to have a rest endpoint on the job which returns the last x amount of lines from the service while it is still running. 

As a user I do not expect to have any logs if the service is not running.

**Comment by pcrespov** [comment]
@sanderegg could you please give me some tips on how to achieve this case with the new computational services design? It would be extremely handy to have it in place so users do not need to rely on support to get the API logs:  I am sure @newton1985 will benefit a lot from that :-)

**Comment by newton1985** [comment]
Yes @pcrespov and @sanderegg it would be really useful! :)

**Comment by pcrespov** [comment]
Implemented in ITISFoundation/osparc-issues#687
