### ISSUE TITLE
Clicking on share link of a TEMPLATE study results in ghost study

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-simcore#2560]
**USER STORY:**

For templates, you are allowed to manage share options and also obtain a share link to that template. When that link is used, it generates a "ghost" study with services that don't start. In addition, logging out of the account and logging back in makes this "ghost study" disappear see animation below

Expected behavior would be:
* clicking a template share link would create that study (if you have access rights to the template)
* If the user does not have access to study, error message about not having access to the template
* Study created is like any other created from a template with working services and persistence through logging in/logout
Alternatively:
Disable share link for templates for time being until someone asks for this feature 

![ghost](https://user-images.githubusercontent.com/28002886/135235496-378b5bbd-b554-4301-abb2-a5461fcf052f.gif)

**Comment by odeimaiz** [comment]
@pcrespov I'm not sure that the backend is creating an instance of the template.... I have the feeling it tries to open it as it was a normal study and it fails.

**Comment by KZzizzle** [comment]
> The share link section was disabled for templates. Thanks @KZzizzle!

🤗
