### ISSUE TITLE
Multi-select and move nodes is a bit buggy

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-simcore#2610]
**USER STORY:**

The multi-select and move feature for nodes in the workbench seems to work only sporadically. I tried to figure out a reproducible pattern, but couldn't see one. Sometimes if I hold ctrl + click on multiple studies, it "catches", and sometimes not. 

Also, it would be _really_ awesome if, like on a mac/pc, you could click and hold to create a rectangle that multiselects everything inside of it :). 

**DEFINITION OF DONE:**

Done = multi-select works every time via ctrl + click
Awesome = multis-select works every time via drawing a rectangle

**EXAMPLE:**

Any file/screenshot/photomontage/video/website is provided for a better understanding of the request

**Comment by odeimaiz** [comment]
Implemented in https://github.com/ITISFoundation/osparc-simcore/pull/2724
