### ISSUE TITLE
nodeports fails to handle upload error and leave invalid files in s3

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2614]
sometimes export tools of h5/sab files do not produce the files in one go but by parts. If the export is done directly in the output folder, there is a chance that nodeports does an incomplete upload. In adddition, this upload raises an error because the headers have a different size as the real content ... 

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>IncompleteBody</Code>
<Message>You did not provide the number of bytes specified by the Content-Length HTTP header.</Message>
<Key>e8f92b5c-d635-11e9-aa0f-02420aff0024/8bd2ee66-352d-4592-bd58-5183626472f1/Trajectories.sab</Key>
<BucketName>production-simcore</BucketName>
<Resource>/production-simcore/e8f92b5c-d635-11e9-aa0f-02420aff0024/8bd2ee66-352d-4592-bd58-5183626472f1/Trajectories.sab</Resource>
<RequestId>16B27476AD014030</RequestId>
<HostId>9672ab65-fc12-4747-9f71-bef35d84f214</HostId>
</Error>
```

``nodeports`` must handle these errors and do some cleanup work e.g. remove partially uploaded files in s3  when upload operation raises an error

**Comment by sanderegg** [comment]
since the refactoring of storage this should be better handled. there might still be some corner cases though.
Generally speaking:
- a failed upload, will be eventually reverted to its last version if possible. if there is no such thing then it will be deleted
- storage always lazily checks if data is available

**Comment by GitHK** [comment]
this has not appears recently closing
