### ISSUE TITLE
Nodeports does not find downloaded file

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2635]
So one of Esra's issues is the following. Projectid=111590 NodeID=bf4bba11-e207-489a-92f3-995d6f8661d4
It seems that it downloads a file which is not present on the disk. See below screenshot and [logs.txt](https://github.com/ITISFoundation/osparc-simcore/files/7513613/_jupyter-smash_bf4bba11-e207-489a-92f3-995d6f8661d4.1.ywnjbf8fvsfknkqmpwm9ij43w_logs.txt).

![Screenshot 2021-11-10 at 10 33 50](https://user-images.githubusercontent.com/5694077/141136460-6cb2dc00-1a2a-45ae-b165-0d3967cf7830.png)

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/eubu1nwqntbnirwhko5xe6um4o) *by @GitHK*._

**Comment by pcrespov** [comment]
@GitHK Is this resolved with the new dysidecar ? Please close if so or keep it as a reference to account for it in the dy-sidecar

**Comment by GitHK** [comment]
No idea how to reproduce this one. Will keep it here, if does not show again in the future will end up closing it.

**Comment by GitHK** [comment]
closing, no more reports of this
