### ISSUE TITLE
running a computational service systematically fails on second run 

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2651]
## Long story short

Running a computational service twice results in three requests to the backend because the second always fails with a 422

## Expected behaviour
I would expect a single ``POST *:start`` request per run-hit

## Actual behaviour

on second run, the front-end always retry because it consistently fails with 422 (in all environments) and 
```json
{"data": null, "error": {"errors": ["Project (uuid) has no computational services, or contains cycles"]}}
```

## Steps to reproduce

open dev pannel. 
open a study. 
add a sleeper and hit run.  -> produces first POST
When fininished, hit run again -> produces a POST that fails and a second retry that will go thru

![image](https://user-images.githubusercontent.com/32402063/142476190-e6df87d6-d5a6-4638-9375-f2b4a8499dc8.png)

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "349c2dc",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/349c2dc/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "349c2dc",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/349c2dc/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 718
    }
  }
]
```

**Comment by odeimaiz** [comment]
This is intended, the first error response is there for letting the user know that the pipeline was already executed, so the frontend  will pop up dialog asking if it has to be re-run.

**Comment by odeimaiz** [comment]
@pcrespov shall we close it?

**Comment by pcrespov** [comment]
> This is intended, the first error response is there for letting the user know that the pipeline was already executed, so the frontend will pop up dialog asking if it has to be re-run.

ok, i understand that you want to respond saying that the ``start`` request cannot be processed because it already run.
Then  https://httpstatuses.com/422 because "was unable to process the contained instructions."
