### ISSUE TITLE
isolve-mpi fails on dalco-staging

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2671]
## what fails:

   - [ ] [isolve-gpu]
   - [x] [isolve-mpi]
   - [ ] [jupyters]
   - [ ] [mattward]
   - [ ] [sim4life]
   - [ ] [sleepers]

## where
   - [ ] e2e-master
   - [x] e2e-dalco-staging
   - [ ] e2e-dalco-production
   - [ ] e2e-aws-staging
   - [ ] e2e-aws-production

## how 

- Seems to be a problem related with the directorv2 as it handles logs 
- Workaround: Fixed by restarting director-v2, portainer. 

[isolve-gpu]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/isolve-gpu.js
[isolve-mpi]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/isolve-mpi.js
[jupyters]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/jupyters.js
[mattward]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/mattward.js
[sim4life]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/sim4life.js
[sleepers]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/sleepers.js

**Comment by pcrespov** [comment]
Maybe the issue is the test itself?
![09-23-37_isolve-mpi_toDashboard_before.jpg](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/fd56364f-be38-4cda-b454-15a72ef55f8a)

**Comment by sanderegg** [comment]
this was fixed.
