### ISSUE TITLE
parallel w/ jupyters does not always pass

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2672]
## what fails:
  - [ ] [isolve-gpu]
  - [ ] [isolve-mpi]
  - [ ] [jupyters]
  - [ ] [mattward]
  - [ ] [sim4life]
  - [ ] [sleepers]
  - [x] [parallel_w_jupyters]

## where
  - [ ] e2e-master
  - [ ] e2e-dalco-staging
  - [ ] e2e-dalco-production
  - [ ] e2e-aws-staging
  - [ ] e2e-aws-production

## how

[isolve-gpu]:(https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/isolve-gpu.js)
[isolve-mpi]:(https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/isolve-mpi.js)
[jupyters]:(https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/jupyters.js)
[mattward]:(https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/mattward.js)
[sim4life]:(https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/sim4life.js)
[sleepers]:(https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/sleepers.js)
[parallel_w_jupyters]:(https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/jupyters.js)

**Comment by pcrespov** [comment]
- delay db access (rm 300+ projects/test-user) AR
   - blocking calls also in gc routine (see logs)

**Comment by mrnicegyu11** [comment]
Just for completion:
For example:

    https://git.speag.com/oSparc/e2e-testing/-/jobs/1257622
    https://git.speag.com/oSparc/e2e-testing/-/jobs/1256871
    https://git.speag.com/oSparc/e2e-testing/-/jobs/1258205

This is also the case for aws-staging:

    https://git.speag.com/oSparc/e2e-testing/-/jobs/1257938
    https://git.speag.com/oSparc/e2e-testing/-/jobs/1258452
    https://git.speag.com/oSparc/e2e-testing/-/jobs/1258457

Error: `Tutorial error: Error: Evaluation failed: TypeError: Failed to execute 'text' on 'Response': body stream is locked at __puppeteer_evaluation_script__:14:43`
