### ISSUE TITLE
CC_Rabbit failing on Master

### ISSUE THREAD

**Issue by Surfict** [ITISFoundation/osparc-simcore#2685]
## what fails?
  - [ ] [isolve-gpu]
  - [ ] [isolve-mpi]
  - [ ] [jupyters]
  - [ ] [mattward]
  - [ ] [parallel_w_jupyters]
  - [ ] [sim4life]
  - [ ] [sleepers]

## where
  - [] [e2e/master]
  - [ ] [e2e/dalco/staging]
  - [ ] [e2e/dalco/production]
  - [ ] [e2e/aws/staging]
  - [ ] [e2e/aws/production]

[mattward]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/mattward.js
[isolve-mpi]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/isolve-mpi.js
[isolve-gpu]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/isolve-gpu.js
[sim4life]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/sim4life.js
[jupyters]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/jupyters.js
[sleepers]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/sleepers.js
[parallel_w_jupyters]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/tutorials/jupyters.js

[e2e/master]:https://git.speag.com/oSparc/e2e-testing/-/pipelines?page=1&scope=all&ref=master
[e2e/dalco/staging]:https://git.speag.com/oSparc/e2e-testing/-/pipelines?page=1&scope=all&ref=staging
[e2e/dalco/production]:https://git.speag.com/oSparc/e2e-testing/-/pipelines?page=1&scope=all&ref=production
[e2e/aws/staging]:https://git.speag.com/oSparc/e2e-testing/-/pipelines?page=1&scope=all&ref=staging_aws
[e2e/aws/production]:https://git.speag.com/oSparc/e2e-testing/-/pipelines?page=1&scope=all&ref=production_aws
----------

## what fails?
  - [ ] [2D_Plot]
  - [ ] [3D_Anatomical]
  - [ ] [3D_EM]
  - [ ] [Bornstein]
  - [ ] [CC_Human]
  - [x] [CC_Rabbit]
  - [ ] [Kember]
  - [ ] [Mattward]
  - [ ] [Voila]
  - [ ] [opencor]

## where
  - [x] [e2e/master]
  - [ ] [e2e/dalco/staging]
  - [ ] [e2e/dalco/production]
  - [ ] [e2e/aws/staging]
  - [ ] [e2e/aws/production]

[CC_Human]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/CC_Human.js
[Kember]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/Kember.js
[Mattward]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/Mattward.js
[3D_Anatomical]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/3D_Anatomical.js
[Voila]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/Voila.js
[2D_Plot]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/2D_Plot.js
[opencor]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/opencor.js
[CC_Rabbit]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/CC_Rabbit.js
[3D_EM]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/3D_EM.js
[Bornstein]:https://github.com/ITISFoundation/osparc-simcore/blob/master/tests/e2e/portal/Bornstein.js

[e2e/master]:https://git.speag.com/oSparc/e2e-portal-testing/-/pipelines?page=1&scope=all&ref=master
[e2e/dalco/staging]:https://git.speag.com/oSparc/e2e-portal-testing/-/pipelines?page=1&scope=all&ref=staging
[e2e/dalco/production]:https://git.speag.com/oSparc/e2e-portal-testing/-/pipelines?page=1&scope=all&ref=production
[e2e/aws/staging]:https://git.speag.com/oSparc/e2e-portal-testing/-/pipelines?page=1&scope=all&ref=staging_aws
[e2e/aws/production]:https://git.speag.com/oSparc/e2e-portal-testing/-/pipelines?page=1&scope=all&ref=production_aws

**Comment by Surfict** [comment]
Was failing in the week 05/12 07/12 and is now working again without apparent reasons.

**Comment by mrnicegyu11** [comment]
@odeimaiz its green now, did you manage to fix it? If so you may close and maybe briefly explain the fix :) Thank you, yours truly, BatMaN

**Comment by odeimaiz** [comment]
sporadic STARTED -> NOT_STARTED issue
