### ISSUE TITLE
Analysis and visualization (3D)

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#27]
**User story**

Some results will need visualization with 3d field viewers. As a **developer** I want to be able to visualize such data, for now defined in a file but using a data format that is flexible enough to be reused later on for the MVP, i.e. the output of unstructured LF solver (decision if structured or unstructured is used for MVP is not finalized yet - hopefully decided in early July).

**Definition of Done**
- [x] There is dedicated panel/view/dashboard in the frontend (3d view?, dashboard?)
- [x] There is a defined data structure for such results (vtk?)
- [x] The field viewer supports scalar and vector data
- [x] The field viewer can visualize slices and allows for selecting components of the field (real, imaginary parts)

**Use case**

Use mockup output data from the sim4life unstructured LF solver.

------------------------------

**User story (from user perspective)**

(suggestion how the user could do it)

- solids (e.g., from a modeling service) can be coupled to a suitable input port of the service
- so can result fields (3D scalar and vector for now, potentially time varying later) to an other input port
- inside the service a 3D view exists, as well as a selection of available fields (e.g., in a tree - or the Team comes up with another idea). in that tree, suitable viewers can be attached to the fields (initially i suggest at least a slice field viewer and perhaps a vector or isosurface viewer) which are then rendered along with the solids in the 3D view.
- when selecting such a viewer in the tree (or a better way of offering/selecting) the related settings appear

**Comment by sanderegg** [comment]
- [ ] get LF result from Sim4life
- [ ] convert file to 3D renderer compatible format
- [ ] upload the file with file manager
- [ ] define a library for displaying 3D model and slice viewers together (three.js, vtk.js, paraview.js)

- [ ] slice viewer, surface viewer

**Comment by drniiken** [comment]
REVIEW

SA

* exporting H field from a S4L project, LF -> VTK file

* file is being loaded now into the S3 storage (basement)

* new service, 3D viewer
* paraview web

* remote rendering
* sending images

* local and remote rendering

`* needs paraview-debranding

* interesting approach, very promising
