### ISSUE TITLE
STARTED -> NOT_STARTED

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#2706]
## Long story short

The e2e testing relies on the study /state to start checking the outputs/state of the services in the pipeline. This state sometimes goes from STARTED to NOT_STARTED instead of SUCCESS or FAILED, therefore, the tests keeps waiting until it reaches the timeout. 

Rabbits in master:
https://git.speag.com/oSparc/e2e-portal-testing/-/jobs/1272140

opencor in staging:
https://git.speag.com/oSparc/e2e-portal-testing/-/jobs/1274578

**Comment by sanderegg** [comment]
this was fixed. merry christmas.
