### ISSUE TITLE
Refactor to use tenacity

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2723]
with retry_unless_exception_type(CancelledError) | retry_unless_value(continue==False) and drop all this custom made code

_Originally posted by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/2722#discussion_r780137542_

**Comment by pcrespov** [comment]
@sanderegg can you put a sample here for ``retry_unless_value``? I do not see it in https://tenacity.readthedocs.io/en/latest/

**Comment by sanderegg** [comment]
we can use lambdas for checking the return value. but it was more of a concept. I will create an example when I have the time.

**Comment by sanderegg** [comment]
implemented
