### ISSUE TITLE
Maintenance: review and cleanup python formatting & static analysis tooling

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2731]
[common.Makefile](https://github.com/ITISFoundation/osparc-simcore/blob/dd94393e2474104e059686bfc13cb6ba2b18848d/scripts/common.Makefile#L105) has multiple recipes addressing code formatting and analysis that have overlapping functionality, namely:
- ``make autoformat``: runs ``isort`` and ``black``
- ``make codestyle``/ ``codestyle-ci``:
   - runs ``scripts/codestyle.bash``
       -  runs ``isort``, ``black``, ``pylint`` and ``mypy``
   - used also in ``ci`` (should not call make from CI!)
- ``make code-analysis``: 
    - runs ``scripts/code-climate``
         - docker run's ``codeclimate``
- ``make mypy``
   - runs ``scripts/mypy.bash``
         - docker runs ``mypy``

See issue  #2811 because we do not have in place a static-analysis in CI

**Comment by sanderegg** [comment]
@pcrespov you are working on this now right?

**Comment by pcrespov** [comment]
Implemented in SEE https://github.com/ITISFoundation/osparc-simcore/blob/master/scripts/common.Makefile#L112-L135
