### ISSUE TITLE
Must click several times Yes to accept confirmation

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2742]
in Master

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/1f0228a5-95a0-4e7c-adb2-f3ff8bc9ddee)

**Comment by odeimaiz** [comment]
Unable to reproduce... more information would be appreciated.
Was it a probe? An iterator converted into parameter and back several times?

**Comment by pcrespov** [comment]
> Unable to reproduce... more information would be appreciated. Was it a probe? An iterator converted into parameter and back several times?

Just deleting an of the nodes

**Comment by odeimaiz** [comment]
OK.... closing it since I'm not able to reproduce it.

**Comment by pcrespov** [comment]
Modal dialog gets duplicated ... 
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/bbbf46f2-e8f0-4f28-afdb-b734d00d5f29)
