### ISSUE TITLE
services with uvicorn do not auto reload in development mode

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2765]
## How to reproduce it

- deploy in dev mode the stack
```cmd
make build-devel
make up-devel
```
- open portainer and wait (a good time) until any uvicorn-based service is running (e.g. director-v2)
- change a file in the source code of the service 
- the server should auto restart but it does not

## What I have tried so far
 
- A similar behavior was detected when ``uvicorn >0.14`` released. Recent [update](https://github.com/ITISFoundation/osparc-simcore/commit/67a91d5261075fbe1a14c9bd6829faf43022bf88#diff-86d5fe588ff2fc7dccb1f4cdd8019d4473146536e88d7a9ede946ea962a91acbL39) *might* explain why it stopped working
- I have tested running a simple fastapi app with ``uvicorn 0.17.0.post1 with CPython 3.8.10 on Linux`` and works
```
$ uvicorn simple_app:app --host 0.0.0.0 --reload --reload-dir .
INFO:     Will watch for changes in these directories: ['/devel/src']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [40] using statreload.  <------------------------- STARTED WATCHER
INFO:     Started server process [42]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'simple_app/__init__.py'. Reloading... <------------------------- I CHANGED FILE
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [42]
```

This indicates that the problem might be in our boot scripts (``boot.sh``) or the fact that our volumes are mounted (i recall an issue in windows docker where watchdogs could not detect modifications on mounted volumes). I would suggest those as the lines to investigate

In addition, to this bug, we should take advantage of the new CLI options ``--reload-include`` and ``--reload-exclude`` options of uvicorn for [development](https://www.uvicorn.org/settings/#development)

**Comment by GitHK** [comment]
From what I've read, it should have something to do with the directory it is started from. This [post explains](https://stackoverflow.com/a/62934660/2855718) it. Would need a bit of your time in order to try out what they suggest.

**Comment by pcrespov** [comment]
> From what I've read, it should have something to do with the directory it is started from. This [post explains](https://stackoverflow.com/a/62934660/2855718) it.

That post is about not being able to start the server but not about auto reload. Those are two different things. 
In any case, our service is installed and when the .venv is active it can be imported from anywhere
