### ISSUE TITLE
Add line-seperation character for better multiline logs handling using logspout

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#2782]
As stated by @sanderegg , it is apparently fairly easily for us to add an "end-of--current-log" separation-character to aid the  grouping of multiline logs.

From the ops-side, we use a go regex to match the first line for a multiline-log using [logspout](https://github.com/gliderlabs/logspout). Once the regex is matched again, a new log-entry is started. All lines in between are considered as one multiline-log, starting with the first line, i.e. the one that matched the regex. (More info on this can be found in the logspout docker readme, we use `MULTILINE_MATCH=first` )

Currently we match `^(ERROR|WARNING|INFO|DEBUG|CRITICAL)[:]`. This fails when terminal-colors are logged, an PR fixing this is pending [here](https://git.speag.com/oSparc/osparc-ops-environments/-/merge_requests/15/diffs). 

Actionable tasks:
- Come up with a separation phrase or character that can be matched using a go-regex, but is non-intrusive when reading the logs. (Some non-perfect ideas: `OSPARC_LOG`, `!!\n`, ...)
- Implement it in simcore
- Add this match to the regex used in logspout

Thanks, let's discuss and see if we can do it.

**Comment by pcrespov** [comment]
Please @mrnicegyu11  check as well 
- #2204 
- #2157

**Comment by matusdrobuliak66** [comment]
as mentioned before we do not use logspout anymore, and other mentioned things are already discussed here https://github.com/ITISFoundation/osparc-simcore/issues/4079
