### ISSUE TITLE
oSPARC Framework, Design, Mockup

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#28]
STORY
Based on the current GUI/style/suggestion from the Team:

- [ ] Nik initiates and establishes a team and procedures to address all oSPARC platform GUI/design issues, user experience, perception, etc.
- [ ] 2 dedicated meetings next week (w 19)
- [ ] MVP GUI workflows and procedures are outlined and defined in detail
- [ ] mockups of GUI, workflows, situations are provided
- [ ] GUI design, style, perception are outlined and provided

**Comment by KZzizzle** [comment]
Very old issue - closing  now but can reopen when it becomes relevant again.
