### ISSUE TITLE
Set appropriate RAM limits on all services and enforce them strictly

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#2807]
This issue follows a talk with the POs and summarizes their expectations:

To make sure no further data is lost due to high RAM allocation of services...
- a maximum limitation on the usable RAM should be set for each service (this is to the best of my knowledge already the case). 
- These limits should now be revised according to our present infrastructure (i.e. no more 96Gb RAM limits if we don't have 96Gb RAM in any node). 
- The scheduling of services should from now on adhere strictly to those limits and schedule in such a manner, that the RAM of a machine may never be over-allocated or exceeded. If there is not enough RAM, a service cannot be started. If this more strict policy implies that we are not able to run enough services anymore, auto-scaling (i.e. spawning of new nodes) needs to enter the picture in the midterm.

It is also possible to have multiple versions of one service, with different RAM limits (8Gb version, 16Gb version, etc.), to help with this change.

For your consideration @GitHK @pcrespov @sanderegg @mguidon

**Comment by sanderegg** [comment]
AFAIK this was completed right. Feel free to close @mrnicegyu11

**Comment by sanderegg** [comment]
@mrnicegyu11 ? this should be closed I think.

**Comment by mrnicegyu11** [comment]
no this is not done I am afraid, we still did not align RAM of services scheduled on nodes with the available RAM of the nodes. We can move this to an operations-ticket if you want though.

**Comment by sanderegg** [comment]
@mrnicegyu11 I do not understand that need of aligning RAM of services.
Currently if you create a service that "requires" more RAM than available on any node, then it will not start and does not prevent other services from starting.
1. Use-case1: my biggest machine has 16GB and I start a service with 20GB reservation. it will stay pending and show an error in the logs. This does not prevent other services from running.
2. Use-case2: I start a service with 10GB reservation but currently other services are using more than 8GB. the service will stay pending and eventually fail with an error in the logs stating it cannot get enough resources. This does not prevent other services from running.
3. Use-case3: I start a computational service in the default cluster. if you ask for more than is available the service will fail and an error is shown in the logs.
4. Use-case4: I start a computational service in an external cluster. There is an [issue](https://github.com/ITISFoundation/osparc-simcore/issues/4153) tracking this. the Director-v2 complains. 

Therefore and as long as the dynamic services are having the same reservation and limit that should be fixed.

**Comment by mrnicegyu11** [comment]
@sanderegg 
What your wrote is accurate, I think I understood the ticket more widely than you. In this case close it please, yes :)


[ Some ops docker-services dont have proper RAM limits set, so this should definitely be done. But this barely touches the osparc-simcore repo actually, so while the technical details are similar the thing I am talking about might just be a vaguely related operations-only ticket]
