### ISSUE TITLE
osparc API extension and upload issue

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2808]
- Files
  - delete
   - classification mechanism: tag/folders?
   - filter
- Add better error when timeout error (e.g. use tenacity?)

**Comment by sanderegg** [comment]
@pcrespov do you know what this is about? that is for sure not a bug... please close if not applicable anymore

**Comment by pcrespov** [comment]
Obsolete. Enhancements on the public API in https://github.com/ITISFoundation/osparc-simcore/issues/2344
