### ISSUE TITLE
pylint does not capture critical syntax errors in webserver

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2811]
- bad config?
- not enough coverage?
- enable static-type analysis in the CI?

**Comment by pcrespov** [comment]
@sanderegg perhaps a solution to this can be the pre-commit hook you showed me a moment ago?

**Comment by sanderegg** [comment]
@pcrespov ... this kind of rings a bell about what you were working on with mypy too no?

**Comment by pcrespov** [comment]
> @pcrespov ... this kind of rings a bell about what you were working on with mypy too no?

@sanderegg yes, I will merge thisone with #2731

**Comment by pcrespov** [comment]
Included in #2731
