### ISSUE TITLE
Jupyterlab in AWS production doesn't shout down when there is an error in saving a study

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#2877]
## Long story short

Jupyterlab service not shutting down properly

## Steps to reproduce
Kudos to @KZzizzle for finding out what was going on. This is what happened:

1. A jupyterlab math on aws has >5gb data
2. Going to the dashboard triggers the error uploading to AWS
3. The container stays up even when back in the dashboard and the "closing lock" disappears
4. Going back in the study re-accesses the same live container

## Expected behavior
As an user who doesn't know what's going on I'd like.
1. A warning telling me that I won't be able to save the study because of the file limit (at least until this is solved)
2. See an error when I go back to the dashboard. What I saw was just the lock (for a long time).

## Your environment
osparc.io, The study name contains "Analyse", study id should be dedb95fa-9ec8-11ec-94c5-02420a0b024d

**Comment by GitHK** [comment]
@elisabettai maybe this is no longer valid?

**Comment by GitHK** [comment]
Will close for now, reopen if it manifests again
