### ISSUE TITLE
s4l as a service

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#29]
**User story**

As a developer I want to have a clear picture in mind how to create a non-UI s4l service running in a container.

**Definition of done**
- [x] Build minimal s4l modeling service without any user interface plugins
- [ ] Find common issues for different plugins and propose strategies how to fix them
- [ ] Python: I can import s4l_v1 without a GUI

in gitlab and shall contain:
- server: move and adapt
- clients
- Dockefile
- CI

**Comment by sanderegg** [comment]
[] compile XCore for linux using dockerfile

**Comment by sanderegg** [comment]
Created a dockerfile for linux (currently based on centos7) to compile. All test pass but some needing codecvt (possibly because of gcc version)

**Comment by sanderegg** [comment]
- [ ] compile LF solver for linux, dockerize
- [ ] compile XRpc worker for linux, dockerize

**Comment by sanderegg** [comment]
feature/SA/master/ThriftAddGLTFmethods
feature/SA/master/issue#29_Sim4LifeAsAService_moveUIToCore

**Comment by pcrespov** [comment]
## [Mithos](https://github.com/ITISFoundation/osparc-simcore/milestone/21) Milestone - dev notes
- [x] create repo with three services (two web and core)
- [ ] s4l-core
     - [x] move tree server to core and setup functionality
     - [ ] write operations (see case)   
     - [ ] sockets comm?
     - [ ] dockerize
- [ ] full deploy of pod

**Comment by pcrespov** [comment]
After release of rocket app by @mguidon , this case is not anymore up-to-date.
