### ISSUE TITLE
Sharing services on master is no longer possible

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-simcore#2923]
## Long story short
I tried to share a service (owned by me) on master. Selecting a group gives a weird GUI problem and doesn't actually share the service. In fact, the service itself disappears until another refresh. 

## Expected behaviour
I am able to share the study and receive a confirmation message that the service has been shared (as before).
![sharing_bug](https://user-images.githubusercontent.com/28002886/160568782-af95ef16-3d32-4f28-bad6-718cd5d0f597.gif)

**Comment by odeimaiz** [comment]
Reproducible when sharing with certain organizations (ie, Z43)...

The weird thing is that when adding other members, everything looks fine, but the DB is not updated.... I found the request in the webserver and catalog, but the DB remains untouched.

**Comment by KZzizzle** [comment]
Possibly related - I seem to sometimes "lose" services that are owned by myself but not shared. 

- In services tab, I only see services shared with "Everyone"
- Refreshing (with devtools open) does not bring them back
- No obvious errors in Network requests
- Creating a study and then opening the service catalog will show all services I have access to again
