### ISSUE TITLE
Improvements and bugs on UI/UX for Annotations section

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2955]
I do not think Annotations belong next to Checkpoints & iterations (meta) . Why not to move it "near to the mouse pointer" e.g. in the wheel that appears with left click?
![image](https://user-images.githubusercontent.com/32402063/161384851-ec90f8e8-203c-4459-a4de-2bd07dbeb90b.png)

**Comment by odeimaiz** [comment]
The Annotations section will stay there, but it might also be added to The Wheel
