### ISSUE TITLE
✨ In Release-Process: Warn when docker images have not been built successfully

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#2969]
**USER STORY:**

If the Github-Actions CI Run corresponding to the latest commit on the master-branch has failed, no docker image is built and uploaded to dockerhub. If one then releases to staging, the re-tagging cannot be performed.

In this case, at some point in our release-process an error should be presented, indicating that the release failed.

Likely, the Github-CI Action corresponding to the staging-release should not show "green" and quietly skip the re-tagging steps but explicitly fail ("red"), indicating failure.

I will at the very least add this case to the docs for creating a release in osparc-simcore.

Please discuss!
@pcrespov @Surfict @sanderegg

**Comment by pcrespov** [comment]
@mrnicegyu11 so what is the action here? why did you close it?
