### ISSUE TITLE
Cardiac Tissue model (myocytes) from Colleen Clancy (C++ code)

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#3]
**User story**

As a **user** I want to create a pipeline consisting of the cardiac tissue model from Colleen Clancy and a post-processing service that reproduces the plots in the official MVP use case. I am able to edit all necessary input settings directly in the frontend. Optionally, I would like to have the option to choose a compiler and compiler flags in case I want to build the kernel first.

**Definition of Done**
- [x] The model is available in the list of services
- [x] The required pipeline can be created
- [x] The code is containerized as binary and as code only with compilation performed on the fly
- [x] For the second part of the pipeline, either python or octave/matlab will be used
- [x] check if there is a need/possibility to have settings (property window)
- [x] the results of the python postpro script should be mapped as time series to the outputs, such that they can be visualized with the 2d plot service (item was modified)

**Use case**
There is documentation/code/Kepler example for this case in filesrv. In addition, the full workflow is available on MaG's VM.

**Comment by esraneufeld** [comment]
[] containerize
[] two coupled services: 1. running the model (C++ code, i think) & 2. performing the postprocessing (currently matlab, port to python service or octave service and use standard viewers)
[] check if there is a need/possibility to have settings (property window)
[] probably we want the results to be outputted in a standardized way, compatible with, e.g., standard viewers
[] optional: also permit a container type, where the executable is not precompiled and containerized, but where compilation is a preprocessing step executed by the container

**Comment by mguidon** [comment]
for the future: https://mybinder.org/

**Comment by esraneufeld** [comment]
the option to first compile the code is lower priority than the rest of this case.

**Comment by sanderegg** [comment]
- [ ] upload 2 input data files to S3
  - [ ] filereader node
- [ ] allow defining 6 parameters
  (- [ ] optional parameter as file that disables the 6 parameters)
- [ ] set the pipeline configuration in the workbench-database
- [ ] solver(s) must be dockerized and available as dynamic service(s)
- [ ] label docker image with ports configuration (services)
- [ ] list of computational services
  - [ ] director
  - [ ] frontend
- [ ] pipeline control
  - [ ] director
  - [ ] frontend
- [ ] connect logger frontend-services
  (- [ ] push logs to database)
- [ ] 2D viewer: 
  - [ ] add the 6 plots to the jupyter node
  - [ ] connect to S3/database
  - [ ] dockerize - make available as service

**Comment by drniiken** [comment]
For the very moment, we are happy with the Jupyter based 2D plot visualization.
