### ISSUE TITLE
On Windows Deployments using Docker Desktop, comp. jobs cannot be run

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3012]
## Long story short

On Windows Dpeloyments using Docker Desktop, comp. jobs cannot be run.

This is due to the input-files not being copied into the computational service's container. This again is caused by the `computational_shared_services` named volume being accessed via its bind-path, which on wsl2 is `/var/lib/docker/.......`. However, it turns out that when Docker Desktop with the wsl2 backend is used, the path is actually fake. In reality, the data of named volumes is stored in a second wsl2 distro (see https://www.docker.com/blog/new-docker-desktop-wsl2-backend/ ).

So, as Docker Developers seem to not guarantee that named volumes can be accessed via their path in all environments, we should only access named docker volumes via their name, and not their possibly not accessible bind mount path.

The solution proposed by @sanderegg is to deprecate the `shared_computational_data` volume and use only bind mounts, which seems to fix the issue.

## Expected behaviour

Comp. Services work

## Actual behaviour

Comp. Services fail

## Steps to reproduce

- Checkout `osparc-local` branch of osparc-ops-repository.
- Run `make up-local`
- Run `cd scripts/provisionDatabase && make up`
- Create user "test@example.org"
- Start sleeper
- Watch sleeper fail

## Your environment

oSparc Full-Ops Local on WSL2 with Docker Desktop

**Comment by sanderegg** [comment]
@mrnicegyu11 do you still want to keep it open if it's fixed using pure WSL?

**Comment by mrnicegyu11** [comment]
maybe add a wontfix label

**Comment by sanderegg** [comment]
since we do not officially support windows, I think that issue is not worth keeping.
and also this is fixed by using WSL2 (I actually updated the README.md)
if it's ok with you @mrnicegyu11 let's close this.

**Comment by mrnicegyu11** [comment]
This is to the best of my knowledge not fixed in WSL2, unless you moved away from accessing named volumes via bind-mounts in the comp-services.
I would be happier to leave this issue open and add the common `wontfix` label for now.

**Comment by sanderegg** [comment]
@mrnicegyu11 I am able to run jobs on my computer with WSL2 so I guess there must be something fishy in your configuration?

**Comment by mrnicegyu11** [comment]
This issue concerns docker on wsl2 installed using docker desktop, as is the recommended way to run docker on windows/wsl2 by the official docker docs.

If docker is installed in wsl2 using apt, this issue will not occur. @sanderegg

**Comment by sanderegg** [comment]
yes which is not the way the README.md tells to install WSL2 + there is no official support of windows see following snapshot of the official simcore README:
![image](https://user-images.githubusercontent.com/35365065/181444238-4f8aef51-4cac-4a57-a7b6-d6884c7f39da.png)
Therefore I propose to close the issue.

**Comment by mrnicegyu11** [comment]
fine by me
