### ISSUE TITLE
allow setting user specific parameters to start services

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3022]
It is desirable to be able to define a specific machine where a service shall run.

To this end the plan is to:
1. create a DB table ```services_specifications``` (GroupID{ForeignKey}, ServiceKey{ForeignKey}, ServiceVersion{ForeignKey}, Specs{JSONB})
2. There we could add under Specs, how the service startup shall be modified/overriden
3. The catalog shall be responsible for the REST API to get these specs
4. When a dynamic service is started, the director-v2 shall get the information about the service (based on the current user), and it they exist apply them to the dynamic sidecar*sub services*

**Comment by mguidon** [comment]
This sounds good. We would use the logic as discussed, that we let only services with all these additional tags run there and none other? (except some necessary monitor/platform services)

**Comment by sanderegg** [comment]
> This sounds good. We would use the logic as discussed, that we let only services with all these additional tags run there and none other? (except some necessary monitor/platform services)

Each time a service is started, we check if the group's user has some specifications for the service, we add them. I think that should be quite flexible.

**Comment by sanderegg** [comment]
## Goal for sprint [Athena](https://github.com/ITISFoundation/osparc-issues/milestone/37)
- allow setting specific service resources in the database only (no user friendly interface for now)
