### ISSUE TITLE
create parameters for array type ports does not work as expected 

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3035]
E.g. for boolean ports we can ``set new parameter``
![Pasted image 20220510154410.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/bf5ae0c7-9094-4175-b40a-387e0c8599f3)
but not for array-type ports
![Pasted image 20220510154343.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/91265a6d-3a7e-49ff-91d5-411f86bf8740)

**Comment by odeimaiz** [comment]
duplicated https://github.com/ITISFoundation/osparc-simcore/issues/3061
