### ISSUE TITLE
Maintenance: test with scicrunch AddexBIo fails

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3043]
```
services/web/server/tests/integration/02/scicrunch/test_scicrunch__resolver.py::test_scicrunch_resolves_all_valid_rrids[AddexBio Cat# C0006007/65-CVCL_0033] FAILED [ 48%]
```
from [https://github.com/ITISFoundation/osparc-simcore/runs/6423692060?check_suite_focus=true](https://github.com/ITISFoundation/osparc-simcore/runs/6423692060?check_suite_focus=true)

Currently disabled in [https://github.com/ITISFoundation/osparc-simcore/blob/03a8b7fe5ea0c86ee6707b757bb6e4c1a05d197e/services/web/server/tests/integration/02/scicrunch/test_scicrunch__resolver.py](https://github.com/ITISFoundation/osparc-simcore/blob/03a8b7fe5ea0c86ee6707b757bb6e4c1a05d197e/services/web/server/tests/integration/02/scicrunch/test_scicrunch__resolver.py)

**Comment by sanderegg** [comment]
@pcrespov that was fixed right? close?

**Comment by pcrespov** [comment]
@sanderegg no, i still have to check thisone

**Comment by pcrespov** [comment]
# FIXME: PC check the CELL_LINE_CITATIONS test please

**Comment by sanderegg** [comment]
@pcrespov can we close this now?

**Comment by pcrespov** [comment]
REactivated
