### ISSUE TITLE
When dynamic service fails badly, ALL studies are blocked

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-simcore#3081]
## Long story short

when a dynamic service is failed but the container somehow is not removed, this blocks the user from opening any studies

## Actual behaviour

no studies of this user can be opened anymore

## Steps to reproduce

A service failed in a study and after the study was closed, the container of the failed service was not removed (in this case it was a dsistudio-app, which is half of a novnc service)
When the user who owns that study tries to open ANY other study (or create a new one), the entry is created in the database, but director-v2 complains:
```
    return [
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/director_v0.py", line 161, in <listcomp>
    RunningDynamicServiceDetails(**x)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RunningDynamicServiceDetails
service_port
  none is not an allowed value (type=type_error.none.not_allowed)
  ```
The frontend gets error:
```
{"error": {"status": 400, "errors": [{"code": "type_error.uuid", "message": "value is not a valid uuid", "resource": "/v0/projects/${STUDY_UUID}:open", "field": "project_id"}]}}
```
for EVERY study the user owns.

**Comment by KZzizzle** [comment]
For me it was dsi-studio but I think @elisabettai also experienced this with her spinal-segmentation service

**Comment by GitHK** [comment]
This was addressed and is no longer a case.
