### ISSUE TITLE
Investigate Dask-Scheduler KeyError

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3113]
Querrying our deployments with graylog for `"KeyError" AND container_name: /.*dask-scheduler.*/` shows multiple KeyErrors occuring.

These key errors seem to be related to the dask-sidecar getting into a non-working state on dalco on wed 15/6/22.

@sanderegg wrote:

```
ok it looks like the dask scheduler is unhappy and not recovering. I'll restart it for now.
there were also computational jobs with illegal job_ids
I am not sure if that is a reminiscent of the old computational backend or something else. there is a bug entry already for this. I will check in the other deploys anyway
so restarting the dask-scheduler has fixed the logs issue... 
I[t] looks like the dask-scheduler is not resilient to disappearing clients in some use-case
```

Until there is some clarity on this `KeyError` log, I will not add a graylog email alert for this (since it occurs regularly it seems, semi-daily basis on some deployments)

Please let me know when this issue is resolved, I will then add the email-alert as discussed :)

**Comment by sanderegg** [comment]
This never happened again. closing.
