### ISSUE TITLE
dy-sidecar started containers missing reboot options

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3142]
All started containers, spawned during `docker-compose up` lack a restart policy.

1. we need to investigate what happens with the services when they are restarted
2. decide what restart policy should be used.

**Comment by pcrespov** [comment]
Why not use the ``restart`` API entrypoint and wire it all the way to the front-end so the user can restart the service if he/she wishes.

For the moment the user does not get any real-life feedback of the status of the container/s. It would be necessary to add yet another entrypoint for that as well.

**Comment by pcrespov** [comment]
Implemented in #3239
