### ISSUE TITLE
review logs security

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3148]
Review logs regarding security hotspot note https://sonarcloud.io/project/security_hotspots?id=ITISFoundation_osparc-simcore&pullRequest=3147&hotspots=AYGpcPQIVRfTUi-N8-IQ

**Comment by pcrespov** [comment]
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/7049794b-3977-4e62-90ef-badf8a227114)

**Comment by pcrespov** [comment]
## Recommended Secure Coding Practices

-   Check that your production deployment doesn’t have its loggers in "debug" mode as it might write sensitive information in logs.
-   Production logs should be stored in a secure location which is only accessible to system administrators.
-   Configure the loggers to display all warnings, info and error messages. Write relevant information such as the precise time of events and the hostname.
-   Choose log format which is easy to parse and process automatically. It is important to process logs rapidly in case of an attack so that the impact is known and limited.
-   Check that the permissions of the log files are correct. If you index the logs in some other service, make sure that the transfer and the service are secure too.
-   Add limits to the size of the logs and make sure that no user can fill the disk with logs. This can happen even when the user does not control the logged information. An attacker could just repeat a logged action many times.

Remember that configuring loggers properly doesn’t make them bullet-proof. Here is a list of recommendations explaining on how to use your logs:

-   Don’t log any sensitive information. This obviously includes passwords and credit card numbers but also any personal information such as user names, locations, etc…​ Usually any information which is protected by law is good candidate for removal.
-   Sanitize all user inputs before writing them in the logs. This includes checking its size, content, encoding, syntax, etc…​ As for any user input, validate using whitelists whenever possible. Enabling users to write what they want in your logs can have many impacts. It could for example use all your storage space or compromise your log indexing service.
-   Log enough information to monitor suspicious activities and evaluate the impact an attacker might have on your systems. Register events such as failed logins, successful logins, server side input validation failures, access denials and any important transaction.
-   Monitor the logs for any suspicious activity.

## Sensitive Code Example
```python

import logging
from logging import Logger, Handler, Filter
from logging.config import fileConfig, dictConfig

logging.basicConfig()  # Sensitive

logging.disable()  # Sensitive


def update_logging(logger_class):
    logging.setLoggerClass(logger_class)  # Sensitive


def set_last_resort(last_resort):
    logging.lastResort = last_resort  # Sensitive


class CustomLogger(Logger):  # Sensitive
    pass


class CustomHandler(Handler):  # Sensitive
    pass


class CustomFilter(Filter):  # Sensitive
    pass


def update_config(path, config):
    fileConfig(path)  # Sensitive
    dictConfig(config)  # Sensitive

```

## See

-   [OWASP Top 10 2021 Category A9](https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/) - Security Logging and Monitoring Failures
-   [OWASP Top 10 2017 Category A3](https://www.owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure) - Sensitive Data Exposure
-   [OWASP Top 10 2017 Category A10](https://owasp.org/www-project-top-ten/2017/A10_2017-Insufficient_Logging%2526Monitoring) - Insufficient Logging & Monitoring
-   [MITRE, CWE-117](https://cwe.mitre.org/data/definitions/117) - Improper Output Neutralization for Logs
-   [MITRE, CWE-532](https://cwe.mitre.org/data/definitions/532) - Information Exposure Through Log Files
-   [SANS Top 25](https://www.sans.org/top25-software-errors/#cat3) - Porous Defenses

**Comment by matusdrobuliak66** [comment]
https://github.com/ITISFoundation/osparc-simcore/issues/4079#issuecomment-1527665530
