### ISSUE TITLE
SetuptoolsDeprecationWarning: Upgrade setup to PEP517

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3151]
Just enter a service/app and
```cmd

$ make info
/home/crespo/devp/osparc-simcore/.venv/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.

``` 

SetuptoolsDeprecationWarning: setuptools.installer is deprecated. 
- Requirements should be satisfied by a PEP 517 installer.

**Comment by sanderegg** [comment]
resource for migrating from pck_resources: https://importlib-metadata.readthedocs.io/en/latest/migration.html
