### ISSUE TITLE
Make docker_compose_down reliable

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3172]
Change:
- this functions should raise an error if containers are still present by the time if finishes. 
- refactor to change order of operations (first run dowcker-compose down and then remove the pending stopped containers)
- add a regression test to ensure this happens and then fix

https://github.com/ITISFoundation/osparc-simcore/blob/3f88ad3d6340b40d616db8c4d0eee80d47da44ed/services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/core/docker_compose_utils.py#L75-L99

**Comment by pcrespov** [comment]
@GitHK I am working on these functions right now, may I take thisone?
