### ISSUE TITLE
🐛 : socketio-session is empty in webserver `simcore_service_webserver.socketio.handlers:disconnect(183)`

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3199]
Socketio-session is empty in webserver `simcore_service_webserver.socketio.handlers:disconnect(183)`

This warrants an investigation.

- The log is `Unknown client diconnected sid: 95d55469880e48a2a261243393e60ed6, session {}`, augmented with comment "this should never happen" in the code
- Check the errror at permalink `/graylog/messages/graylog_120/d713c1f0-07fd-11ed-9204-0242ac130007` on `dalco-prod`

## Actionable follow-up
- [ ] Trace this error
- [ ] Either fix this occuring, or if it is non-ciritical and doesnt impact the user experience, make this (that it doesnt need to be investigated further, dont log on loglevel error but warning) clear in the error log upon this happening.

**Comment by pcrespov** [comment]
@sanderegg could you please check thisone? I think the sticky requests should take care of this, right? perhaps we missed something when we separated the servers

**Comment by sanderegg** [comment]
I think that if for some reason redis DB is reset you might get into this situation.

**Comment by sanderegg** [comment]
outdated. closing
