### ISSUE TITLE
Modeling: Issues in the Modeler

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#32]
- [x] Add visibility checkboxes to the tree view
- [x] Usage of External modeler is broken in sphere/spline creation since GLTF transfer was added
- [x] Fully support window resizing
- [x] Allow multiselection by picking
- [x] Enable rotation while creating entities interactively
- [ ] Move/Rotation handles should be centered in the object they are applied to
- [ ] Clicking outside the object should reset the move/rotate buttons
- [ ] Check what happens with the websocket when server gets restarted
- [ ] The version of the client should be available in the GUI, and the tag on the docker image should be set up automatically if possible
- [ ] After a sphere was added, the button should unclick itself as it is not possible to create another sphere right away (or it should be still possible to create another sphere and then the state is correct)
- [ ] The invisible plane is not functioning correctly when creating several shapes (create 2 cylinders, then it's not possible to define the height of a third cylinder if the mouse is not hovering onto the previous 2 cylinders)
- [ ] The selection state is reset when creating a new object. The buttons do not reflect this. And actually it should either be unclicked or it should maintain the selection mode.
- [ ] After the first s4l spline is created, creating a second one blocks after 2 control points are set.

**Comment by sanderegg** [comment]
- [ ] Move/Rotation handles should be centered in the object they are applied to
- [ ] Clicking outside the object should reset the move/rotate buttons
- [ ] Usage of External modeler is broken in sphere/spline creation since GLTF transfer was added

**Comment by odeimaiz** [comment]
deprecated
