### ISSUE TITLE
Issue with service specifications

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3212]
If I setup and entry inside `services_specifications` which overwrites the memory and CPU limits, like the following CSV:

```
service_key,service_version,gid,sidecar
simcore/services/dynamic/jupyter-smash,3.0.7,2,"{""TaskTemplate"": {""Resources"": {""Limits"": {""NanoCPUs"": 4000000000, ""MemoryBytes"": 43687091200}}}}"
```

### The following happens:

1. The `dynamic-sidecar` has its limits set to what is specified above (overwrite OK)
1. The created container running the `jupyter-smash` has the original limit (not overwritten)

--- 

### Conclusions after investigation

- The webserver fetches the information regarding he limits from the catalog via the  `service resources endpoint (catalog)` and passes down the information to the director-v2 who uses it to start the service.
- Clearly the `service specifications endpoint (catalog)` is used and the data is injected to the dynamic-sidecar when the service is started and overwrites the information about the resources coming from the webserver.
- The `service specifications` are only applied to the dynamic-sidecar.

### Questions

- Should the `service specifications` also apply to the containers created by the dynamic sidecar? ( I guess no since these are mainly used as placement constraints and it was never intended to be used as showcased above)
- To obtain what I want to do above, I guess the webserver should inject the changed values as discussed prior to this.

@sanderegg care to elaborate more on this topic and what was the original goad and what it should be able to do or not to do.

**Comment by sanderegg** [comment]
@GitHK : this is not a bug. This has never been implemented due to lack of resources. You can only override the dy-sidecar specifications as per design. The rest of that feature (ref missing) will come once resources are freed to do so.

**Comment by GitHK** [comment]
I agree this is not a bug. Closing
