### ISSUE TITLE
Computational node fails to upload file

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#3213]
## Long story short

A computational node (ascent-runner) failed while uploading the results (it happened at least 2 times). In the frontend (logger) I saw that it failed during uploading (once at ~60%, the other time time at ~90%. If I remember well, the file size was in the order of 100MB.
project_id: f5ec048e-099c-11ed-9335-02420a0b00f3
node_id: 3d5166eb-cfbe-4afe-9b4e-4da6b518cf53

This happened on S3 (osparc.io)

## Expected behaviour

It doesn't fail uploading.

## Actual behaviour

If fails while uploading and the user has to re-run the node (which take quite some time).

I was able to capture some hopefully useful message in Graylog (this happened around 13:00 UTC on 22-07-2022)

```
WARNING:simcore_service_storage.simcore_s3_dsm:Error in 1-th concurrent task <coroutine object SimcoreS3DataManager._update_database_from_storage_no_connection at 0x7f6f58c1f8c0>: The file f5ec048e-099c-11ed-9335-02420a0b00f3/3d5166eb-cfbe-4afe-9b4e-4da6b518cf53/logs.zip  in production-simcore was not found

WARNING:simcore_service_storage.simcore_s3_dsm:pending/incomplete uploads of [['f5ec048e-099c-11ed-9335-02420a0b00f3/3d5166eb-cfbe-4afe-9b4e-4da6b518cf53/logs.zip', 'f5ec048e-099c-11ed-9335-02420a0b00f3/3d5166eb-cfbe-4afe-9b4e-4da6b518cf53/envs', 'f5ec048e-099c-11ed-9335-02420a0b00f3/3d5166eb-cfbe-4afe-9b4e-4da6b518cf53/ascent_results.zip']] removed

WARNING:simcore_service_storage.simcore_s3_dsm:Dangling multipart uploads '[('_dwWRe3Tj5XbpsoFQwDHby4jPDXWHdaFpBCSbeG.RmmefJuTVmEKwctKXcWRCdA0qZhAY9Lw3KHNk4wdrgjlc6csG8wOSjcem0UwS8rZVXboMYhYP3a1RHqVG8ZfrVHb', 'f5ec048e-099c-11ed-9335-02420a0b00f3/3d5166eb-cfbe-4afe-9b4e-4da6b518cf53/ascent_results.zip')]', were aborted. TIP: There were multipart uploads active on S3 with no counter-part in the file_meta_data database. This might indicate that something went wrong in how storage handles multipart uploads!!
```

## Steps to reproduce

Create a node in osparc.io, using the latest version of ascent-runner. Here are inputs I had:
![image](https://user-images.githubusercontent.com/18575092/180733961-f90e3a03-ac34-434b-ac30-648f5c0715e2.png)

## Your environment
osparc.io

**Comment by sanderegg** [comment]
this might be fixed at some point in #3217 . Closing this one as duplicate
