### ISSUE TITLE
Rabbit connection closed blocks dy-sidecar from saving state

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#3225]
Happened on dalco prod, around 11 AM (UTC) on 27 Jul 2022.

Study id `e3703ef0-0740-11ed-944c-02420a0b019c ` was taking forever to close, a jupyter-smash (id `9bd81e40-3456-4c2c-a9d7-e796c91f92b3`) was the culprit.

The dy-sidecar associated with the jupyter-smash successfully saved some of the stuff, but then it had this error:
```
ERROR:/home/scu/.venv/lib/python3.9/site-packages/simcore_service_dynamic_sidecar/core/rabbitmq.py:Rabbit connection closed with exception from amqp://admin:******@production_rabbit:5672/?name=simcore_service_dynamic_sidecar.core.rabbitmq_139999222982448_7
```

@GitHK tried to save the state manually, but it didn't work, since we had:

`simcore_sdk.node_ports_common.exceptions.S3InvalidPathError: No object in S3 storage at e3703ef0-0740-11ed-944c-02420a0b019c/9bd81e40-3456-4c2c-a9d7-e796c91f92b3/workspace.zip`

The S3InvalidePathError is weird, because the file was actually present in the storage (from a previous save 2 days before).

After the fact, I've searched a bit in graylog.
There's a [director-v2 error](https://monitoring.osparc.speag.com/graylog/messages/graylog_127/2a19aef1-0da3-11ed-9204-0242ac130007) 
Maybe there's more.

**Comment by GitHK** [comment]
This is unrelated to rabbitmq. It is an error that happens if the service is no longer present in the database and we try to save to s3. Closing this
