### ISSUE TITLE
use aiodocker and get a nice progress of the pulling

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3229]
For another PR: instead of using docker-compose in the CLI, you could actually use aiodocker and get a nice progress of the pulling, which would be sent back via Rabbit to the logs.

_Originally posted by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/3211#discussion_r932130496_

**Comment by pcrespov** [comment]
Check dask sidecar for aiodocker.pull -> throw in logs
