### ISSUE TITLE
Computational node fails to upload files (after a re-run)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#3230]
## Long story short
A computational service fails to upload the results, with:
```
Tue Aug 02 2022 15:28:03 GMT+0200 (Central European Summer Time) INFO 29cd40f5-a656-4434-8c9a-c327388425b2 ascent-runner: [sidecar] Task error:
The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. 
```
I am attaching the full logs from the logger. [logs_ascent-runner_failedUploading.log](https://github.com/ITISFoundation/osparc-simcore/files/9242892/logs_ascent-runner_failedUploading.log)

## Some hints
The first time I run the service it run successfully, but the second time it failed uploading. I then re-tried to run and @sanderegg found in the database (`file_meta_data` table) that `upload_expires_at` was briefly filled in with the correct date, but then was overridden with `NULL`. The re-run also failed

## Steps to reproduce

Based on what I did, I think we can reproduce it (on AWS prod) by:
1. Add an ascent-runner node, run it with default input parameters
2. Run it a second time

(When I actually got the error, I went back to the dashboard between 1 and 2.)

## Your environment
osparc.io

**Comment by elisabettai** [comment]
Small update: I've re-run again and it worked.

**Comment by sanderegg** [comment]
@elisabettai shall we close this? is this still happening?

**Comment by sanderegg** [comment]
@elisabettai can we close this or is it still happenning?

**Comment by sanderegg** [comment]
@elisabettai I fixed an issue [there](https://github.com/ITISFoundation/osparc-simcore/pull/4242) maybe this is definitively fixed. can we close?
