### ISSUE TITLE
stacktraces & unhandled errors in storage microservice

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3238]
## Long story short

On the 4th of August on `osparc.io`, the storage microservice's logs showed multiple unhandled exceptions that require investigation. While the service appeared still functional, the cause and imapct of the errors are for now unclear. The logs are attached to this issue.

Related: The info message which is printed when dangling multipart uploads are detected can be adjusted from:
`TIP: There were multipart uploads active on S3 with no counter-part in the file_meta_data database. This might indicate that something went wrong in how storage handles multipart uploads!!`
to
`TIP: There were multipart uploads active on S3 with no counter-part in the file_meta_data database. This might indicate that something went wrong in how storage handles multipart uploads, or, that data was attempted to be uploaded directly to S3 without going through the storage API.`

[production-simcore_production_storage_logs.txt](https://github.com/ITISFoundation/osparc-simcore/files/9279606/production-simcore_production_storage_logs.txt)

Thanks

**Comment by sanderegg** [comment]
several issues were fixed lately and released to production. therefore this issue shall be closed.
