### ISSUE TITLE
After opening a big study, input files disappeared and trigger error

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3244]
AFter opening TN big study.

Surface Extraction node reports: Unable to pull inputs

It seems the input zip file got deleted?

**Comment by mrnicegyu11** [comment]
... And maybe outputs are pulled t
[_dy-sidecar_838eea0e-e1ff-4c9a-a3a2-9051caab3b6a.1.d7cw0wgl4rwg7f1yl9coiyqek_logs.txt](https://github.com/ITISFoundation/osparc-simcore/files/9291630/_dy-sidecar_838eea0e-e1ff-4c9a-a3a2-9051caab3b6a.1.d7cw0wgl4rwg7f1yl9coiyqek_logs.txt)
wice

**Comment by pcrespov** [comment]
@sanderegg do you think this is related with #3306 ?

**Comment by sanderegg** [comment]
@pcrespov yes

**Comment by sanderegg** [comment]
I can close that entry I think

**Comment by sanderegg** [comment]
fixed by #3306
