### ISSUE TITLE
dy-sidecar: sometimes containers are stuck in "created" state

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3247]
It was observed that often when TN starts his study in AWS that:
- some services are stuck in "Created" state (jupyter-smash and/or iseg)

a workaround (works only for jupyter-smash) is to go to portainer select the container and press the "start" button which makes it starts beautifully.

Why this happens is unclear. 

From quickly scanning the code in [https://github.com/ITISFoundation/osparc-simcore/blob/40720c7726f4856f508d59a9eac8d359999b2fe6/services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py](https://github.com/ITISFoundation/osparc-simcore/blob/40720c7726f4856f508d59a9eac8d359999b2fe6/services/dynamic-sidecar/src/simcore_service_dynamic_sidecar/modules/long_running_tasks.py)
lines 77-80 it can be seen that:
- ```docker-compose up --detach --no-build --detach``` is called
- ```docker-compose start``` is called right afterwards

From the documentation ```docker-compose up --detach``` states that it runs in the background. My question would be when is the control coming back then? is calling ```docker-compose start``` right behind really the way to go?
What about doing in that case ```docker-compose create``` and then ```docker-compose start``` instead? Cause right now it kind of defeat the purpose of using the ```up``` command...

**Comment by pcrespov** [comment]
Still needs to be tested in staging before closing this
