### ISSUE TITLE
Executable bits in file permissions not persistent

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#3273]
## Long story short

Files in the workspace folder with the executable bit set are recreated without it after restart of the service.

Priority: Low for now

**Comment by sanderegg** [comment]
@mguidon @GitHK is this still a thing? please close if not.

**Comment by GitHK** [comment]
I think is still a thing that we cannot fix. @mguidon can provide more feedback here. I think he found a way to deal with this for his use case.

**Comment by GitHK** [comment]
closing this, no more replies

**Comment by mguidon** [comment]
I think this was a missing command line argument for rclone (--metadata or similar). I guess it was taken over with the new approach
