### ISSUE TITLE
Catalog cannot handle deployment with only tis product

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#3288]
## Long story short

On the `tis` deployment, there is only the `tis` product available. The `catalog` service somewhere expects a `osparc` product. I might find back the error message

**Comment by pcrespov** [comment]
Might have to do with the ``CATALOG_ACCESS_RIGHTS_DEFAULT_PRODUCT_NAME`` env var.  
https://github.com/ITISFoundation/osparc-simcore/blob/a501cc6910be6268476b37846804f266e10f77a7/services/catalog/src/simcore_service_catalog/core/settings.py#L71

Can you set it to ``CATALOG_ACCESS_RIGHTS_DEFAULT_PRODUCT_NAME=tis`` and see?
