### ISSUE TITLE
dy-sidecar does not create all containers

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3293]
For services like iSeg and Sim4Life which require multiple docker images to run, sometimes not all the containers are created.

Solution:
- replace the buggy `docker-compose up` with `docker-compose create` since it's basically doing this.
- retry to create with `--force-recreate` option if not all containers were created

**Comment by sanderegg** [comment]
@GitHK be careful with this.
docker-compose create +start is not equal to docker-compose up

Please carefully check... networks are not created the same. test it in the bash console and you will see

**Comment by GitHK** [comment]
Thanks for pointing it out. I will investigate a bit more on how to do this.
