### ISSUE TITLE
Amazon Follow-Up

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#33]
**User story**

As a **user** I want to make sure that the platform runs as cost effective as possible. Only the absolutely necessary services should run 24/7. Other computational resources shall be allocated dynamically on-demand.

**Definition of done**

- [ ] Identify parts of the platform that need to be up and running permanently
- [ ] Integrate AWS python SDK for allocating resources

**Use case**

Dag scheduler works with dynamically allocated hardware.

**Comment by mguidon** [comment]
Replaced by new issue #496
