### ISSUE TITLE
add an a test to cover the following case

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3313]
So apparently the migrated bladder control project to master si good for catching corner cases which are not covered by the CI. Like for example testing out archiving of multiple output ports containing files.

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/3bd8m8pewi8npbmzy5sxwug34r) *by @GitHK*._

**Comment by sanderegg** [comment]
closing this issue. feel free to re-open if it means anything @GitHK
