### ISSUE TITLE
do not start deprecated services

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3334]
If a service was deemed as deprecated it should not be started and maybe even show a new service state such as
```deprecated```

**Comment by pcrespov** [comment]
@sanderegg is ithis closed? how can I help here?

**Comment by sanderegg** [comment]
All good I will close it

**Comment by sanderegg** [comment]
I still need some stuff from @odeimaiz

**Comment by pcrespov** [comment]
@odeimaiz added missing part.
