### ISSUE TITLE
metrics for number of services started is only showing legacy dynamic services

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3336]
only the metrics from director-v0 are fetched nothing about the new dy-sidecar-powered services.

**Comment by mrnicegyu11** [comment]
Any news here guys? @sanderegg @GitHK 

 The metric in question uses the following timeseries in its PromQL query: `simcore_simcore_service_director_services_started_total`
 
 This comes directly from simcore, namely the director (presumably v0) and webserver.
 
 So i guess this ticket requires changes in the backend, I would unassign myself for now and follow up once the exported metrics contain new dy-sidecar services ;) Let me know if this is alligned with your plans

**Comment by sanderegg** [comment]
@mrnicegyu11 no. 
following the discussion from yesterday with @elisabettai, if you can get the metrics without using this information it is not needed anymore. Let me know and then we can add these also from the director-v2.

**Comment by elisabettai** [comment]
Hi @sanderegg, would it be possible to get information (e.g. when services are started) for the new dynamic services? I was trying to play a bit in Graylog, but I don't actually know where to start from.

**Comment by sanderegg** [comment]
@elisabettai , @mrnicegyu11 was saying he had a method for getting them. Is that still current? otherwise I need to add the call in the dynamic sidecar. This should not take too long (maybe 1 day or we could even ask @GitHK to do it)

**Comment by GitHK** [comment]
> @elisabettai , @mrnicegyu11 was saying he had a method for getting them. Is that still current? otherwise I need to add the call in the dynamic sidecar. This should not take too long (maybe 1 day or we could even ask @GitHK to do it)

I can give a hand with this. Just let me know how it should work and where I can find something similar.

**Comment by sanderegg** [comment]
@GitHK : that would be in services/director/src/simcore_service_director/producer.py line 903 and 1145 for the legacy services.
I.E. it sends a message in the rabbit MQ for instrumentation. I think this might be all there is needed.

**Comment by sanderegg** [comment]
@mrnicegyu11 , well good that you tried... would have been nice

**Comment by GitHK** [comment]
@sanderegg so I would not wait to be sure that the service was started successfully? I have several points in time when I can execute this:
- sidecar creation
- user services creation
- containers are started and healthy

Which would be the correct one?

**Comment by sanderegg** [comment]
well, started means that it is started and healthy.

**Comment by sanderegg** [comment]
otherwise I don't think we can count it as started @GitHK

**Comment by elisabettai** [comment]
Thanks @GitHK for having a look to this and @sanderegg, @mrnicegyu11 for your input. @GitHK, let me know how it goes and when we can have a look to the data in master.

The metrics they would like to see is: "Average number of times per month a service on the o2S2PARC platform was run, up to the top 10 most popular services averaged over the quarter reported on".

As a sanity check, I'm having a look to what we have in Grafana in master. Do the values make sense? I see sleeper:2.0.2 being used ~26K times on average per month, which sounds a bit too high also considering e2e and p2e tests every hour and every day. Maybe I am still getting those values on the y-axis wrong.
![image](https://user-images.githubusercontent.com/18575092/197568680-9a2cf7a9-be6d-41d7-b766-e2072b7a09f0.png)

**Comment by mrnicegyu11** [comment]
@elisabettai Without doing the math explicitly I also find this high. But I guess this is a quantitative question so we need to check how many sleepers etc. are actually started per day by the e2e/p2e....

It might also be that the title of the graph is either wrong or selling the underlying PromQL query simpler than it is. Maybe consider explicitly checking the PromQL query if it tryly calculates the average number of times per month averaged over the quarter (it is unclear to me on first sight what that even means :D )

**Comment by sanderegg** [comment]
@elisabettai , @mrnicegyu11 
so a few things:
this graph shows 2 different sleeper 2.0.2 ? looks suspicious.
Also in theory:
e2e runs: 1/hour * (5 sleepers (serial test) + 5 sleepers (parallel test)) * 24h * 30days = 7200 runs per month
p2p runs: not running sleepers as far as I know

**Comment by mrnicegyu11** [comment]
Running the query in prometheus instead of grafana gives a more verbose picture, something seems a bit off. There are multiple "deployments" on master, I guess this is not as intended and needs investigation

![image](https://user-images.githubusercontent.com/8209087/197704920-ea86e3b0-e8e1-47e7-abf5-313f2aff9c2f.png)

**Comment by GitHK** [comment]
> otherwise I don't think we can count it as started @GitHK

@sanderegg We do count them as healthy for the older ones, If you look at the code. Nothing guarantees it started. That's why I'm asking this.

**Comment by sanderegg** [comment]
@GitHK , ok so then do it the same. a service started is started

**Comment by elisabettai** [comment]
Just looking with @sanderegg, there seems to be some problems (on AWS prod for the webserver started services, e.g. [this one](https://monitoring.osparc.io/prometheus/graph?g0.expr=sum(rate(simcore_simcore_service_webserver_services_started_total%7Bservice_key%3D~%22simcore%2Fservices%2Fcomp%2Fitis%2Fsleeper%22%7D%5B1d%5D)*1*24*60*60)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1w&g1.expr=sum(rate(simcore_simcore_service_director_services_started_total%7Bservice_key%3D%22simcore%2Fservices%2Fdynamic%2F3d-viewer-gpu%22%7D%5B1d%5D)*1*24*60*60)&g1.tab=0&g1.stacked=0&g1.show_exemplars=0&g1.range_input=8w&g2.expr=&g2.tab=1&g2.stacked=0&g2.show_exemplars=0&g2.range_input=1h))

**Comment by elisabettai** [comment]
@GitHK, any chance you can have a look to this soon-ish? We'd this for the report we need to finalize in two weeks.
