### ISSUE TITLE
When a dynamic service does not have enough resource it should wait in pending

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3340]
Dynamic services powered by dy-sidecar shall now again (as was originally the case) wait in pending when there is not enough resources forever unless:
- study is closed
- service is removed

If this behaviour was also changed for legacy services it should also be reverted.

This is a pre-requisite so that auto-scaling may kick in (and it may take a few minutes until resources are available)

**Comment by sanderegg** [comment]
@GitHK did you complete this issue? I saw something about a timeout being extended right?

**Comment by GitHK** [comment]
Yes, was fixed by https://github.com/ITISFoundation/osparc-simcore/pull/3388
