### ISSUE TITLE
Communication channel between GC service and sockets

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3387]
We need a way to sync communication between websockets. We know there is a embedded features in socketio that allows connecting to a message broker to do so... and seems the way to go.

A use case is e.g. enforce logout (i.e. socket channel disconnect) from a task in the GC service, which has no direct communication with the front-end!

NOTE: search fro this issue number in the code base to find contreat examples

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4286
```

**Comment by pcrespov** [comment]
Can use similar method as the one developed in #2410

**Comment by sanderegg** [comment]
@pcrespov what do you want to communicate exactly?
