### ISSUE TITLE
Investigate: why dy-sidecar is attached to the dy-sidecar_uuid network

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3390]
When a `dy-sidecar_UUID` is created it is also attached to the `dy-sidecar_UUID` network.
This allows for the containers inside to have access to the dy-sidecar's interface. Why is this required. Can it be removed?

- https://github.com/ITISFoundation/osparc-issues/issues/638

**Comment by GitHK** [comment]
@mrnicegyu11 you might be also interested in this one.

**Comment by mrnicegyu11** [comment]
Currently to the best of my knowledge this common volume is not needed. It might be in the future though.
