### ISSUE TITLE
dask-scheduler has high CPU usage after some running time

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3393]
When dask-scheduler reaches high CPU usage, the whole stack gets affected. This happens only a after the service is running for a few days. 

More details reported in https://git.speag.com/oSparc/e2e-testing/-/issues/5

The workaround is to restart the service. For the moment, we have done this manually, but we can create a cron job to do this automatically until this issue is resolved.

**Comment by sanderegg** [comment]
after upgrade of dask libraries this went away.
