### ISSUE TITLE
Porting of S4L Modeler to Linux

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#34]
**User story**

As a **developer** I want to be able to have a s4l modeler service running on a linux node in the simcore platform.

**Definition of Done**
- [x] Investigate license terms for ACIS on linux
- [x] Identify plugins and 3rd party libraries needed for modeling functionality
- [x] Refactor/Throw away platform dependent parts

**Use case**

Make current prototype for s4l modeling service part of a pure linux docker swarm

**Comment by oetiker** [comment]
related to #52
