### ISSUE TITLE
S3 TransferError while dy-sidecar uploads to S3 (400 - Bad Request)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#3402]
## Long story short
While closing a study, a dy-sidecar fails to upload to S3

## Actual behaviour
I see in the dy-sidecar logs this, while it tries to upload the output
`aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request'`. I'm attaching the full log. 
[_dy-sidecar_cb581308-75f6-497b-9509-4ae923b46e3a.1.iy4bbbfy6rfw092x3hdcvhpqh_logs.txt](https://github.com/ITISFoundation/osparc-simcore/files/9695953/_dy-sidecar_cb581308-75f6-497b-9509-4ae923b46e3a.1.iy4bbbfy6rfw092x3hdcvhpqh_logs.txt)

## How to reproduce
It is not easy to reproduce.
I got the error above 2 times today while closing a [study](https://staging.osparc.io/#/study/a94dc17c-3efc-11ed-96ce-02420a0b1f13) with lot of data.
In the jupyter-sim4life node I deleted (from the terminal) the file in one of the output ports. Then I closed the study and there was the error while saving. 

## Your environment
AWS staging

- https://github.com/ITISFoundation/osparc-issues/issues/638

**Comment by GitHK** [comment]
Ongoing investigation

**Comment by elisabettai** [comment]
It happened again on AWS staging, during an e2e test (still a jupyter-smash node). Here more logs. [_dy-sidecar_7b3e6f9a-bb0c-597e-8a64-e1c0e77c7a22.1.uvuoqjkj7bwjsaphe0frzstc1_logs.txt](https://github.com/ITISFoundation/osparc-simcore/files/9783607/_dy-sidecar_7b3e6f9a-bb0c-597e-8a64-e1c0e77c7a22.1.uvuoqjkj7bwjsaphe0frzstc1_logs.txt)

Sidecar was still there, so that can be pushed. It's a puppeteer study, so I didn't worry too much.

**Comment by elisabettai** [comment]
I've opened and closed a couple of times today a large study on dalco prod and haven't seen this 400 error anymore. Closing for now.
