### ISSUE TITLE
Zombie volume backed up

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3436]
running the following query in Graylog: ```"osparc-ops-dy-volumes-cleanup"```

- [10/13/2022 - 00:04 AND 00:01](https://monitoring.osparc.speag.com/graylog/search?q=%22osparc-ops-dy-volumes-cleanup%22&rangetype=absolute&from=2022-10-12T23%3A59%3A52.840Z&to=2022-10-13T00%3A00%3A16.230Z)

**Comment by sanderegg** [comment]
today 13 zombies:
- staging AWS 7
- production AWS 2
- dalco 4

**Comment by GitHK** [comment]
outdate, please open issue if something occurs relative to the agent
