### ISSUE TITLE
Pending sidecars never closing due to "Insufficient access rights to write workspace.zip"

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3493]
On `osparc.io`, see for example `graylog/messages/graylog_179/38a575c7-58a1-11ed-95cd-0242ac12000e`, or query graylog for `"Insufficient access rights to write"`.

There were more than 100 dy-sidecars pending and not closing, due to this error. Most of them are from e2e/p2e. It is unclear why this happens. One theory is that the project associated to the dy-sidecar is deleted by the puppeteer *before the study is closed*. On a brief check of graylog, we could not find `:close` calls in the webserver for the projects belonging to those pending dy-sidecars. Why this would happen is unclear. This needs an investigation. This has only been happening from the 27th of October onwards, which would be consistent with the last update of the director-v2 docker service on `2022-10-27 14:34:55` according to portainer.

CC @pcrespov @sanderegg

**Comment by GitHK** [comment]
This issue was addressed, there was na issue with computing when to save the state
