### ISSUE TITLE
list available running nodes to be stopped

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3522]
when the maximum amount of concurrent dy-services is reached, it would be desirable to have a dialog with a list of the running dy-services to choose which one to stop

**Comment by odeimaiz** [comment]
Not sure about this one. I would still force the user to stop the service while having the iframe visible in the screen

We could pop up a dialog for direct accessing those 5 five services.... but I don't find it so useful.

**Comment by sanderegg** [comment]
what I thought goes in the direction of:
- "you have too many running services, please choose among this list which one(s) to stop:" (then the list of the running services names)
- the user chooses one, this guy stops and then the new service can start

**Comment by odeimaiz** [comment]
Closing, we decided to make the user more aware of what will be closed by going to the service itself and stop it.
