### ISSUE TITLE
Deleting a project does not remove failed dy-sidecars

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3567]
Is there a way to clean up all abandoned zombie dy-sidecars with one easy command?

This just happened:
- Today at 10:33 ~40 dy-sidecars on dalco (likely only staging) failed to save their data to S3 (ceph)
- The projects they belong to cannot be found in the pg database, but are referenced in the logs. So the project(s) were likely deleted
- Looking through the logs, I see many of these dy-sidecars are from e2e or p2e tests (Filename `TheNumber.txt` and such)
- Now, we might not care about these failed e2e test uploads, but we surely need to check that there are not 40 dy-sidecars now on dalco clogging the machines

Any ideas how to best tackle this? @GitHK  ?

The specific error was `[simcore_sdk.node_ports_common.file_io_utils:logged_gather(122)]  -  Error in 1-th concurrent task <coroutine object _upload_file_part at 0x7f1b6044a240>: Cannot connect to host ceph-prod-rgw.speag.com:443 ssl:default [Temporary failure in name resolution]` [ https://monitoring.osparc.speag.com/graylog/messages/graylog_195/cb41a5a8-64c7-11ed-b190-0242ac130011 ]

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/ok3y4s1m6bbnf8kwu3jemijt4h) *by @mrnicegyu11*._

There might also be a subtle simcore-webserver bug hidden, when reading the logs relating to one of the deleted projects I see the following error in the webserver
```
[0;31mERROR[0m: [2022-11-15 09:28:23,775/MainProcess] [simcore_service_webserver.projects.projects_api:lock_with_notification(1055)]  -  Project [project_uuid='70940bf2-64c7-11ed-b2a1-02420a0b000d'] already locked in state 'prj_states.locked.status='CLOSING''. Please check with support.
```
[ https://monitoring.osparc.speag.com/graylog/messages/graylog_195/da2bb381-64c7-11ed-b190-0242ac130011 ]

I think `projects_api:lock_with_notification` should not be called on an object that is already locked, something probably went wrong there.

This might have to be followed up.

[ in case you want to check yourself https://monitoring.osparc.speag.com/graylog/search?q=%2270940bf2-64c7-11ed-b2a1-02420a0b000d%22&rangetype=relative&from=18000 ]

good info! thx

**Comment by sanderegg** [comment]
- so the original issue was "Temporary failure in name resolution" which would indicate that CEPH was not available??
- after that I guess the dynamic sidecar is in a locked state
- after that the webserver tries to delete the study (@neagu what happens when someone tries to delete a study with failed dy-sidecars?) - this is done at the end of each e2e/p2p test to prevent cluttering storage --> CLOSING state
- after that I would guess that the garbage collector tries as well to delete the study and finds it already in CLOSING state and you get the lock issue (and probably tries again every GC interval)

**Comment by sanderegg** [comment]
@GitHK said
Let's see a few things:
- If a dy-sidecar fails to save. It will stay there and await manual intervention. 
- If the project has a failed sidecar still running and you delete it the project should get deleted. The sidecar will still await manual intervention.
Also please note:
- if a node is deleted it is no longer possible to save it. (errors in accessing the DB will happen due to nodeports checks)
- the dy-sidecar should be informed when a node was deleted and it needs to take into consideration when shutting down

**Comment by sanderegg** [comment]
- Deleting a project means the user does not care about the data --> it is safe to remove the failed nodes
- deleting a project should not remove the databases **before** the services are gone

**Comment by GitHK** [comment]
@sanderegg an approach to solve this issue could be the following:
- query the projects table and check if project is present
- if project is present, check if node is present in workbench

If node or project are not present, do not save the data the service.

This will for sure avoid current issues that we are having with services and projects which are getting deleted.
