### ISSUE TITLE
Flaky tests/public-api/test_solvers_jobs_api.py::test_run_job[FAILED]

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3569]
FAILED tests/public-api/test_solvers_jobs_api.py::test_run_job[FAILED] - osparc.exceptions.ApiException: (404)

[example](https://github.com/ITISFoundation/osparc-simcore/actions/runs/3477365541/jobs/5813586054#step:11:36)

**Comment by pcrespov** [comment]
Client seems to be sending `` GET /v0/solvers/simcore/*/jobs/*/outputs/**None**``!!
```
[uvicorn.access:send(440)]  -  10.0.0.2:40864 - "GET /v0/solvers/simcore/services/comp/itis/sleeper/releases/2.1.1/jobs/0d363446-23bd-4ce0-915b-ea17cf593bfc/outputs/logfile HTTP/1.1" 307
2022-11-16T08:05:19.500993154Z INFO: [2022-11-16 08:05:19,500/MainProcess] [uvicorn.access:send(440)]  -  10.0.0.2:40864 - "GET /v0/solvers/simcore/services/comp/itis/sleeper/releases/2.1.1/jobs/0d363446-23bd-4ce0-915b-ea17cf593bfc/outputs/None HTTP/1.1" 404
```

**Comment by pcrespov** [comment]
It still happens even after repetitions... i

**Comment by GitHK** [comment]
latest run with this issue
https://github.com/ITISFoundation/osparc-simcore/actions/runs/4890752382/jobs/8730721666?pr=4195

**Comment by pcrespov** [comment]
- docker logs dump also fails: `Unexpected failure while dumping <Container: 59e896e35a8e>.Details 501 Server Error for http+docker://localhost/v1.41/containers/59e896e35a8e75b1cd4a5e6baabdca46f5f8581594936ad05399fbf61cf5075d/logs?stderr=1&stdout=1&timestamps=1&follow=0&tail=1000: Not Implemented ("configured logging driver does not support reading")`
