### ISSUE TITLE
Agent: prune stopped user-services

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3570]
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/c65bff9c-54bd-40f5-ba70-4681a083bd6c)

as you can see, it is stopped
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/15a4679d-400a-4a27-8e9a-b31425de74bb)

The agent might prune this and then log the cause by inspecting the containers and extracting fore instance
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/c9d54321-39aa-4532-aa3d-39cba241f85c)

**Comment by GitHK** [comment]
no longer applies, agent will not do this. This was a side effect of an issue where the dy-sidecar would not log the result of a failed operation and ignored it as nothing happened.
