### ISSUE TITLE
Dynamic sidecar ```POST /containers:down``` entrypoint raises RunimeError if no services were started

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3578]
following [https://git.speag.com/oSparc/e2e-testing/-/issues/9](https://git.speag.com/oSparc/e2e-testing/-/issues/9):

some dynamic sidecars are started and then closed
On closing the study the dynamic sidecar is asked to shutdown the user services.

instead of returning a standard response it raises a ```RuntimeError``` which then triggers a whole lot of issues.
Since nothing was started, it does not make sense to trigger an error on close.

Therefore the ```POST /containers:down``` entrypoint shall be modified accordingly and not raise any error when no service was started. It can maybe issue a warning in the logs but nothing more.

**Comment by GitHK** [comment]
NOTE: also check the delete endpoint, it might delete the entry in the db before stopping the service

**Comment by GitHK** [comment]
NOTE: check how the delete behaves and address accordingly
