### ISSUE TITLE
Live stats on cpu/ram usage per service

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#3585]
**USER STORY:**

As a user, I want to know how much resources my service is consuming in real-time. This will allow my to ask (pay) for more resources.

**Notes**

- frontend could show that as a overlay view if service is in full-screen mode
- could also be added as part of the "node" in the workbench
- information can be obtained via `docker stats` and thrown out to the frontend via the rabbit.

**Comment by odeimaiz** [comment]
Implemented
