### ISSUE TITLE
E2E: complete implementation of test to check if all dy-sidecar created services were properly removed after testing

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3588]
The webserver knows when the CI is the one calling into the system.
It should make sure that any created docker component also receives the label

Therefore one could:
- E2E have a test that checks that all services/volumes are properly cleaned up by listing anything with the proper label
- auto clean script

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/6xe17kiysf8dbqutdzk8dg1jie) *by @sanderegg*._

*Added @mrnicegyu11 sprint planning 02Mar2023*:
Also expose the product (such as tip, s4l) to the user services' container labels, please.

**Comment by sanderegg** [comment]
```bash
pip install httpie

# this will get all the containers with label set as user_id
http GET https://monitoring.osparc-master.speag.com/portainer/api/endpoints/2/docker/containers/json Authorization:"Bearer BEARER_CODE" limit==1 filters=='{"label":["user_id=${PUPPET_USER_ID}"]}'
```

**Comment by sanderegg** [comment]
```bash
# same for services
http GET https://monitoring.osparc-master.speag.com/portainer/api/endpoints/2/docker/services Authorization:"Bearer BEARER_CODE" limit==1 filters=='{"label":["user_id=5"]}'
```

**Comment by sanderegg** [comment]
this is now done for dynamic sidecars and we could finish this test

**Comment by pcrespov** [comment]
@sanderegg this is related, right?
>Dear all , I have finally taken the time to complete the e2e test named ```check_all_puppeteer_services_gone``` by making the script fail when it finds containers owned by the puppeteer that should not be around. It works by leveraging the portainer API and asking for any container where the ```simcore_user_agent=puppeteer```.
This will still need some fine tuning, because it is now not able to differentiate between the different branches. I will check tomorrow with @maiz to see how this might go
