### ISSUE TITLE
Frontend Design/Theming

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#36]

**Comment by pcrespov** [comment]
- [ ] target first widgets in UIs of current prototypes
- [ ] official repo under itisfoundation. manifest adds repo as contribution to qx
- [ ]

**Comment by drniiken** [comment]
* theming
* progress
* check case, widgets
* browser running, check and work on it ourselves

**Comment by oetiker** [comment]
Some extra work on the viewer might be vtkweb viewer would help it integrate properly ... fix fonts and color of panel

**Comment by oetiker** [comment]
new release of material font icons to provide tree icons https://github.com/ITISFoundation/qx-iconfont-material/releases/tag/v0.1.0

**Comment by oetiker** [comment]
new release of osparc theme with tree styling https://github.com/ITISFoundation/qx-osparc-theme/releases/tag/v0.1.0

**Comment by pcrespov** [comment]
very stylish indeed :)
