### ISSUE TITLE
Dy-sidecar: A service with pending resources that gets removed does not get removed 

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3604]
While testing with autoscaling the following issue popped up:

- start a dynamic sidecar with constraints that cannot be fulfilled (such as label or resources)
- it goes into Pending --> that is correct
- now removing the node does not remove the service, it stays there

**Comment by GitHK** [comment]
this was fixed by https://github.com/ITISFoundation/osparc-simcore/pull/3833
