### ISSUE TITLE
Autoscaling: handle down scaling cluster

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3627]
- [ ] detect when a node is not in use anymore, or shall not be used anymore
- [ ] send a signal over RabbitMQ  that a node is about to be closed to allow some other service (such as the agent) to ask for more time for doing whatever it needs to do (@GitHK the agent will need to react to that I guess)
- [ ] if there is no one asking for more time, terminate the node

**Comment by GitHK** [comment]
@sanderegg I also would like some form of communication via RabbitMQ to target specific nodes.
I guess you would like to have some sort of messages back from the target agent node like (`message received` and `messaged processed`).
This will allow you to figure out if the processing has finished.

**Comment by sanderegg** [comment]
completed by #3655
