### ISSUE TITLE
Autoscaling: Starting sim4life on a freshly started node fails

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3746]
When opening a sim4life instance that triggers the creation of a new computer in AWS, sim4life starts and shows the Ready flag in osparc GUI.

Opening sim4life:
- is slow to start (not always), progress on splash screen?
- eventually shows the sim4life GUI, but shows that the application is busy and never comes out of it

Closing sim4life completely and re-starting it then works, and none of the issues above are visible

**Comment by sanderegg** [comment]
version 2.0.82 now manages to start.
But we still have something that goes slow on the freshly started machine.
@mrnicegyu11 we will need to analyse the syslog to check if we can identify something.

**Comment by sanderegg** [comment]
New test with AMI using [Amazon EBS fast snapshot restore](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html).

process:
1. removed all autoscaled nodes
2. started jupyer-math:2.08 to trigger autoscaling
3. started iseg:1.0.11 to measure timings on node already present
4. started s4l-life:2.0.88 to measure timings on node already present

## general observations
- error in docker still present in syslogs
```bash
journalctl -xb -r | grep level=error
Jan 24 19:35:44 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:35:44.951354395Z" level=error msg="attach failed with error: error attaching stdout stream: write unix /var/run/docker.sock->@: write: broken pipe"
Jan 24 19:35:40 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:35:40.313303007Z" level=error msg="Bulk sync to node 3799f40e0aec timed out"
Jan 24 19:35:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:35:10.326271063Z" level=error msg="Bulk sync to node 3799f40e0aec timed out"
Jan 24 19:35:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:35:10.314672586Z" level=error msg="Bulk sync to node 7808f9bdb601 timed out"
Jan 24 19:35:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:35:10.309334889Z" level=error msg="Bulk sync to node 7808f9bdb601 timed out"
Jan 24 19:34:40 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:40.323027502Z" level=error msg="Bulk sync to node 7808f9bdb601 timed out"
Jan 24 19:34:40 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:40.315525608Z" level=error msg="Bulk sync to node 1a7583b7a676 timed out"
Jan 24 19:34:40 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:40.311625866Z" level=error msg="Bulk sync to node 1a7583b7a676 timed out"
Jan 24 19:34:40 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:40.306655471Z" level=error msg="Bulk sync to node 1a7583b7a676 timed out"
Jan 24 19:34:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:10.425415456Z" level=error msg="error reading the kernel parameter net.ipv4.vs.expire_quiescent_template" error="open /proc/sys/net/ipv4/vs/expire_quiescent_template: no such file or directory"
Jan 24 19:34:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:10.425399879Z" level=error msg="error reading the kernel parameter net.ipv4.vs.expire_nodest_conn" error="open /proc/sys/net/ipv4/vs/expire_nodest_conn: no such file or directory"
Jan 24 19:34:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:10.425362838Z" level=error msg="error reading the kernel parameter net.ipv4.vs.conn_reuse_mode" error="open /proc/sys/net/ipv4/vs/conn_reuse_mode: no such file or directory"
Jan 24 19:34:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:10.206925502Z" level=error msg="error reading the kernel parameter net.ipv4.vs.conn_reuse_mode" error="open /proc/sys/net/ipv4/vs/conn_reuse_mode: no such file or directory"
Jan 24 19:34:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:10.206909527Z" level=error msg="error reading the kernel parameter net.ipv4.vs.expire_quiescent_template" error="open /proc/sys/net/ipv4/vs/expire_quiescent_template: no such file or directory"
Jan 24 19:34:10 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:34:10.206863603Z" level=error msg="error reading the kernel parameter net.ipv4.vs.expire_nodest_conn" error="open /proc/sys/net/ipv4/vs/expire_nodest_conn: no such file or directory"
Jan 24 19:33:36 ip-10-0-3-131 dockerd[1069]: time="2023-01-24T19:33:36Z" level=error msg="2023/01/24 19:33:36 INFO  : Serving unix socket: /run/docker/plugins/rclone.sock" plugin=cb1a9fffc96b296a0ae6b3ffb11c344cc5b849aabb04fbaaee05d382a2353491
Jan 24 19:33:10 ip-10-0-3-131 containerd[749]: time="2023-01-24T19:33:10.863693951Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
```

## jupyter-math:2.0.8
- dy-sidecar service created time: ```2023-01-24T19:31:46.635346848Z```
- syslog "join swarm message": ```2023-01-24T19:33:59```
- dy-sidecar container created time: ```2023-01-24T19:34:11.469953232Z```
- syslog "user startup finished": ```2023-01-24T19:34:17```
- jupyter-math container created time: ```2023-01-24T19:35:23.651737719Z```
- jupyter-math container ready: ```2023-01-24 19:36:17.590```
time to get computer: ```00:02:25```, 
time to start jupyter-math from computer: ```00:02:06```

**Comment by sanderegg** [comment]
New test with AMI using [Amazon EBS fast snapshot restore](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html).

process:

removed all autoscaled nodes
started s4l-life:2.0.88 to measure timings on node already present
started jupyer-math:2.08 to trigger autoscaling
started iseg:1.0.11 to measure timings on node already present

## General
- machine launch time: ```2023-01-24T20:22:26+00:00```
- docker join swarm (syslogs): ```Jan 24 20:24:27```
- dy-sidecar container created time: ```2023-01-24T20:24:35.99953561Z```
- sym-server-dy container created time: ```2023-01-24T20:26:20.841135132Z```
- sym-server-dy container happy time: ```2023-01-24T20:26:41.631216788Z```
- s4l-core-lite container created time: ```2023-01-24T20:26:20.843836212Z```
- s4l-core-lite container happy time (all good message): ```2023-01-24T20:29:26.995400660Z```
- sim4life-lite container created time: ```2023-01-24T20:26:22.284842779Z```
- sim4life-lite container happy time: ```2023-01-24T20:29:42.085603697Z```

**Comment by sanderegg** [comment]
New test with AMI using [https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html) on both volume snapshots

process:
removed all autoscaled nodes, paused e2e
started sim4life:2.0.8
start a second instance

## observations
### first instance (cold start)
- machine launch time: ```2023-01-25T20:44:46+00:00```
- machine startup time (syslogs): ```Jan 25 20:45:15```
- **docker join swarm (syslogs): ```Jan 25 20:45:46```**
- dy-sidecar service created time: ```2023-01-25T20:44:40.585377706Z```
- dy-sidecar container created time: ```2023-01-25T20:45:55.01951951Z```
- sym-server-dy container created time: ```2023-01-25T20:47:08.338100141Z```
- sym-server-dy container first log time: ```2023-01-25T20:47:13.796629361Z```
- sym-server-dy container happy time: ```2023-01-25T20:47:29.010045029Z```
- s4l-core-lite container created time: ```2023-01-25T20:47:08.342387596Z```
- s4l-core-lite container first log time: ```2023-01-25T20:47:50.093321896Z```
- s4l-core-lite container happy time (last all good message? @colinRawlings @mguidon ?): ```2023-01-25T20:50:14.300932807Z```
- sim4life-lite container created time: ```2023-01-25T20:47:09.675721781Z```
- sim4life-lite container first log time: ```2023-01-25T20:47:50.773522145Z```
- sim4life-lite container happy time: ```2023-01-25T20:47:58.561793785Z```
- sim4life-lite then shows a bunch of unhappy socket.io connections: ```2023-01-25T20:48:00.765418157Z```
- until ```2023-01-25T20:50:22.260101197Z```


### second instance (warm start) - impressions: very fast
- dy-sidecar service created time: ```2023-01-25T21:08:31.834311143Z```
- dy-sidecar container created time: ```2023-01-25T21:08:35.029800938Z```
- sym-server-dy container created time: ```2023-01-25T21:08:47.019512102Z```
- sym-server-dy container first log time: ```2023-01-25T21:08:49.586942484Z```
- sym-server-dy container happy time: ```2023-01-25T21:08:54.717017167Z```
- s4l-core-lite container created time: ```2023-01-25T21:08:47.022810228Z```
- s4l-core-lite container first log time: ```2023-01-25T21:08:49.689225186Z```
- s4l-core-lite container happy time (last all good message? @colinRawlings @mguidon ?): ```2023-01-25T21:08:58.694373258Z```
- sim4life-lite container created time: ```2023-01-25T21:08:47.180473357Z```
- sim4life-lite container first log time: ```2023-01-25T21:08:51.244556853Z```
- sim4life-lite container happy time: ```2023-01-25T21:09:02.348656180Z```




## conclusions
### cold start
- machine joining the swarm in ~30 seconds instead of 2 minutes when only /docker is in fast restore mode
- sim4life takes 5min40s from service launch time (includes autoscaling time to react, potential here to spare up to 30seconds due to autoscaling task), 
- when dy-sidecar is created until sim4life is ready takes 4min27
- we still see issues with socket.io connections
- issues with table not found visible

### warm start
- sim4life ready to use in 31 seconds from service launch time
- issues with table not found visible


### next steps
- director-v2 seems to not wait for all containers to be ready before telling the frontend that it is in a running state, which could disrupt something a bit @GitHK 
-

**Comment by mguidon** [comment]
So the good news is that there was no problem with the volumes. Did you by any chance try to save the preferences as discussed in #3804 ?
What changed between your test and mine in the last 3 hours?

**Comment by sanderegg** [comment]
@mguidon hmm I think there is still the issue of the volume, is that not the problem with the ```ERROR    | no such table: settings``` ? sorry will write it down more clearly. this still happens

**Comment by sanderegg** [comment]
The EBS fast restore works like so:
fill rate per hours: MIN (10, (1024 ÷ snapshot_size_gib))
max credits in bucket: MAX (1, MIN (10, (1024 ÷ snapshot_size_gib)))
so for one volume we can have a maximum of 10 credits. each machine that starts uses 1 credit.

--> a maximum of 10 machines per hour can get the full speed 3000IOPS provided the fill rate gets to be 10.

We decided to toss away this idea. @Surfict will look whether there are other options.
