### ISSUE TITLE
Flaky tests/unit/test_api_containers.py::test_containers_entrypoint_name_containers_not_started

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3764]
Check [this CI log](https://github.com/ITISFoundation/osparc-simcore/actions/runs/3930429982/jobs/6720448511#step:9:386) as example

**Comment by sanderegg** [comment]
still flaky?

**Comment by GitHK** [comment]
Very good question. I'm not sure if I've seen it as flaky lately

**Comment by GitHK** [comment]
@sanderegg @GitHK @matusdrobuliak66 reports for this one?

**Comment by sanderegg** [comment]
not from me. but I will not close this one

**Comment by pcrespov** [comment]
Again https://github.com/ITISFoundation/osparc-simcore/actions/runs/6315870051/job/17149324609#step:8:556

**Comment by sanderegg** [comment]
stale closed now
