### ISSUE TITLE
Should ``get_running_services`` return services w/o containers?

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3783]
After some debugging with @sanderegg we noticed that the problem was that two services associated to @elisabettai were failing the validation above because all associated containers failed. The service exists but has no container therefore the ``service_port == None`` and therefore the validator ``RunningDynamicServiceDetails`` failed.

**This issue needs a follow up**: @GitHK we need to determine what is expected from ``get_running_services`` since a service can still exists without any running container.

SEE https://github.com/ITISFoundation/osparc-simcore/blob/308fa08e60693836e1ce225e53b535c95bd95384/services/director-v2/src/simcore_service_director_v2/modules/director_v0.py#L145-L164

@GitHK please let me know when you have a moment to check this issue.

_Originally posted by @pcrespov in https://github.com/ITISFoundation/osparc-issues/issues/835#issuecomment-1397007589_

**Comment by pcrespov** [comment]
@sanderegg  wrote steps to reproduce:
- 2 failed legacy services (they were visible in portainer)
- when starting a study or a service, we start by listing all your running services (both legacy and dy-sidecar) [director_v0.py](https://github.com/ITISFoundation/osparc-simcore/blob/308fa08e60693836e1ce225e53b535c95bd95384/services/director-v2/src/simcore_service_director_v2/modules/director_v0.py)
- during the listing of the legacy services, it returned 2 that were broken that had no port open and therefore correctly set to ```None``` (since they were failed... that makes sense)
- validating these returned services failed... ```RunningDynamicServiceDetails``` failed validating because it does not accept ```service_port = None```

**Comment by elisabettai** [comment]
For me all started with a legacy dynamic service `tvb`.

Another potential issue I noticed while looking in Portainer what was happening to `tvb`, is that the `tvb-app` part of the service was pending (waiting for resources it seemed), while the `tvb-web` part failed (and thus the user sees the service failing). Should we have a separate issue for this @pcrespov?

Another issue highlighted by @sanderegg, is that those legacy service never got removed.

**Comment by GitHK** [comment]
@pcrespov just saw this one now.
Had a look into the code `get_running_services` returns all `services`. This should be named to something like `get_services` (since it only lists all the services that it finds in swarm, it does not care about their state).

**Comment by GitHK** [comment]
@elisabettai @pcrespov If you are running a non legacy service, I've recently made it so it fails when one of the containers fails to boot. Could you please check and let know if this is (still) the case?

**Comment by pcrespov** [comment]
this is difficult to reproduce now. @elisabettai do you remember this? otherwise let's close it

**Comment by GitHK** [comment]
closing the issue, no replies
