### ISSUE TITLE
SIM - MAP-CORE ToDos

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#38]
**STORY PART I**

**Communication**

According to meeting minutes of our last meeting:
 - [x] send tissue list of NEUROCOUPLE to Peter
 - [x] setup of meeting with them to discuss technical aspects (mapping, ontologies, API, metadata, etc.)

**STORY PART II**

**Import simulation data provided by MAP-CORE and visualize**

**User story**

As a user I want tor import simulation data provided by MAP-CORE into the SIM-CORE platform. I want to visualize them.

**Definition of done**

- [x] Analyze data types and visualizers required
- [x] Define where and how in the UI this should happen

**Use case**

We have to contact them in order to find examples.

**Comment by drniiken** [comment]
![screen shot 2018-04-09 at 18 23 24](https://user-images.githubusercontent.com/32800795/38509881-7bd5df58-3c23-11e8-9c5f-6a024c53f0fc.png)

**Comment by drniiken** [comment]
* talked with Peter Hunter & David Nickerson in DC
* webex scheduled for Monday May 7
* will discuss possible integration/mapping between full body models and organ scaffolds

**Comment by mguidon** [comment]
@dyollb @odeimaiz This is the issue I mentioned over coffee. I tagged it D5.2.
@dyollb @esraneufeld  Do you guys have an overview of what type of data/visualizers we need here? Can we create a new issue where we pick one, two or forty-two target for implementation?
