### ISSUE TITLE
Autoscaling: Filesystem issues for sim4life

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#3804]
There is a problem with the filesystem in the docker containers created on a fresh ec2-instance for sim4life. I think it only happens for the first running instance on the node but I am not sure anymore (This needs to be confirmed). The problems surfaces in various cirucmstances:
1. when sim4life starts, it creates a File in `work/workspace/Materials`. I think this happens by copying from the root filesystem into the work volume. This file has zero size and when sim4life wants to read it, it fails. The error message is as follows (the 2 database errors):

![image](https://user-images.githubusercontent.com/33161876/214614161-56921aa1-aef2-4613-95ae-d922e713c5c9.png)

2. When you open the Preferences dialog(via the burger) and close it, we try to save the preferences by first creating a file in the `/tmp` folder (e.g. the root partition) and then moving it to `work/workspace/Preferences/Preferences.h5`

![image (1)](https://user-images.githubusercontent.com/33161876/214615128-f184ec1b-7062-4df8-8c39-d657a2231d72.png)

3. And lastly, when we auto save a file (after about 5 minutes), the same problem manifests: I think we try to save the file by first creating a temporary one too.

Sometimes, I see error messages like `invalid cross device link` next to above errors. This usually means that a file move operation cannot be done because target and destination are not on the same partition or different harddrives. I have seen this problem before with other servcies aws prod. In that case, reprovisioning the machine fixed the problem. (The root filesystem and all the other mounts in the container do sit on the same partition physically, thats why this cannot be the actual problem).

Last time, there was a weird issue with the kernel on the AMI. (@Surfict, maybe you remember). My guess is, that there is some sort of mismatch between kernel version, docker daemon and the timing of when the filesystem becomes available. We could try to use only one drive on the autoscaling nodes if that makes the debugging simpler.

**Comment by mguidon** [comment]
@Surfict I just tested again on staging with version 88. It behaves exactly as described above. First instance sad, second instance happy.

**Comment by sanderegg** [comment]
Some testing showed the following:
on staging AWS with a s4l-lite:2.088 that showed the issue on start the following was discovered and could help narrowing down the issue.

Entering the s4l-core-lite container and going to /work/workspace/Preferences and executing
```bash
rm *.h5
```
then saving the preferences in s4l-lite GUI works.

Doing it again fails again and the files are corrupted (0 size or invalid h5 file).

This is very reproducible. More debug messages would help to find the real issue. this will be taken care of by @mguidon

**Comment by sanderegg** [comment]
issue fixed in sim4life
