### ISSUE TITLE
Change of env variable in webserver

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#3827]
Hi dear devops,
could you please change the env variable `STORAGE_DEFAULT_PRESIGNED_LINK_EXPIRATION_SECONDS` to `43200` in all deployments?

It would be great to have it in staging before tomorrow.
There's a bit more explanation [here](https://github.com/ITISFoundation/osparc-simcore/issues/3217#issuecomment-1411712491).

I've changed it manually already in dalco-staging for a test.

Merci vielemals!

**Comment by mrnicegyu11** [comment]
@sanderegg can you comment if this will be fine and if it can be done on the fly?

**Comment by sanderegg** [comment]
@mrnicegyu11 
for master/staging deploys no problem
for prod I think you are doing a maintenance today right? otherwise I think this is low danger since there are multiple webservers.

**Comment by mrnicegyu11** [comment]
ok thanks, I will add this to the maintenance todos
