### ISSUE TITLE
Unexpected SIGTERM to dy-sidecar and dy-proxy pair

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3832]
It was observed that on autoscaled nodes, `dy-sidecar` and `dy-proxy` pair,  sometimes get a `SIGTERM` out of the blue.

I am sure this is not initiated by the director-v2 since it would first try to save the state, push the outputs, before trying to remove both services.

For reference have a look at logs from `67fa84ec-5a78-49b8-8aca-0ce179d84021` AWS prod. It can clearly be seen that the sidecar and proxy receive a SIGERM and shut down.

**Comment by GitHK** [comment]
This was also observed again on a node with 3 dy-services running on them. All 3 pairs of `dy-sidecar` and `dy-proxy` received the SIGTERM at the same time.

The obvious culprit would be autoscaling draining the node too early.

**Comment by sanderegg** [comment]
@GitHK could you please add the command I should use in Graylog to find these cases? thanks.

**Comment by GitHK** [comment]
Related to this case. Currently on AWS staging unexpected behaviour. Containers are in an orphaned state. If we look at the details in the screenshots it's stated that the task belongs to a node which was deleted.

Unfortunately the longs are partial. If you filter by `container_name: /.05827b71-86b1-48b4-9f5a-8ee5c4d545e8./` the only thing I see is that the sidecar was trying to shut down, but I don't see a lot of logs related to starting so I don't think these are that helpful.

@matusdrobuliak66 was also involved in this investigation.


![Image](https://user-images.githubusercontent.com/5694077/232690363-e400230c-6fea-497b-9aba-3298a9c473d3.png)

![Image](https://user-images.githubusercontent.com/5694077/232690374-9aff6e6f-d101-40ba-b9c0-5874798efc8b.png)

![Image](https://user-images.githubusercontent.com/5694077/232690387-36a8685d-b2aa-4383-9401-7c147df6a79b.png)

**Comment by matusdrobuliak66** [comment]
> Related to this case. Currently on AWS staging unexpected behaviour. Containers are in an orphaned state. If we look at the details in the screenshots it's stated that the task belongs to a node which was deleted.
> 
> Unfortunately the longs are partial. If you filter by `container_name: /.05827b71-86b1-48b4-9f5a-8ee5c4d545e8./` the only thing I see is that the sidecar was trying to shut down, but I don't see a lot of logs related to starting so I don't think these are that helpful.
> 
> @matusdrobuliak66 was also involved in this investigation.
> 
> ![Image](https://user-images.githubusercontent.com/5694077/232690363-e400230c-6fea-497b-9aba-3298a9c473d3.png)
> 
> ![Image](https://user-images.githubusercontent.com/5694077/232690374-9aff6e6f-d101-40ba-b9c0-5874798efc8b.png)
> 
> ![Image](https://user-images.githubusercontent.com/5694077/232690387-36a8685d-b2aa-4383-9401-7c147df6a79b.png)

Just not to forget, on 17.4. somewhere around that time we also turned off the autoscaling e2e tests (therefore this might be an outlier):
![image](https://user-images.githubusercontent.com/60785969/232693452-397df96e-5912-442c-9fb6-090422ee9c1f.png)

**Comment by sanderegg** [comment]
These services were manually deleted. @GitHK as I already asked. do you have a link to such an error?
If not I will unassign/close the case.

**Comment by GitHK** [comment]
We have been monitoring the staging deployment and there was not even a single incident regarding sidecars the last week. Let alone with autoscaled node. I'd say we can close the case for now.

**Comment by sanderegg** [comment]
Ok then I close it.
