### ISSUE TITLE
Improve user logout

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#384]
* FrontEnd: 
  - refresh or reload or close browser should trigger a window querying user whether she wants to logout.
  - if browser is closed from a different tab, then send a logout signal to server

* Server
 - kills all running dyb services upon user logout
 - timeout for user logout? (optional)

**Comment by ignapas** [comment]
The described frontend behavior is not the most appropriate. The user should stay logged in if he closes the browser.

**Comment by pcrespov** [comment]
@ignapas Please update the description then ... and the status. Thx :-)
