### ISSUE TITLE
Dask sidecar module not found in directror-v2

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3852]
The attached logs come from the director-v2

Something regarding the python runner and a strage issue about a module not being found when deserialising pickled data.

[dask_sidecar_missing_dv2.log](https://github.com/ITISFoundation/osparc-simcore/files/10685122/dask_sidecar_missing_dv2.log)

**Comment by sanderegg** [comment]
the error is pickled back to the director-v2 dask client. since the director-v2 does not include the dask-sidecar it does not show up.

**Comment by sanderegg** [comment]
fixed by https://github.com/ITISFoundation/osparc-simcore/pull/4133
