### ISSUE TITLE
Possible memory leak in storage when copying

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3891]
As discovered it seems the memory usage of the storage service might be leaking.

It could be identified as linked to copying process which uses aioboto3 copy function.

Investigation needed:
- create a test or enhance the test for copying and check the memory usage
- maybe the copy parameters need to be modified

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/bjsdwq3nkpnjjqhw5mrwjkqtgr) *by @mrnicegyu11*._

**Comment by sanderegg** [comment]
https://monitoring.osparc.io/prometheus/graph?g0.expr=container_memory_usage_bytes%7Bname%3D~%22.*simcore.*storage.*%22%7D-container_memory_cache%7Bname%3D~%22.*simcore.*%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1d

![image](https://user-images.githubusercontent.com/35365065/219582574-5c8f4185-7571-4717-b811-ca46ba718acb.png)

**Comment by mrnicegyu11** [comment]
Storage now takes 7.5 Gb on aws-prod:
![image](https://user-images.githubusercontent.com/8209087/221584069-1c73a2fa-9c06-4fa5-bde5-f207cb61f6d1.png)

**Comment by sanderegg** [comment]
From today, storage seems to go up in memory by steps. It is actually still not quite clear where the memory accumulates. I will need some more testing to resolve this, and find a way to reproduce locally. 

![Image](https://user-images.githubusercontent.com/35365065/228151394-0da08b6b-06e6-441a-8a7a-2ef550dda6ea.png)

**Comment by sanderegg** [comment]
Also it seems that this problem is affecting AWS prod only.

**Comment by sanderegg** [comment]
the latest graphs from [grafana](https://monitoring.osparc.io/prometheus/graph?g0.expr=container_memory_usage_bytes%7Bname%3D~%22.*simcore.*storage.*%22%7D-container_memory_cache%7Bname%3D~%22.*simcore.*%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=4w) look good. closing this case
