### ISSUE TITLE
e2e does not really wait for studies to be unlocked

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3899]
When done with the study, the e2e assumes that after 5 seconds it will be unlocked. It does not check the status of the card.

Afterwards the e2e delets the study and it succeeds. This is an issue (https://github.com/ITISFoundation/osparc-simcore/issues/3898). The test passes.

On the backend side, the sidecar is still trying to save the state and fails with `Insufficient access rights to write`

### Reference logs

Artifacts https://git.speag.com/oSparc/e2e-testing/-/jobs/2603016
Logs form sidecar: 
[_dy-sidecar_857aa40c-b5b8-5e07-aa5d-fb3a44b6023d.1.nt86cemvxi3gibb7ovwocswqp_logs.log](https://github.com/ITISFoundation/osparc-simcore/files/10791542/_dy-sidecar_857aa40c-b5b8-5e07-aa5d-fb3a44b6023d.1.nt86cemvxi3gibb7ovwocswqp_logs.log)

**Comment by odeimaiz** [comment]
Discussed with @GitHK, the e2e test does check the status.

**Comment by GitHK** [comment]
Closing this.
