### ISSUE TITLE
Filter out puppetteers in services usage metrics

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#3908]
It would be nice to have a way to filter out dynamic and computational services starter by the puppeteer.

For now the only way is to subtract those values manually, as explained [here](https://git.speag.com/oSparc/osparc-metrics/-/blob/master/FilterPuppets.md).
Doing it manually gives a rough estimate and we need also to take into account when new e2e tests are introduced, which will probably become even more frequent with the upcoming product releases.

**Comment by sanderegg** [comment]
@GitHK there was an entry where you added the user agent. How can I see that entry in prometheus ? (also @mrnicegyu11 shall know that and could add a link to prometheus where we see this?). looking at container metrics I do not see it in master.

Now next question is:
if I look in prometheus at this [entry](https://monitoring.osparc-master.speag.com/prometheus/graph?g0.expr=simcore_simcore_service_webserver_services_started_total&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h) for example I do not see the user agent. and we should add that as well.
