### ISSUE TITLE
Limit the amount of networks in the created networks

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3950]
Currently the director-v2 and the dy-sidecar will create the following networks:

- project_network (used by all user services in a project to comunicate between each other)
- dy_sidecar_UUID (used by the proxy to send traffic to the ingress container)
- back----end (all user services of are placed here)
- egress-i (connects the target container to the egress proxy)
- with_intenrt (provides internet connectivity to certain containers when internet is blocked)

None of the above have any limits regarding the maximum amount of hosts that should be used for the network. These should be enforced

- https://github.com/ITISFoundation/osparc-issues/issues/638

**Comment by GitHK** [comment]
@mrnicegyu11 I think you did a PR for this in ops. Can we close this case?

**Comment by mrnicegyu11** [comment]
Thanks for reminding me, I will do some tests to validate the behavior on prod and close this then later today if the tests are successful

**Comment by mrnicegyu11** [comment]
Test successful on aws-prod and tip, closing
