### ISSUE TITLE
docker version 23.0.1 is not supported by director-v2 unit tests

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3952]
on my linux machine I have docker version 23.0.1 installed.

issues are:
1. https://github.com/ITISFoundation/osparc-simcore/blob/48f1d77730c0230730ac633453703415c8713516/services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/volume_remover.py does not parse docker version correctly. it expected XX.XX.XX where XX.X.X seems to be valid
2. https://github.com/ITISFoundation/osparc-simcore/blob/48f1d77730c0230730ac633453703415c8713516/services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/volume_remover.py fails in test_sh_script_error_if_volume_is_used

**Comment by GitHK** [comment]
I have it under control. It is assigned to me and will tackle it this sprint. I need to finish with the volume removal which I am currently working on before also fixing the validator. See https://github.com/ITISFoundation/osparc-simcore/issues/3946
