### ISSUE TITLE
Analysis and visualization (2D)

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4]
**User story**

Some results will need visualization with tables and/or 2d plots. As a **user** I want to be able to visualize such data

**Definition of Done**
- [x] There is dedicated panel/view/dashboard in the frontend
- [x] There is a defined data structure for such results
- [x] Tables shall be sortable and editable
- [x] Selecting subsets in the table should dynamically update the plots
- [x] In addition to a Jupyter like script representation, a standalone 2D xy-viewer is needed

**Use case**

Clancy case is used as a first goal.

see comments below (at the end) for the updated definition of done.

**Comment by mguidon** [comment]
Embed this solution in s4l table viewers

**Comment by mguidon** [comment]
Add an new algorithm to sim4life that displays 2d data (series data, csv, excel) in a chromium view

**Comment by pcrespov** [comment]
## [Canceron](https://github.com/ITISFoundation/osparc-simcore/milestone/3) Milestone
 - [ ] workbench: model node -> computation node -> viewer node (with Jupiter)
 - [ ] two interactive resources available: 3d view and dashboard grid panel
 - [ ] demo node interaction with resources

**Comment by pcrespov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pipelines and analysis](https://trello.com/c/1RZX536V/149-pipelines-and-analysis)

**Comment by sanderegg** [comment]
Scenario 1:
1. User logs in
2. Workbench opens
3. User creates modeler node (producer node)
  a. Modeler node connects to Modeler service (IP:port)
  b. Workbench provides a widget that points to modeler service (IP:port)
  c. User loads a model/modify the model until happy in modeler widget
4. User creates computation node
  a. User creates computation pipeline…
  b. …
5. User links computation node to modeler node
  a. Workbench tells modeler node to pass its data (GLTF scene) to the computation node (IP:port, common RestAPI for all nodes?) (either directly or through DAT-CORE, other…)
6. User starts computation node
  a. Workbench tells modeler node to transmit its data to computation node or to DAT-CORE (RestAPI?)
  b. Workbench tells computation node where to find the input data
  c. Workbench starts computation node
  d. Computation node finishes computing and saves its data to DAT-CORE
7. User creates Jupyter notebook node (analysis node)
  a. Jupyter notebook node connects to Jupyter notebook service (IP:port)
8. User links Jupyter notebook node to computation node output
  a. Workbench tells Jupyter notebook where to get the data
  b. Workbench provides a widget that points to jupyter notebook (IP:port)
  c. User interacts with notebook in notebook widget

**Comment by sanderegg** [comment]
![image](https://user-images.githubusercontent.com/35365065/38723914-e94dbc22-3f02-11e8-9caa-3d7b4eb22e2b.png)
![image](https://user-images.githubusercontent.com/35365065/38723930-f259c4e6-3f02-11e8-9bad-b04c5fee6233.png)

**Comment by drniiken** [comment]
* demo
* progress

**Comment by pcrespov** [comment]
## [Caprica](https://github.com/ITISFoundation/osparc-simcore/milestone/4) Milestone - dev notes

- [ ] Prototype in Jupyter 2D plots from data Clancy model. Start simple, then create [widgets](http://jupyter.org/widgets).

**Comment by sanderegg** [comment]
- [ ] Creation of a python package to access the inputs/outputs to the Jupyter node from the Jupyter notebook
    - [ ] Access to inputs on the fly
    - [ ] Automatically import/export data from S3 storage
    - [ ] Automatically get/set configuration from DB

**Comment by sanderegg** [comment]
- [ ] autoplay notebook

**Comment by sanderegg** [comment]
Have a look at this as well:
https://rawgraphs.io/

**Comment by drniiken** [comment]
Nik & Esra tell the Team:
* contine with this approach
* go with plotly
* combination of it
* play around with the current implementation ...

**Comment by drniiken** [comment]
The proposed solution looks very attractive.
However, the following additional functionality would be important and we need to know, if it can be provided with the current solution
- generation of multiple plots within one service
- generation of combined plots (possibly, also with input derived from multiple inputs
- simplification of insertion of column titles (what went wrong in the NIH demo)
- can we make it easier to create standard 2D plots (maybe something like a template (while keeping the power of the current solution for people that want more control and flexibility)

We do feel that this solution is not mutually exclusive with a plotly based solution. Both can be attractive and can coexist. If we go for a plotly based solution in addition, we might want to make that one more flexible with also pipelining kind of functionality (as in the 3D viewing with paraview-web).

**Comment by esraneufeld** [comment]
i would like to close this case soon, as the current functionality is mostly sufficient for now:
before closing, please create two variant services:
- a simple 2d plot service, that does not provide the users with all these options for plot type, but rather just creates a standardized 2d plot, once the axes have been selected
- a table viewer service that only contains all the steps up to (and including) the specification of the table column titles, but no option to continue with plot creation
i will also create a lower priority follow-up case about addressing the issue of creating combined 2d plots from different sources.
