### ISSUE TITLE
Potentially wrong docker image labels on simcore images

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#4012]
I was looking into some corner cases of our docker-registry-watcher in the deployment-agent and noticed that the docker image labels of osparc-simcore services seems to have changed.
On v1.50.x (current prod release) I still see
```
- org.label-schema.vcs-url=https://github.com/ITISFoundation/osparc-simcore
- org.label-schema.vcs-ref=ad461f28cadfa009ca1aa925e51a36cff81795b8
- org.label-schema.build-date=2023-02-27T16:52:09Z
- io.osparc.api-version=0.3.0
- org.label-schema.build-date=1.0
```
set to reasonable values (via portainer).

On master & staging_Mithril2 however the variables mentioned above are all set to `1.0`.

I would need to know if this is a bug (i guess yes) and if or how impactful that is. Is this used anywhere?

master/staging ("wrong"):
![image](https://user-images.githubusercontent.com/8209087/226890756-b6f1de41-3ac3-4c49-9a85-4425aa21dce8.png)

prod v1.50.x ("right"):
![image](https://user-images.githubusercontent.com/8209087/226890804-a4ee4874-aca6-4d57-9d4b-3380603666cd.png)

**Comment by pcrespov** [comment]
@sanderegg found that it is a bug in buildx
