### ISSUE TITLE
🚀 Pre-release master -> staging_Mithril4

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4020]
### What kind of pre-release?

master branch

### Sprint Name

Mithril

### Pre-release version

4

### Commit SHA

b91f3442b25888e3997d20af24fb769e80f53921

### Did the commit CI suceeded?

- [X] The commit CI succeeded.

### Motivation

fixed p2e test with opencor/kember by redefining catalog minimal resources

### What Changed

*  https://github.com/ITISFoundation/osparc-simcore/pull/3998 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4005 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4016 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3984 by @pcrespov 
* https://github.com/ITISFoundation/osparc-simcore/pull/4015 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4017 by @sanderegg 

**Full Changelog**: https://github.com/ITISFoundation/osparc-simcore/compare/staging_Mithril3...staging_Mithril4

### Devops check ⚠️ devops

- [x] Add changes (if any) and release tags in https://github.com/ITISFoundation/osparc-ops-environments/tags
- [x] Add changes (if any) and release tags in osparc ops configurations
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/3998 @mrnicegyu11 

### e2e testing check 🧪

- [x] e2e: isolve-mpi is red since a day, need to check
- [x] e2e: parallels are reddish but this seems unrelated
- [x] p2e: is green with this change
- [x] ops: green

### Summary 📝

- [x] `` make release-staging name=Mithril version=4 git_sha=b91f3442b25888e3997d20af24fb769e80f53921``
- [x] Draft [pre-release](https://github.com/ITISFoundation/osparc-simcore/releases)
- [x] Announce
  ```json
  {"start": "2023-03-23T13:30:00.000Z", "end": "2023-02-01T14:00:00.000Z", "reason": "Release Mithril4 "}
  ```

### Releasing

- [x] Release (release draft)
- [x] Check [Release CI](https://github.com/ITISFoundation/osparc-simcore/actions/workflows/ci-staging.yml)
- [x] Check deployed
  - [x] aws deploy
  - [x] dalco deploy
- [x] Delete announcement
- [x] Check e2e runs
- [x] Announce
``` md
https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Mithril4
```
### Post-mortem
- [x] log in the issue relevant issues encountered during the release
- [ ] close this issue

**Comment by mrnicegyu11** [comment]
--> DevOps changes are unrelated to this scheduled prerelease and are tracked by this ticket: https://git.speag.com/oSparc/osparc-ops-environments/-/issues/524

**Comment by sanderegg** [comment]
release to staging was done.
## Post-mortem:
- deployment-agent did not auto-release correctly: the ENVs on the catalog that were changed in osparc-simcore were not properly updated. Needed to restart the deployment-agent (done by @mrnicegyu11). The value of ```CATALOG_SERVICES_DEFAULT_RESOURCES``` was updated.
