### ISSUE TITLE
🚀 Release v1.51.0

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4023]
### Release version

1.51.0

### Commit SHA

b91f3442b25888e3997d20af24fb769e80f53921

### Previous pre-release

https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Mithril4

### Did the commit CI suceeded?

- [X] The commit CI succeeded.

### Motivation

Permalink feature in production ready before SCM

### [staging_Mithril1](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Mithril1)

* https://github.com/ITISFoundation/osparc-simcore/pull/3916 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3703 (#3635) by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3926 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3919 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3925 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3927 by @dependabot
* https://github.com/ITISFoundation/osparc-simcore/pull/3856 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3933 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3935 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3928 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/3936 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3945 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/3930 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3947 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3942 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3949 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3956 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3909 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3957 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/3955 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3937 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3948 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3961 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3963 by @odeimaiz

**Full Changelog**: https://github.com/ITISFoundation/osparc-simcore/compare/staging_ResistanceIsFutile16...staging_Mithril1
**Release issue**: https://github.com/ITISFoundation/osparc-issues/issues/896

### [staging_Mithril2](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Mithril2)
* https://github.com/ITISFoundation/osparc-simcore/pull/3960 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3970 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3967 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/3973 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3976 [📌 to  `v1.50.1`] by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3978 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3972 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3979 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3958 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3982 [📌 to  `v1.50.2`] by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3985 [📌 to  `v1.50.2`] by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3980 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3983 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3988 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3962 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3995 by @odeimaiz

**Full Changelog**: https://github.com/ITISFoundation/osparc-simcore/compare/staging_Mithril1...staging_Mithril2
**Release Issue**: https://github.com/ITISFoundation/osparc-simcore/issues/4002

### [staging_Mithril3](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Mithril3)

* https://github.com/ITISFoundation/osparc-simcore/pull/4000 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3997 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/4001 (ITISFoundation/osparc-issues#829) by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3989 by @sanderegg

**Full Changelog**: https://github.com/ITISFoundation/osparc-simcore/compare/staging_Mithril2...staging_Mithril3
**Release Issue** https://github.com/ITISFoundation/osparc-simcore/issues/4009

### [staging_Mithril4](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Mithril4)

* https://github.com/ITISFoundation/osparc-simcore/pull/3998 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4005 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4016 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/3984 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4015 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4017 by @sanderegg

**Full Changelog**: https://github.com/ITISFoundation/osparc-simcore/compare/staging_Mithril3...staging_Mithril4
**Release Issue** https://github.com/ITISFoundation/osparc-simcore/issues/4020

### Devops check 👷

- [x] Review changes above with (⚠️ devops)
   - [x] catalog environ missing (check issue opened by @sanderegg ) 
- [ ] Add changes (if any) and release tags in https://github.com/ITISFoundation/osparc-ops-environments/tags
- [ ] Add changes (if any) and release tags in osparc ops configurations

### Tests assessment: e2e testing check 🧪

- [ ] vtk links failing staging
- [ ] gc in aws-staging. @mrnicegyu11 looking into it.

### Test assessment: targeted-testing 🔍️

- [x] Check changes by @GitHK 
- [x] Check changes by @sanderegg  
- [x] Check changes by @pcrespov 
- [x] Check with @elisabettai  

### Summary 📝

- [x] Prepare release link
```cmd
make release-prod version=1.51.0  git_sha=b91f3442b25888e3997d20af24fb769e80f53921
```
- [x] Draft [release changelog](https://github.com/ITISFoundation/osparc-simcore/releases)
- [x] Announce maintenance. **Tue, Mar.28 from 10:30 - 12:00 am**  : 
- redis 
   ```json
      { 
        "start": "2023-03-28T08:30:00.000Z", 
        "end":   "2023-03-28T10:00:00.000Z", 
        "reason": "Release v1.51.0"
      }
    ```
    - [x] aws
    - [x] dalco
    - [x] tip
- [status page](https://manage.statuspage.io/login)
    - [x] osparc
    - [x] s4l
- mattermost channels
    - [x] maintenance
    - [x] power users

### Releasing 🚀

- [x] Maintenance page up 👷
- [x] Release by publishing [draft](https://github.com/ITISFoundation/osparc-simcore/releases)
- [ ] Check [release CI](https://github.com/ITISFoundation/osparc-simcore/actions/workflows/ci-release.yml)
- [ ] Check deployed
  - [x] aws deploy
  - [ ] dalco deploy
  - [ ] tip deploy
- [x] Delete announcement
- [x] Check e2e runs
- [ ] Announce
``` md
:tada: https://github.com/ITISFoundation/osparc-simcore/releases/tag/v1.51.0
```

**Comment by pcrespov** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/32402063/227526795-c9a4db20-a647-447e-b9eb-67652295b967.png">
WARNING: see time!

**Comment by mrnicegyu11** [comment]
## BLOCKED 

This issue https://github.com/ITISFoundation/osparc-simcore/issues/4027 until understood / fixed *is a blocker for me to release to prod,* please provide some comforting words for poor mrnicegyu11 or adress the bugs. thanks :)
