### ISSUE TITLE
Garbage collector not collecting garbage + related

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#4027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

staging aws (e.g. staging.osparc.io)

### Current Behavior

With the new grafana alert for pending docker services we noticed that aws-staging had an increasing number of pending docker services today, starting from 11am swiss time. The services could clearly be related to e2e / p2e started containers, such as kember, cc, etc.

An investigation of the garbage collector showed that for some hours, from at least 11am until approx. 15:15 Zurich time, no garbage was collected. At 15:15, garbage collection resumed for 1 successful run, clearing the resource load on the machines, but afterwards the GC reported errors again. This can be seen as the characteristic logs-lines `Step 1`, `Step 2`, `Step 3` where missing.
Instead, the garbage collector seemed to be not continuing its garbage collection for 1h intervals multiple times, which hints at this being related to 3600s timeouts in the director-v2, that were reported at the same time. During these 1h "pauses" of the garbage collector, only healthchecks were logged.

Ideally, the garbage collector should in an async fashion continue its garbage removal even if a long running HTTP request has a timeout of 3600s. It is not desirable to have the GC paused and waiting 3600s, as then the resources on the nodes may fill up with orphaned services during this time.

During this investigation, a significant number of errors in both director-v2 and GC related to the dy-sidecar `dy-sidecar_5f7ea91a-0aff-4eae-9587-8721c195a073` were noted. This sidecar and the assoc. s4l-lite-web service can be seen to have shut down correctly (as indicated by successful S3 upload and message `🎉 App shutdown completed 🎉`), and the autoscaled node went into a drained state only seconds after the shutdown of the sidecar.

To the best of our understanding, for `dy-sidecar_5f7ea91a-0aff-4eae-9587-8721c195a073`, which is our best guess at finding at least one root cause of the GC failure, the timeline is as follows:
- User/Puppetter initiates shutsdown dy-service s4l-lite-web
- director-v2 reports `WARNING:simcore_service_director_v2.modules.dynamic_sidecar.docker_api._core:Skipped labels update for service 'dy-sidecar_5f7ea91a-0aff-4eae-9587-8721c195a073' which could not be found.` (time `2023-03-23 15:27:12`)
- dy-sidecar on autoscaled node `ip-10-0-2-157` shuts down successfully (time `2023-03-23 15:27:15`)
- director-v2 reports `ValueError: 'dy-sidecar_5f7ea91a-0aff-4eae-9587-8721c195a073' does not appear to be an IPv4 or IPv6 address` (see https://monitoring.staging.osparc.io/graylog/messages/graylog_9/315edc01-c98f-11ed-8b8d-0242ac12001a , time `2023-03-23 15:27:16`)
- director-v2 complains with `ERROR:simcore_service_director_v2.modules.dynamic_sidecar.api_client._base:Request timed-out after 1 attempts with an unexpected error: 'e.request=<Request('POST', 'http://dy-sidecar_5f7ea91a-0aff-4eae-9587-8721c195a073:8000/v1/containers:down')>':e=ConnectError('[Errno -2] Name or service not known')`
- autoscaled node goes into drained state (time `2023-03-23 15:27:48`)

Please note that 'dy-sidecar_5f7ea91a-0aff-4eae-9587-8721c195a073' was probably not responsible for the GC failure between 11am and 3pm, but had *lots* of errors and cried for an investigation into its errors. It might be unrelated to the GC issue.

In general, it was very painful to establish already this minimal information, as the director-v2 logs are riddled with errors and warnings. I would please ask that the errors of the director-v2 are looked into and handled, soon. 

For example: https://monitoring.staging.osparc.io/graylog/messages/graylog_9/2ee92111-c98f-11ed-8b8d-0242ac12001a (why is an exited container an unexpected container status? It exited with code 0 so this is fine?). 
Furthermore, some warnings dont make sense when reading them during debugging:. This is an entire log from director-v2, what does this mean, what is `Retrying None`? `WARNING:simcore_service_director_v2.modules.dynamic_sidecar.api_client._base:Retrying None in 1.0 seconds as it raised ConnectError: [Errno -2] Name or service not known.`?

For more deep-dives, please check as well: 
- https://monitoring.staging.osparc.io/graylog/search?q=NOT+container_name%3A%2F.%2Atraefik.%2A%2F+AND+%225f7ea91a-0aff-4eae-9587-8721c195a073%22&rangetype=absolute&from=2023-03-23T09%3A09%3A34.276Z&to=2023-03-24T14%3A13%3A44.195Z
- https://monitoring.staging.osparc.io/graylog/search?q=container_name%3A%2F.%2A5f7ea91a-0aff-4eae-9587-8721c195a073.%2A%2F&rangetype=absolute&from=2023-03-23T15%3A11%3A24.886Z&to=2023-03-23T15%3A44%3A54.433Z
- https://monitoring.staging.osparc.io/prometheus/graph?g0.expr=swarm_node_info%7Binstance%3D~%22ip-10-0-2-157%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=13s329ms&g0.end_input=2023-03-23%2015%3A27%3A57&g0.moment_input=2023-03-23%2015%3A27%3A57

CC @matusdrobuliak66 who helped me trace this.

### Expected Behavior

- GC works and collects garbage
- GC does not use blocking functions that will make him idle for 60min 
- There is a graylog/grafana alert for the GC not working, since this requires human intervention
- Director-v2 errors and warnings are addressed (fixed)
- Director-v2 logs are refactored to be more understandable

### Steps To Reproduce

I will add a .zip file with the GC logs, use the redis-commander pw for aws-staging to access the logs. You can also use graylog.

### Anything else?

It pains me to say this but for me, as long as what happened here is not understood at all (and you might be able to see from the description that we really struggled to understand causality due to the large amount of errors), this is for me a blocker to release to production. If garbage collection fails a few times, considering e2e and p2e testing, the resources on the deployments will be used up fully and the platform will become unresponsive. 

I will adjust the v1.51.0 release document to indicate this blocker from my side.

I am available for further discussions and tracing. Things that would resolve this block for me:
- Understanding of why this happened.
- Understanding of why the garbage collector suddenly worked again for 1 run without human intervention.

@pcrespov  I suggest for releases from staging to prod to also check the logs of all simcore services for `Tracebacks` and `ERROR`s in the future, we might be lucky to have caught this in staging since there is some flakiness or randomness involved whether garbage is collected or not.

**Comment by mrnicegyu11** [comment]
[staging_aws_GC_failure_24mar2023.zip](https://github.com/ITISFoundation/osparc-simcore/files/11064403/staging_aws_GC_failure_24mar2023.zip)

**Comment by sanderegg** [comment]
```what is Retrying None```
- this message comes from [tenacity when using a context manager](https://github.com/jd/tenacity#retrying-code-block) and I agree this is misleading. One way to improve this would be to use the decorator instead of the context manager and it would print the function name of what it is retrying. Otherwise, one would need to improve the ```before_sleep_log``` callback fct.

**Comment by pcrespov** [comment]
@GitHK is this fully resolved?

**Comment by GitHK** [comment]
Since this is related to https://github.com/ITISFoundation/osparc-simcore/issues/4035
This is also fixed. Closing.
