### ISSUE TITLE
Implement RED method in simcore services to evaluate performance

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4028]
This RED method seems a very good start to understand our services load...

https://www.infoworld.com/article/3638693/the-red-method-a-new-strategy-for-monitoring-microservices.html#:~:text=RED%20method%20explained,of%20failed%20requests%20per%20second
```[tasklist]
### Tasks
- [ ] review clients for open-telemetry vs zipkin @matusdrobuliak66
- [x] enable prometheus in fastapi-services in servicelib
```

**Comment by matusdrobuliak66** [comment]
> This RED method seems a very good start to understand our services load...
> 
> https://www.infoworld.com/article/3638693/the-red-method-a-new-strategy-for-monitoring-microservices.html#:~:text=RED%20method%20explained,of%20failed%20requests%20per%20second

I found a few tools that can do this out of the box, but for Kubernetes deployments:
- istio (https://vorozhko.net/implementing-red-method-with-istio)
  - Istio uses its own sidecar proxy, called Envoy, to collect metrics about the traffic flowing between microservices. These metrics are then used to monitor the performance of the microservices and to enforce traffic policies. In addition, Istio provides a powerful telemetry system that includes metrics, traces, and logs, which can be used to gain insights into the performance and behavior of the microservices.
- maybe Traefik Mesh (https://traefik.io/traefik-mesh/)
- maybe Linkerd

For the docker swarm hasn't yet found something similar, probably we would need to collect all the needed metrics by Prometheus.

**Comment by pcrespov** [comment]
TIPS:
- Review diagnostic handlers https://github.com/ITISFoundation/osparc-simcore/blob/224fee941d30230fcd151955a3638da41c34ef63/services/web/server/src/simcore_service_webserver/diagnostics_handlers.py

I propose to extend them uniformly along all services so we have the same diagnostics API throughout all services that tells use things like:
- connectivity with other backend services (ping)
- memory usage
- stress of events loop
- etc

**Comment by matusdrobuliak66** [comment]
- I was looking into how to setup [jaeger client](https://github.com/jaegertracing/jaeger-client-python) -> and they urge people to start to use https://opentelemetry.io/ . 
- Putting it here just for reference (automatic-instrumentation -  it dynamically injects bytecode to capture telemetry from many popular libraries and frameworks)
  -  FastApi: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/fastapi/fastapi.html
  -  Aiohttp: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/aiohttp_client/aiohttp_client.html

**Comment by pcrespov** [comment]
@bisgaard-itis some of the work you have been doing on monitoring is in this line.  Could you update this case adding some info of what you ahve been doing please. Please add PRs/issues as well.

**Comment by bisgaard-itis** [comment]
I believe the second task here was already accomplished by https://github.com/ITISFoundation/osparc-simcore/pull/5217. Or perhaps I am misunderstanding the point of the task.

**Comment by bisgaard-itis** [comment]
I think a good starting point would be [this](https://github.com/blueswen/fastapi-observability?tab=readme-ov-file) repo which sets up a toy system with three apps and adds different levels of observability (using fastapi). It uses [opentelemetry](https://github.com/open-telemetry/opentelemetry-python) for tracing and [Grafana  Tempo](https://github.com/grafana/tempo) as a tracing backend (which should fit well since we are already using grafana). I would very much like to be part of this work!

**Comment by matusdrobuliak66** [comment]
Closing as a lot of new observability functionality was implemented by @bisgaard-itis in the last months
