### ISSUE TITLE
interactive_services_manager.py deprecated?

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#403]
services/web/server/src/simcore_service_webserver/director/interactive_services_manager.py ?

please add deprecation warning or remove/disable (e.g. remame inteactive_services_manager_deprecated.py_

Saw also dependencies services/web/server/src/simcore_service_webserver/sockets_handlers.py

if not used, please do the same

**Comment by sanderegg** [comment]
do we have a solution for the autokill feature?

**Comment by sanderegg** [comment]
- [x] interactive_service_manager removed
- [ ] what about sockets_handlers.py?

**Comment by sanderegg** [comment]
@pcrespov : do we still need the websockets in webserver? I see sockets_handlers.py from sockets.py. Actually both are unnecessary right?

**Comment by pcrespov** [comment]
@sanderegg  yes

The computation subsystem still sends the logger and the progress via socketio.
webserver/src/sockets.py defines the subsystem's setup function that attaches the sockets to the app.
It is minimal but we keep what we have.
