### ISSUE TITLE
Refactor GC to not block for stopped services

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#4068]
GC searches for all the services which should be stopped and then stops all of them in parallel (waiting for all of them to be done before sleeping and triggering again)

**Comment by sanderegg** [comment]
@GitHK not sure that is still a thing. can you elaborate or close it if that is outdated? thanks

**Comment by GitHK** [comment]
I think this was changed. Closing this for now. If required we'll change the GC.
