### ISSUE TITLE
Limit number of logs displayed in UI

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4076]
proposal:
similar to Portainer allow the user to:
- [ ] limit the number of messages shown in the frontend (500, 1000, 2000 whatever is a constant memory)
- [ ] could be limited to the current filters
- [ ] pagination
- [ ] allow to change the log level via a backend call
- [ ] do not overflow the memory

**Comment by sanderegg** [comment]
@odeimaiz this one can be closed for now right?

**Comment by odeimaiz** [comment]
yes
