### ISSUE TITLE
Backlog on GDPR (General data protection Regulation)

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4087]
After listening to https://talkpython.fm/episodes/show/409/privacy-as-code-with-fides I would like to review how to fully comply with most privacy specs required by regulators

- [x] Opt-out from platform and delete entire account
- [x] Review share/unshare

Some references to review

- https://en.wikipedia.org/wiki/General_Data_Protection_Regulation 
- https://www.oag.ca.gov/privacy/ccpa

**Comment by mrnicegyu11** [comment]
Hey @pcrespov, I was re-reasing this ticket and  the tasks listed in your comment arenot actionable to me. From my side, we look on track for the GDPR things. I am re-assigning this to you, feel free to close :--)
