### ISSUE TITLE
PublicAPI: Allow to list all created jobs (support paging)

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4110]
Currently it is possible to list jobs but this is limited to 20 and there is no possibility to list more.
proposal:
- add paging
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4407
- [ ] https://github.com/ITISFoundation/osparc-simcore-python-client/issues/38
```

**Comment by pcrespov** [comment]
I wonder if we could add pagination options in the headers so it does not affect the python client generation ... otherwise we should add defaults

**Comment by bisgaard-itis** [comment]
@sanderegg Do you know what the last point in the tasklist is about? I am just wondering if we could close this one?
