### ISSUE TITLE
♻️ remove code once #4202 hits production

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#4204]
once https://github.com/ITISFoundation/osparc-simcore/pull/4202 reaches production remove code

- `_can_save_is_no_longer_none` from `services/director-v2/src/simcore_service_director_v2/models/schemas/dynamic_services/scheduler.py`

**Comment by pcrespov** [comment]
@GitHK #4202 already reached production in https://github.com/ITISFoundation/osparc-simcore/issues/4236 :-)

**Comment by GitHK** [comment]
Thanks for this. I will put it my list of things to do.

**Comment by pcrespov** [comment]
@GitHK closed??

**Comment by sanderegg** [comment]
@GitHK @pcrespov 
no the warning is still there
What needs to be done?
