### ISSUE TITLE
cMIS export: remove unnecessary files and update existing ones to latest SDS

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#4216]
### Is there an existing issue for this?
This is a sub task of https://github.com/ITISFoundation/osparc-issues/issues/673

### User Story

I am a oSPARC user who wants to submit my oSPARC template for publication on the SPARC Portal. I have to manually fill in the following files:
- template.json (file containing the uuid that makes the link between the Portal and oSPARC)
- dataset_description.xlsx
- manifest.xlsx
- (an image file for thumbnail (nice to have, not a blocker))
- code_descritption.xlsx (see last box below).

I'd propose to fill in as much of this information as possible with metadata from the study, the rest will need to be added/modified manually by the user.
### Useful links
- Templates for excel files: https://docs.sparc.science/docs/sparc-dataset-structure
- Example of a dataset with the necessary files: https://sparc.science/datasets/325?type=simulation&datasetDetailsTab=files
### Definition of Done

After reviewing the files with current export function, I'd propose these changes.
- [x] Change `code/manifest.xlsx` (see [this file](https://github.com/ITISFoundation/osparc-simcore/files/11441747/manifest.xlsx)). Also I see useful information about inputs/outputs there, but I don't see all of them.
- [x] Change [dataset_description.xlsx](https://github.com/ITISFoundation/osparc-simcore/files/11441730/dataset_description.xlsx) and pre-fill some of the fields (see example file attached, the things that can be prefilled are in blue, leave the black ones as they are, e.g. "Computational modelling"). In the final file, all text should be in black. 
- [x] Rename the file `code/project.json` to `template.json` and fill it with information from the study (example [here](https://sparc.science/file/308/1?path=files%2Ftemplate.json))
- [x] Remove the folder `derivative`
- [x] Remove the folder `docs`
- [x] Remove the folder `storage` (this should happen when #4213 is fixed)
- [x] Remove the files: `CHANGES`, `README`, `manifest.json`, `submission.xlsx`
- [ ] Nice to have: if the study has a thumbnail, download the corresponding image file.

**Comment by GitHK** [comment]
@elisabettai except the thumbnail everything is here. I would like to avoid adding it, since depending on the source it may take a lot of time to fetch it.
