### ISSUE TITLE
API: I would like to get hold of the solver log even if I stop a job

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

Not high priority. Is sometimes useful to debug.

Also, I am not sure if I get a log if the solver fails? @pcrespov?

**Comment by sanderegg** [comment]
waiting for https://github.com/ITISFoundation/osparc-simcore/actions/runs/4992869205 to be deployed...

**Comment by mguidon** [comment]
Works. Thanks
