### ISSUE TITLE
🚀 Release v1.53.0

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#4236]
### Release version

1.53.0

### Commit SHA

`2ab6150f23ae2765f7373d3c49019eea79e8faaa`

### Previous pre-release

https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_PastelDeNata4

### Did the commit CI suceeded?

- [x] The commit CI succeeded.

### Motivation

lorem ipsum

#### Staging JellyBeans3
**Release Issue**: https://github.com/ITISFoundation/osparc-simcore/issues/4156

* https://github.com/ITISFoundation/osparc-simcore/pull/4100 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4117 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4131 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4133 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4055 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/3974 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4139 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4136 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4105 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4141 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4064 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4138 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4137 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4146 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4147 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4134 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4145 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4154 by @dependabot
* https://github.com/ITISFoundation/osparc-simcore/pull/4160 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4162 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4163 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4165 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4170 by @GitHK

#### Staging PastelDeNata1
**Release Issue**: https://github.com/ITISFoundation/osparc-simcore/issues/4200

* https://github.com/ITISFoundation/osparc-simcore/pull/4149 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4175 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4169 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4171 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4181 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4164 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/4182 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4123 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4176 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4043 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4187 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4178 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4184 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4190 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4183 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4173 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4188 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4166 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4193 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/4195 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4196 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4194 by @pcrespov

#### Staging PastelDeNata2
**Release Issue**: https://github.com/ITISFoundation/osparc-simcore/issues/4224

* https://github.com/ITISFoundation/osparc-simcore/pull/4186 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4201 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/4180 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4203 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4198 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4202 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4206 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4008 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4207 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4208 by @elisabettai
* https://github.com/ITISFoundation/osparc-simcore/pull/4212 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4215 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4218 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/4220 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4221 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4211 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4217 by @GitHK

#### Staging PastelDeNata3
**Release Issue**: https://github.com/ITISFoundation/osparc-simcore/issues/4240

* https://github.com/ITISFoundation/osparc-simcore/pull/4205 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4222 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4214 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4225 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4209 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4226 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4199 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4219 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/3774 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4227 by @odeimaiz

#### Staging PastelDeNata4
**Release Issue**: https://github.com/ITISFoundation/osparc-simcore/issues/4261

* https://github.com/ITISFoundation/osparc-simcore/pull/4230 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4238 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4232 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4233 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4241 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/4242 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4210 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/4245 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/3812 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4197 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4246 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/4252 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/4249 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4243 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/4235 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4239 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/4248 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/4254 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4257 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/4259 by @dependabot

_No response_

### Devops check 👷

- [x] Add changes (if any) and release tags in https://github.com/ITISFoundation/osparc-ops-environments/tags
- [x] Add changes (if any) and release tags in **osparc-ops-deployment-configuration** (osparc.io & osparc.speag.com & tip.itis.swiss)
- [ ] ...

### Summary 📝

- [x] Prepare release link
```cmd
make release-prod version=1.53.0 git_sha=2ab6150f23ae2765f7373d3c49019eea79e8faaa
```
- [x] Draft [release changelog](https://github.com/ITISFoundation/osparc-simcore/releases)
- [x] Announce maintenance ( ** ANNOUNCE AT LEAST 24 HOURS BEFORE ** )
- redis ``{"start": "2023-05-31T13:00:00.000Z", "end": "2023-05-31T14:30:00.000Z", "reason": "Release 1.53.0"}``
    - [x] aws
    - [x] dalco
    - [x] tip
- status page (https://manage.statuspage.io/)
    - [x] osparc
    - [x] s4l
- mattermost channels
    - [x] maintenance
    - [x] power users

### Releasing 🚀

- [x] Maintenance page up.
- [x] Release by publishing [draft](https://github.com/ITISFoundation/osparc-simcore/releases)
- [x] Check release CI
- [x] Check deployed
  - [x] aws deploy
  - [x] dalco deploy
  - [x] tip deploy
- [x] Delete announcement
- [x] Check e2e runs
- [x] Announce
``` md
:tada: https://github.com/ITISFoundation/osparc-simcore/releases/tag/v1.53.0
```

**Comment by mrnicegyu11** [comment]
Caveat: Deployment agent in aws-prod is paused for
- https://z43.fogbugz.com/login?dest=%2ff%2fcases%2f180484%2fTrouble-I-meet-when-I-use-the-sim4life-lite
- https://git.speag.com/oSparc/osparc-ops-environments/-/issues/578
(i.e. an env-var was adjusted in portainer )

**Comment by GitHK** [comment]
As asked by @odeimaiz I have added the country code UK for osparc.io 
Since this restarts the director-v2 we need to schedule a maintenance in order to release the changes for the env vars changed on the webserver. 

Relative commit

https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/tree/a427c0599462e366406b125e2b6e37722c1e5316

**Comment by GitHK** [comment]
@mrnicegyu11 @matusdrobuliak66 @odeimaiz 
The env var were update on prod AWS since the auto deploy agent is paused and this old required a webserver restart.
As of now consider this to be deployed on production. There is no more urgency to release this before the 1st of June

**Comment by mrnicegyu11** [comment]
There is something very weird going on with node dalco06. We absolutely cannot ssh into it anymore, but it is still part of the docker swarm and runs containers. Let's use the user logout and maintenance to remove this machine from the swarm for further investigation. During the maintenance when users are logged out, please run `docker node update --availability drain osparc-dalco-06`, potentially making sure that also from dalco staging no user is working on this machine. Thanks

**Comment by matusdrobuliak66** [comment]
Release after notes: 
 - A lot of hanging sidecars were on Dalco, and also a few on AWS, it took us a long time to close them (most of them had s3 upload issues)
- in-house network stopped working for 0.5-1 hour
- few ENV vars were missing in the config file after the first deployment (DYNAMIC_SIDECAR_ENABLE_VOLUME_LIMITS & LOG_FORMAT_LOCAL_DEV_ENABLED) so we added them and retag the ops repos

Observations:
 - the company network was not working and in aws we limit who can access it with ips from the company, therefore we were not able to access the AWS monitoring stack
 - In the Dalco production when the maintenance page was up and the Redis maintenance key setup, we were not able to use testing.* endpoint to bypass these restrictions
