### ISSUE TITLE
Computational backend: State of solvers is reported wrongly

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

staging aws (e.g. staging.osparc.io)

### Current Behavior

I have 4 solver jobs and start them all at the same time. They go from pending to starting immediately although the actually dont start yet because they do no have enough resources to run concurrently.

### Expected Behavior

Probably state should be pending?

**Comment by sanderegg** [comment]
@mguidon on this one I will need some example that I can reproduce. I was not able to using sleepers.

**Comment by sanderegg** [comment]
closing this as not reproducible and possibly outdated.
