### ISSUE TITLE
qx compiler does not work in MaG and Dev computers

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#426]
In DC the qx compiler did not work in MaG and Dev Computer.

- **UPDATE**:  @oetiker updated the qx-compiler in #456
- [ ] check it works in MaG and Dev computers
- [ ] move webclient to ITISFoundation/dockerfiles repo. Latest versions should be pushed to Dockerhub

**Comment by odeimaiz** [comment]
child of #572

**Comment by mguidon** [comment]
I think this has been resolved a while ago
