### ISSUE TITLE
Flaky tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py::test_handling_scheduling_after_reboot

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#4268]
```
FAILED tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py::test_handling_scheduling_after_reboot[reboot with failed tasks] - AssertionError: expected state: ABORTED, found: [<RunningState.FAILED: 'FAILED'>]
[1787](https://github.com/ITISFoundation/osparc-simcore/actions/runs/5069482377/jobs/9103177464?pr=4267#step:9:1788)
```

reference 
https://github.com/ITISFoundation/osparc-simcore/actions/runs/5069482377/jobs/9103177464?pr=4267#step:9:1787

**Comment by pcrespov** [comment]
FYI: https://github.com/ITISFoundation/osparc-simcore/actions/runs/6377778957/job/17307082795?pr=4803#step:8:1717

```
FAILED tests/unit/with_dbs/test_modules_comp_scheduler_dask_scheduler.py::test_handling_scheduling_after_reboot[reboot with failed tasks] - AssertionError: expected state: ABORTED, found: [<RunningState.FAILED: 'FAILED'>]
assert False
 +  where False = all(<generator object _assert_comp_tasks_db.<locals>.<genexpr> at 0x7f8005142490>)
```

**Comment by pcrespov** [comment]
FYI: https://github.com/ITISFoundation/osparc-simcore/actions/runs/6395430856/job/17359083256#step:8:1723

**Comment by pcrespov** [comment]
FYI: https://github.com/ITISFoundation/osparc-simcore/actions/runs/6510211420/job/17683566860?pr=4862#step:8:1718

**Comment by pcrespov** [comment]
FYI: Note exactly the same but in the same topic https://github.com/ITISFoundation/osparc-simcore/actions/runs/6538396600/job/17754298360?pr=4870#step:8:1406

**Comment by sanderegg** [comment]
stale and not happening anymore
