### ISSUE TITLE
Disable editing when state does not allow

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

I am getting bombarded with messages that I shall not edit the workbench while a job is running

![image](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/1d05efb9-5505-445f-a563-221d00aec155)

Can we disable editing in that case? Or at least dont stack the error notifications?

### Definition of Done

I cannot even start editing while a job is running (maybe make the dashboard visually change to accommodate for the read-only state) or avoid plastering the monitor with notifications

**Comment by odeimaiz** [comment]
Implemented
