### ISSUE TITLE
tests/unit/test_modules_outputs_watcher.py::test_port_key_sequential_event_generation[1-file_generation_info1]

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4300]
reference: [https://github.com/ITISFoundation/osparc-simcore/actions/runs/5148473856/jobs/9271122800](https://github.com/ITISFoundation/osparc-simcore/actions/runs/5148473856/jobs/9271122800)

**Comment by GitHK** [comment]
should have been fixed 12 months ago. closing
