### ISSUE TITLE
Replace pylint by ruff?

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4323]
we should give a try to https://github.com/charliermarsh/ruff

_Originally posted by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/4320#pullrequestreview-1464834020_
            
- reuse `.pylintrc` rules with ruff?
- pre-commit?
- separate actions?
-

**Comment by sanderegg** [comment]
added ruff tooling in https://github.com/ITISFoundation/osparc-simcore/pull/4432
