### ISSUE TITLE
Add CLI settings command in dask-sidecar

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4331]
See parent issue (and associated PRs) for details 

This should work
```cmd
cd services/dask-sidecar
make settings-schema.json
```

When it works, add the entry in the `settings-schema.json:` of the main Makefile

**Comment by GitHK** [comment]
- consider using the solution from here https://github.com/ITISFoundation/osparc-simcore/pull/4338

**Comment by pcrespov** [comment]
> @pcrespov can you explain the use of that command and its relation with the dask-sidecar? This guy currently has no entrypoint because it is used as plugin to the dask-worker/dask-scheduler command of distributed[dask].

@sanderegg after our discussion 
- this service is loaded by `dask` executable vs other services are loaded by `uvicorn` executable
- this service works either as worker/scheduler
- this service has `settings` class but does not capture env-vars passed to `dask` executable

I understand that the are differences wrt the other services layout. Nonetheless, in retrospective i notice that the other services also have the problems you pointed in here since they are not directly the executables but driven by the servers i.e. `uvicorn` or `gunicorn` .. which themselves have also environs. I did not anticipate this so I guess we will have to go back to this in a near future when the artifacts in the CI are finally used.

I let you to close this issue and eventually postpone actions .
