### ISSUE TITLE
front-end view page cannot render only a study with a single file-picker

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4342]
- Since https://github.com/ITISFoundation/osparc-simcore/pull/4043, the dispatcher plugin allows creating a project with a single file-picker (and no service) but the redirection to a front-end view-page shows as
![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/1a69a62b-8f95-47ab-abce-4ead25441ff7). 
- This is not what the user would expect but it is working as designed since front-end view page was originally created to display the GUI of a single interactive service and here we have a file-picker only!  
- Nonetheless, in the case of registered users, this how the re-direction displays:
![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/84b41e15-7e1e-4e9b-86c6-48bc4080d6df)
so that I would later on build some pipeline etc...
- We decided that dispatching projects with a single file-picker is **reserved to registered users**. So there are at least two things to analyze:
1. why a study is actually created in this case? Dispatcher should reject right-at-once this type of requests coming from an anonymous user! 
2. can we modify the view so that it shows "registration required"-like message instead of "idle viewer"?  ( Add @odeimaiz  in the issue to discuss possibilities )

CC: @elisabettai @ignapas

**Comment by elisabettai** [comment]
Thanks @pcrespov for reporting.
For a non-registered user maybe we can show the same view as an anonymous user (the same view as the one guests see when accessing links from the Portal)? But we would also need to disable the software catalog, I don't know how easy is that, maybe @odeimaiz knows.

Ideally, what the PO would expect in case of a Guest user access is to have the software catalog, without certain services that shouldn't be accessed without login (e.g. Jupyters). Just as a reminder, I know @pcrespov we discussed something different. 😉
