### ISSUE TITLE
Dask scheduler has issues with clusters

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a fresh deploy the situation is as follows:
- WEBSERVER_CLUSTERS=0
- 4 clusters in the database (2 x identical IP)
- no running ec2 instances for MaG cluster

No computational jobs can be run on the default cluster, all jobs remain in PUBLISHED. There are errors in the director log. He is trying to create a client to my cluster.

[staging-simcore_staging_director-v2_logs.txt](https://github.com/ITISFoundation/osparc-simcore/files/11743294/staging-simcore_staging_director-v2_logs.txt)

**Comment by mguidon** [comment]
After restart of director_v2: Same problem.

**Comment by mguidon** [comment]
I leave this setup for a while to see what happens to the e2e. The weird thing is that if this affects the puppeteer as well. Also, there are two other clusters pointing to an IP that does probably not exist.

**Comment by mguidon** [comment]
This works.
Going back to WEBSERVER_CLUSTERS=0 also works.

**Comment by mguidon** [comment]
And now removing the ec2 instance also works.

**Comment by sanderegg** [comment]
outdated. closing this
