### ISSUE TITLE
Resource specs for a service are only shown the first time

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

production aws (e.g. osparc.io)

### Current Behavior

When I click on a service I get the resource specs only the first time. Second time displays rubbish. Works again after page reload

![resource_specs_bug](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/6fb52065-f4f7-433d-a6bc-61dba27ae690)

**Comment by odeimaiz** [comment]
Fixed
