### ISSUE TITLE
replace docker-compose 1.29.1 with docker cli and plugin

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#4507]
also upgrade py-yaml with this occasion to the latest version, for details see https://github.com/ITISFoundation/osparc-simcore/pull/4503

**Comment by pcrespov** [comment]
- These are the changes in the dynamic-sidecar at #4503 that should be reverted once this dependency is resolved
    - `pip install` adds `--no-build-isolation` option (notice the `--no-` prefix!!)
    - This was added in both the `pip` at the `Dockerfile` and in the `Makefile` where is passed via ``pip-sync``
