### ISSUE TITLE
dy-sidecar API

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#457]
child of #651

The dy-sidecar shall provide the following API:
- __pull__: download data to dy-service if not already downloaded, shall return success, not necessary or error
- __run__: run the dy-service if possible (notebook may run, modeler probably not)
- __push__: publish generated data from dy-service if new data generated
- __dump__: save the dy-service state
- __load__: reload the dy-service state

**Comment by pcrespov** [comment]
@sanderegg these ideas could be integrated in the new design of sidecar. SEe if you can move them to the new case and close thisone

**Comment by sanderegg** [comment]
see #244
