### ISSUE TITLE
Cluster information display

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4644]
- It sometimes takes 10 seconds to update the view. No big deal though:

![slow_cluster_switch](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/db596c49-11ab-4708-bbef-cd4614a44d5c)

- If I enlarge the view, the content gets resized. Thats weird if I want to see all the clusters

**Comment by sanderegg** [comment]
outdated.
