### ISSUE TITLE
Personalized resources

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4661]
I put RAM above 200 in the db. The settings view shows this:

![image](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/3c118246-95a3-4df9-9fb1-5fc1d060d2b3)

Cannot edit the RAM (probably ok). But I cannot save the cpu changes.

**Comment by odeimaiz** [comment]
@mguidon
The number field requires a maximum, and I guess that what you set in the db was going over the maximum.

 What should be the maximum?

**Comment by mguidon** [comment]
Hmmm 512 GB?
