### ISSUE TITLE
Maintenance: Sync versions of mypy

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Planned changes

Sync `scripts/mypy/requirements.txt` with the versions of `mypy` in `tests.in` and `tools.in`!!

- Since https://github.com/ITISFoundation/osparc-simcore/pull/4749, `mypy` version is around 1.5 while `mypy~=1.2.0` in the `scripts/mypy/requirements.txt`. 
- Why `mypy` is in the requirements/tools/tests listings? 
    -  via sqlalchemy

**Comment by sanderegg** [comment]
mypy cannot stay out of projects requirements.
