### ISSUE TITLE
Flaky: [unit] clusters-keeper  tests/integration/test_clusters.py::test_cluster_scale[local/dask-sidecar:production] - ValueError: Not Found

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4757]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/6187024232/job/16796679843?pr=4747#step:10:142

**Comment by pcrespov** [comment]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/6188541561/job/16800777488#step:8:247

**Comment by sanderegg** [comment]
outdated
