### ISSUE TITLE
Deploy an autoscaling service for s4llife / jupyterlab that uses one of the machine defined for small/medium/large

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4767]
For the initial testing (and maybe launch depending on time), machines needs to be created on EC2 as required when S4llife / Jupyterlabs instances are started.
To this end an additional autoscaling instance must be created in the upcoming ZMT deployement with the a priori following requirements:
- the service name should probably be ```autoscaling-s4llife``` for clarity
- the ENVS variable must be defined on the docker-compose (unless there is a way) directly to not have conflicts with any other?
- it takes the same set of ENVS as autoscaling for s4l-lite deployment
- machine type(s) must be defined (s4l-lite uses g4dn.8xlarge for mulitple instances, if we want only one then resources shall be adjusted such that the service uses something just below the max of the machine)
- max number of instances shall be defined
- buffer machines shall be defined (I would start with 0 until there are complaints)
- for specific labels I would propose:
```
AUTOSCALING_NODES_MONITORING_NODE_LABELS='["dynamicsidecar", "gpu", "io.simcore.s4life-autoscaled-node"]' # defines the labels to check for on the nodes (i.e. ["dynamicsidecar"])
AUTOSCALING_NODES_MONITORING_SERVICE_LABELS='["io.simcore.scalable-s4life"]' # optional defines the label to check for on the monitored services
AUTOSCALING_NODES_MONITORING_NEW_NODES_LABELS=["io.simcore.autoscaled-node"]
```

**Comment by GitHK** [comment]
ideally on AWS staging then we move it to prod ZMT

**Comment by sanderegg** [comment]
implemented via:
https://github.com/ITISFoundation/osparc-simcore/pull/5189
https://github.com/ITISFoundation/osparc-simcore/pull/5196
https://github.com/ITISFoundation/osparc-simcore/pull/5197
