### ISSUE TITLE
Study with legacy interactive services cannot be opened anymore

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#4770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

staging aws (e.g. staging.osparc.io)

### Current Behavior

If I open a study with a legacy service, it stays "Pending" forever.

### Steps To Reproduce

This relies on having an old (=prior to changes to the zipping/storage). In my case is a jupyter-chaste v1.0.1. 

Open this old study, the legacy service stays pending forver

### Anything else?

In Portainer, I found this in the container log:
```
INFO: [run.bash]  Starting container ...
INFO: [run.bash]    Workdir :/home/jovyan/work
INFO: [boot_notebook.bash]  creating inputs/outputs folder
INFO:simcore_sdk.node_data.data_manager:pulling data from 4a02a612-0f38-11ee-bc38-02420a0b01ac/4ac4c35f-f5d4-4b66-be7d-0ce53bac8486/work.zip to /tmp/tmpi83h7egi/work.zip...
Traceback (most recent call last):
    return await _get_link(store_id, file_id, api.download_file)
    resp = await apifct(
    response_data = await self.request(
    return await self.request(
    raise ApiException(http_resp=r)
Reason: The file 4a02a612-0f38-11ee-bc38-02420a0b01ac/4ac4c35f-f5d4-4b66-be7d-0ce53bac8486/work.zip  in staging-simcore was not found
HTTP response body: {"data": null, "error": {"logs": [{"message": "The file 4a02a612-0f38-11ee-bc38-02420a0b01ac/4ac4c35f-f5d4-4b66-be7d-0ce53bac8486/work.zip  in staging-simcore was not found", "level": "ERROR", "logger": "user"}], "errors": [{"code": "HTTPNotFound", "message": "The file 4a02a612-0f38-11ee-bc38-02420a0b01ac/4ac4c35f-f5d4-4b66-be7d-0ce53bac8486/work.zip  in staging-simcore was not found", "resource": null, "field": null}], "status": 404, "message": "The file 4a02a612-0f38-11ee-bc38-02420a0b01ac/4ac4c35f-f5d4-4b66-be7d-0ce53bac8486/work.zip  in staging-simcore was not found"}}
Traceback (most recent call last):
    asyncio.get_event_loop().run_until_complete(
    return future.result()
    await data_manager.pull(path)
    await _pull_file(archive_file)
    downloaded_file = await filemanager.download_file_from_s3(
    download_link = await _get_download_link(store_id, s3_object, api)
    raise exceptions.InvalidDownloadLinkError(None) from err
ERROR:asyncio:Unclosed connector
connector: <aiohttp.connector.TCPConnector object at 0x7f9672e17310>
```

**Comment by elisabettai** [comment]
fyi @GitHK, @sanderegg. Not sure if we should worry a lot, since this is a legacy dynamic service.

**Comment by sanderegg** [comment]
@elisabettai I just tried a jupyter-math:1.6.9 on master without issue. You might have hit a problematic timing on staging AWS?

**Comment by elisabettai** [comment]
Hi @sanderegg, I've just retried on AWS staging with this old jupyter-chaste (v1.0.1) and it is failing in the same way as above. Good that works for you with math on master.

In your case, are you opening an old (=prior to change in storage/rclone) study? What I'm trying to do is opening an old study that I haven't touched before the latest changes.

**Comment by elisabettai** [comment]
It turned out that files in S3 have a delete marker. So they're actually not there anymore, hence the error.
