### ISSUE TITLE
FAILED tests/unit/with_dbs/01/test_director_v2.py::test_update_cluster

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4777]
Might worth having a look at this case

FAILED tests/unit/with_dbs/01/test_director_v2.py::test_update_cluster - hypothesis.errors.Flaky: Hypothesis test_update_cluster(mocked_director_v2=<aioresponses.core.aioresponses object at 0x7fd118996e90>, client=<aiohttp.test_utils.TestClient object at 0x7fd11842f580>, user_id=6312, cluster_id=6890, cluster_patch=ClusterPatch(name='aé\x96æo\x03o\U000d447fx¼\x95', description='aé\x96æo\x03o\U000d447fx¼\x95', type='ON_PREMISE', owner=None, thumbnail=HttpUrl('http://a1.l.q.m1ste9csqcdke.attorney/%255p%09h%5E2%2FfCZ7c//Q#%25', scheme='http', host='A1.L.Q.M1STe9csQCdKe.ATTorneY', tld='ATTorneY', host_type='domain', port='80', path='/%255p%09h%5E2%2FfCZ7c//Q', fragment='%25'), endpoint=None, authentication=None, access_rights={2878: ClusterAccessRights(read=True, write=False, delete=True)})) produces unreliable results: Falsified on the first call but did not on a subsequent one
Falsifying example: test_update_cluster(
    mocked_director_v2=<aioresponses.core.aioresponses object at 0x7fd118996e90>,
    client=<aiohttp.test_utils.TestClient object at 0x7fd11842f580>,
    user_id=6312,
    cluster_id=6890,
    cluster_patch=ClusterPatch(
        name='aé\x96æo\x03o\U000d447fx¼\x95',
        description='aé\x96æo\x03o\U000d447fx¼\x95',
        type=<ClusterTypeInModel.ON_PREMISE: 'ON_PREMISE'>,
        owner=None,
        thumbnail='http://a1.l.q.m1ste9csqcdke.attorney/%255p%09h%5E2%2FfCZ7c//Q#%25',
        endpoint=None,
        authentication=None,
        accessRights={2878: ClusterAccessRights(
             read=True,
             write=False,
             delete=True,
         )},
    ),
)
Unreliable test timings! On an initial run, this test took 253.41ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 3.64 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.

You can reproduce this example by temporarily adding @reproduce_failure('6.84.3', b'AXicjY4tCkJhFETP+Xgi4hMExSDPYPIvi8FgsAhiFPNbgVUsrkJX43oEd+H9ELvDzCl3GG6SWt7ykJec5ZRpZ32TizzlTvqvZKKoVULBMhKuZCQzaclEVjLMN6bSJ7OLtCM/u7Th0Y0HtyYX7u05t+mOPDj+VgLxloNrgA9qTBKT') as a decorator on your test case

**Comment by pcrespov** [comment]
Failed again in https://github.com/ITISFoundation/osparc-simcore/actions/runs/10452391237/job/28940730691?pr=6175#step:11:2664


```
You can reproduce this example by temporarily adding @reproduce_failure('6.91.0', b'AXicJY+xSgJgFIW/79dMzCADnaTBwaEhHJJQ0CHNpgahaBB0cFLIB/AVfJMW8T0kwzl6jqbwiudylsN3LhxNiSQ3IBmhI1VC+qE/WMdfzeEQvyGRvQ7ydOXw1ZFNvvnkvSOn9qNatG7DsS1L3tqO5MVigFm10N7JTGrSl2eZ6HnvQdaylIZ86eXfp6bFVgbyGq3mPp6czVeyCbxyIe+Sl0fpyl1MSCz/jyMOlFMWMg==') as a decorator on your test case
```

**Comment by sanderegg** [comment]
outdated
