### ISSUE TITLE
pytest fixtures for simcore

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#484]
a pytest plugin that adds common fixtures specific to osparc-simcore platform

e.g. devel_environ, services_docker_compose (see web/server/tests/integration-*/conftest.py 

This can be installed in dev requirements of each module

**Comment by sanderegg** [comment]
add to the cookiecutter the test layout of the webserver

**Comment by pcrespov** [comment]
very nicely done by @sanderegg in [server/tests](https://github.com/ITISFoundation/osparc-simcore/tree/master/services/web/server/tests) with ``helpers`` and ``fixtures`` folders
