### ISSUE TITLE
Depending on selected pricing unit/service resources, a subcontainer shall scale to the available resources

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4960]
When a use selects a different TIER, then S4life shall run on a bigger machine.
S4life is made of multiple containers, how they should scale shall be defined and understood in the dynamic scheduler.

**Comment by GitHK** [comment]
@mguidon @sanderegg I'm not aware, is this is stila thing?

**Comment by sanderegg** [comment]
I implemented it some time ago. so the largest service is scaled.
fixed by https://github.com/ITISFoundation/osparc-simcore/pull/5189
