### ISSUE TITLE
Show computational progress in dashboard

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4983]
User story:
- when a user logs in osparc, he/she sees the dashboard with the his/her projects
- the user started some computations last time he/she was logged in
- the user wants to know what is the progress of the computations (i.e. are they still running? in error? completed?)

Background:
- when a project is opened from the GUI, there is a request going to ```/projects/{project_id}:open```,
- in the backend this "connects" the webserver to the RabbitMQ messaging system and tells it to wire all the logs/progress infos received for the ```project_id```,
- these messages are then re-wired to the frontend via websocket (```projectStateUpdated``` and ```nodeUpdated``` websocket event),
- when a computation starts the ```projectStateUpdated``` comes with state ```STARTED```,
- when a computation completes the ```projectStateUpdated``` comes with the final state (```SUCCESS```, ```ERROR```),
- there is currently no global progress

Proposals:
1. show the state somehow in the dashboard directly (for the visible projects)
2. show the state inside the project preview dialog

**Comment by jsaq007** [comment]
Can we close this @sanderegg ?

<img width="1712" alt="Screenshot 2023-12-14 at 23 55 42" src="https://github.com/ITISFoundation/osparc-simcore/assets/903587/48cc8db2-970c-4358-948e-3606783da88b">

**Comment by sanderegg** [comment]
absolutely @jsaq007, it is done.
