### ISSUE TITLE
+ Buttons missing in sim4life.io

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#4987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is currently no + button available:
![image](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/f16f1925-b514-499f-9055-89eda798a7f3)

I guess the frontend is looking for a service called sim4life-dy, while we have sim4life-8-0-0-dy. This would be something that should be configureable at some point.

**Comment by elisabettai** [comment]
What do we do for the release here? Do we change maybe what is hardcoded in qooxdoo and later find a proper solution? I guess @mguidon the "Start Sim4Life" button should start the latest version of the sim4life-8-0-0-dy service.
