### ISSUE TITLE
Cardiac model from Kember (Java code)

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#5]
**User story**

As a **user** I want to create a pipeline consisting of the cardiac model from Kember and a post-processing service that reproduces the plots in the official MVP use case. I am able to edit all necessary input settings directly in the frontend. Optionally, I would like to have the option to choose a compiler and compiler flags in case I want to build the kernel first.

**Definition of done**

 - [x] The model is available in the list of services
- [x] The required pipeline can be created
- [x] The code is containerized as binary and as code only with compilation performed on the fly
- [x] For the second part of the pipeline, either python or octave/matlab will be used
- [x] check if there is a need/possibility to have settings (property window)
- [x] the results of the python postpro script should be mapped as time series to the outputs, such that they can be visualized with the 2d plot service (item was modified)

**Use case**

There is documentation/code example for this case in filesrv. In addition, the full workflow is available on MaG's VM.

**Comment by esraneufeld** [comment]
same comment as for colleen clancy, just this time with java instead of c++

**Comment by sanderegg** [comment]
- [ ] dockerize java code as binary
- [ ] make solver available on osparc platform
- [ ] convert matlab code to python
- [ ] make 2D graph analysis available on platform

**Comment by drniiken** [comment]
REVIEW

SA

* showing the service
* java based solver

* service, viewer

* pipeline starting
* progress bar working

* made faster for demo
* has only internal parameters

* tomorrow:
proactively ask which parameters to wire through

* replaying a matlab project
* do not show some of the heavy ones tomorrow

* nice !
* a raw data toggler
* code of Jupyter script

* now loading original file
* showing the graph from the paper

**Comment by drniiken** [comment]
For the very moment, we are happy with the Jupyter based 2D plot visualization.

**Comment by pcrespov** [comment]
Would it be possible then to close this case and create a smaller one with the remaining issue? The latter could refer as a continuation of this
