### ISSUE TITLE
Sharing a wallet doesn't work

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#5006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

development (master)

### Current Behavior

on s4l-master.speag.com I cannot share my credit account with anybody. When I click on "share" the buttons the loading icon stays there forever.

![image](https://github.com/ITISFoundation/osparc-simcore/assets/18575092/a254748a-cfa6-4084-bf37-52df45a117f1)

### Anything else?

@pcrespov, this is the same thing we observed together 2 days ago. There's no information in the browser developers tools.

**Comment by ignapas** [comment]
Front-end does not seem to make any request after clicking 'Share'. What should be the endpoint for this? @pcrespov

**Comment by pcrespov** [comment]
> Front-end does not seem to make any request after clicking 'Share'. What should be the endpoint for this? @pcrespov

@ignapas AFAIK sharing is fully handled in the front-end. Check with @matusdrobuliak66 about this anyway.
