### ISSUE TITLE
The ISAN Portal (M8; MS11.b,D11.b)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#501]
**Background**
A joint portal for the three COREs will be launched publicly at the ISAN conference in July 19. The main purpose is to make (measurement) data sets public. However, they will also want to make a few models accessible. We still need to discuss with the SPARC management, the form this should take (link to oSPARC with login only accessible to selected users, link to reduced oSPARC with public accessibility, dedicated simple GUI to execute some models such as Clancy). Related to issues #493 and #496.

related documents (evolving)
https://docs.google.com/document/d/1fFM1twvGlQ_-mvBP316aYy3ykE-z4bN9HVohr6SC7kc/edit?usp=sharing (original document from Blackfynn)
https://docs.google.com/document/d/1zBXlho_jSab0YzEE7NxVP1q1JfLlGfySgt4_8U6DMF4/edit?usp=sharing (with our comments)

**Definition of Done**
- [x] tbd

**Comment**
we primarily need a page on which the available models are listed and can be filtered. functionality should be identical to what the dat-core will be building, which will be based on (https://www.gudmap.org/chaise/recordset/#2/Cell_Line:Mouse_Strain@sort(ID)). we probably want to put entries into the dat-core knowledge graphs, that contain links to the models we want to make public, and meta-data information that can then be displayed and searched.
i suggest to reduce implementation effort and maximize usage consistancy, by waiting for the DAT-CORE implementation to progress and then copying it.

**Comment**
after talking to blackfynn:
we will be allowed to duplicate and adapt some of their code to mimick the functionality they are implementing (see https://www.gudmap.org/chaise/recordset/#2/Cell_Line:Mouse_Strain@sort(ID)).
they will store the information about their data in a graph database implemented in Neo4j 
that gets produced automatically out of the published datasets in blackfynn (https://en.wikipedia.org/wiki/Neo4j). we will put entities corresponding to the portal computational models into the blackfynn database, enriched with the metadata we want (which will also be used for searching) and with links to the model in osparc instead of typical data. this will then automatically be mirrored into the Neo4j database and the code blackfynn writes for data searching and displaying based on Neo4j should then easily be adaptable by us for the computational models.

**Comment by esraneufeld** [comment]
comment from joost on slack:

Q: Is https://dev-sparc-portal.sparc.science/ still the actively developing page?
A: Yes, that site is deployed automatically when the master branch of the github repository is updated.
[...]
Development of the portal has halted a bit on our side for the last two weeks as we have focussed on getting the design documents out. However, we are aiming to restart development next week.

**Comment by ignapas** [comment]
* Follow up progress on Blackfynn's side
* Check about the missing metadata fields
