### ISSUE TITLE
UI: pressing buy Credits spins forever and does not call the API

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

development (master)

### Current Behavior

- Payments -> Buy Credits ... spins forever

![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/59b6c1c7-b169-46c4-8946-471f084df728)

![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/525a8fb4-6b8d-4796-bb45-3c86d7820d2a)

The api call is never done. 

### Expected Behavior

It should call `POST /wallets/{wallet_id}/payments`

SEE https://sim4life.io/dev/doc#/wallets/create_payment

### Steps To Reproduce

- Payments -> Buy Credits ... spins forever

### Anything else?

- I wonder whether the reverse commit you did the other day is linked to this since it works in staging (this is master deploy!)
- NOTE: that this is https://sim4life.io !! which corresponds to master. But it should be a similar problem in master

**Comment by elisabettai** [comment]
Closing this one. Buying credits with a test credit card now works. The problem was not purely frontend related. @pcrespov. feel free to add more details for the record if you think that's useful.
