### ISSUE TITLE
REST API w/ Python Client (M10, MS6.1-3,D6.1-3)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#503]
**Background**
Allow oSPARC use through a non-GUI API (scripting, other). This includes creating a REST API as well as a Python client.

**Definition of Done**
Python interface can be used for:
- [ ] authentication
- [ ] load/save project
- [ ] setup pipeline
- [ ] display/export results

**Comment by pcrespov** [comment]
This is a duplicate of osparc-issues#16

**Comment by pcrespov** [comment]
duplicate of ITISFoundation/osparc-issues#16
