### ISSUE TITLE
0 credits: show proper error message when user tries to start a service

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#5038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 
![image](https://github.com/ITISFoundation/osparc-simcore/assets/18575092/1bca3ff1-89b8-41fc-8e4c-95d178f796ee)

In the web developers tool we get, which doesn't sound the right error code.
status: 503, message: "Currently catalog service is unavailable, please try again later

### Expected Behavior

I guess we need a more error message (and code)?

### Steps To Reproduce

Use a wallet where you have 0 credits and try to start a new service.

**Comment by matusdrobuliak66** [comment]
Fixed by some UI changes from frontend guys.
