### ISSUE TITLE
Study cant be opened frontend bug

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#5044]
The study cant be opened from the details view, after upgrading the dynamic services' patch versions. If I go back to the dashboard and try again it works. There are no REST requests sent from the frontend to the server.
![firefox_CFpQx70OWe](https://github.com/ITISFoundation/osparc-simcore/assets/8209087/9096e081-3adf-480b-9226-0c18ed817973)

**Comment by jsaq007** [comment]
I think this is the same as the issue I am working on and should be fixed. There could be an aspect of backend required... but we can finalise it on Monday when I'm in the office

**Comment by jsaq007** [comment]
I believe this is a duplicate issue and has now been resolved in: https://github.com/ITISFoundation/osparc-simcore/pull/5200
Perhaps someone is able to verify this did resolve this issue too?

**Comment by jsaq007** [comment]
This issue should be resolved in https://github.com/ITISFoundation/osparc-simcore/pull/5200. I will close it for the time being.
