### ISSUE TITLE
iSolve Progress

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#5046]
### Current Behavior

Now that I finally start running larger jobs, I see this:
![image](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/7127bc55-403f-4002-8a30-a205f59e7547)

left is the log from a similar run, right is the progress I get back.

For larger jobs, it seems we spend so much time in "Prepare for time update" that we get a progress bar. Since the progress cannot be reset (or go back) the progress remains in 66 % until the main part (Time Update) is larger than that 66 %.

I see several options to fix this. Lets discuss.

**Comment by sanderegg** [comment]
@mguidon this is a non-issue now or isn't it?

**Comment by mguidon** [comment]
Correct. This is solved now. Closing.
