### ISSUE TITLE
Large Models/Results Rendering & Interaction (M9; D4.a)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#505]
**Background**
currently, the loading of large data (for visualization purposes, or for service I/O) can be a critical bottle-neck. Means of acceleration should be investigated (off-line rendering, multi-resolution rendering, parallel storage of reduced resolution models for displaying purposes, parallel data transmission...)
Related to issue #35

- [x] prototype means of high frame-rate screen-capture for offline rendering (implemented on windows and no streaming yet)
- [x] port to linux and add streaming
- [x] prototype means of passing user interactions from the user interface to the service
- [x] implement interactive viewing and modeling based on the two above (related to #xx)
- [x] tbd: merge with paraview-derived ideas for off-screen rendering and multiresolution rendering (paraview permits specifying frame rate, interaction rate, and image compression level)
- [x] deploy
- [ ] technically missing: non-viewers, connection of componnets, color-bar, bugs, off screen performance

**Comment by drniiken** [comment]
Nik & Esra consider to add a checklist with items to fulfill.

**Comment by odeimaiz** [comment]
![image](https://user-images.githubusercontent.com/33152403/53181436-d3e97f00-35f7-11e9-8f3c-5b4fd4676d05.png)

**Comment by esraneufeld** [comment]
prioritized tools:
- import of CAD models (start with open formats - vtk, stl, sat, careful with licenses)
- modeling primitives (incl. splines) - starting with spheres, cylinders, cubes, splines, points, boxes
- boolean
- move
- pick
to be revised.

**Comment by drniiken** [comment]
### **Modeling Operations w/ Priorities**


### **1st Prio**

**CAD/Mesh Import**
- SAT
- IGES, STEP (if possible)
- VTK
- STL, PLY
- additional most urgent, required img data, mesh formats (tbd)

**Primitives**
- Cylinder, Sphere, Block
- Rectangle, Circle, Spline, Lines, Point

**Tools**
- Distance Tool

**Snap**
- basic snapping

**Select**
- select solid, picking

**Solid Dimensions**
- set/adjust solid dimensions via properties

**Move**
- move/translate, rotate
- move from-to
- scale

### **2nd Prio**

**CAD/Mesh Import**
- ProE (if possible)
- required img data, mesh formats (tbd)

**Tools**
- Geometry Measure

**Snap**
- extended snapping
- snapping resolution (linear, angular)

**Select**
- select subpart of solid (face, edge, etc.)

**Move**
- pivot operations

**Boolean**
- Boolean operations

**Modifications**
- cutting, planar

**Extract**
- extract edges and faces, points

**Sweep, Offset**
- basic sweep, offset operations
- sweep along a line, etc.

**Mesh Operations**
- most basic (tbd)

### **3rd Prio**

**Primitives**
- Pyramid, Cone, Tube
- Arc, Polygon

**Tools**
- Place Modeling Grid

**Solid Dimensions**
- set/adjust solid dimensions interactively

**Move**
- mirror, etc.

**Extract**
- extract bounding box

**Sweep, Offset**
- extended sweep/offset operations

**Modifications**
- thickening, etc.
- wire tools

**Mesh Operations**
- extended (tbd)

**Comment by esraneufeld** [comment]
i would like to promote the boolean operations to 1st prio. pretty please

**Comment by drniiken** [comment]
Sure thing ... done.

**Comment by mguidon** [comment]
**Importers**

| filename   | description                   |
|------------|-------------------------------|
| 3di        | Artwork 3Di                   |
| asm        | Pro/ENGINEER                  |
| asm.*      | Pro/ENGINEER                  |
| bndl       | Encrypted Component           |
| catpart    | CATIA V5                      |
| dwg        | DWG                           |
| dxf        | DXF                           |
| ex2        | Exodus II                     |
| exo        | Exodus II                     |
| exp        | CATIA V4                      |
| glb        | glTF                          |
| gltf       | glTF                          |
| iges       | Iges                          |
| igs        | Iges                          |
| model      | CATIA V4                      |
| nas        | Nastran                       |
| obj        | Wavefront OBJ                 |
| ply        | Stanford Polygonal Format PLY |
| prt        | Pro/ENGINEER                  |
| prt.*      | Pro/ENGINEER                  |
| sab        | ACIS SAT                      |
| sat        | ACIS SAT                      |
| sem        | SEMCAD X Model                |
| session    | CATIA V4                      |
| smash      | Recover Model                 |
| step       | Step                          |
| stl        | Stereo Lithography STL        |
| stp        | Step                          |
| txt        | Outline File                  |
| vtk        | Legacy VTK                    |
| vtp        | VTP                           |
| vtu        | VTU                           |

**Exporters**

| filename   | description          |
|------------|----------------------|
| glb        | glTF                 |
| gltf       | glTF                 |
| iges       | Iges                 |
| igs        | Iges                 |
| model      | CATIA V4             |
| obj        | OBJ                  |
| ply        | PLY                  |
| sab        | ACIS SAT             |
| sat        | ACIS SAT             |
| step       | Step                 |
| stl        | STL                  |
| stp        | Step                 |
| vti        | VTK XML Image Format |
| vtk        | VTK                  |
| vtk        | VTK                  |
| vtu        | VTU                  |

**Comment by mguidon** [comment]
**Status Update Brown Islands 20.01.2020**

Done:
- osparc SuperMash linux build integrated in CI

Still to do:
- stand-alone service
- Test latency/bandwith and swithc to video codec if necessary
- ACIS license

**Comment by drniiken** [comment]
The POs would love to see this being embedded into oSPARC - at the end of the coming sprint!
Thank you.
