### ISSUE TITLE
Jupyter Service (M5; MS4.a,D4.b)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#507]
**Background**
The current Jupyter service should be finalized.

**Definition of Done**
- [x] Simplify mapping of input/output ports
- [x] Allow storing service along with python script, state (persistent)

**Comment by drniiken** [comment]
Needs testing and decision if sufficient or needs change.

**Comment by KZzizzle** [comment]
Can I close this as it is a duplicate of #1175?
