### ISSUE TITLE
Frontend does not display error message when too many projects are opened

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#5085]
When study is open the frontend no longer shows any erro when the a study is already opened.

Reply from `POST v0/projects/e131863c-8d02-11ee-818c-02420a0b0331:open`
```json
{
    "data": null,
    "error": {
        "logs": [
            {
                "message": "You cannot open more than 1 study at once. Please close another study and retry.",
                "level": "ERROR",
                "logger": "user"
            }
        ],
        "errors": [
            {
                "code": "HTTPConflict",
                "message": "You cannot open more than 1 study at once. Please close another study and retry.",
                "resource": null,
                "field": null
            }
        ],
        "status": 409,
        "message": "You cannot open more than 1 study at once. Please close another study and retry."
    }
}
```

_Originally posted by @GitHK in https://github.com/ITISFoundation/osparc-simcore/issues/5027#issuecomment-1827399597_

**Comment by elisabettai** [comment]
@GitHK, I am slightly confused here. Where did you see the problem?
On s4l-lite, I tried to open 2 projects at the same time and I got the expected error message
![image](https://github.com/ITISFoundation/osparc-simcore/assets/18575092/8b5711b2-3185-4359-8b4b-81540f92c0a8)

On the other production deployments, users are free to open as many projects as they want.

**Comment by GitHK** [comment]
@elisabettai this is on TIP prod

**Comment by GitHK** [comment]
very good it now works as expected. must have been something during the release.
I also don't see it any longer
