### ISSUE TITLE
Standalone NEURON Service

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#514]
**Background**
Some SPARC teams want to run NEURON [Yale] without connection to EM. In the near future, this concerns the integration of the model from team Bronstein (Case #493).

**Definition of Done**
- [x] the user can provide the .hoc and .mod files. the .mod files are compiled and the simulation is executed using NEURON
- [x] to be seen: what parameters do we need to offer to the user through the GUI (as little as possible initially), what visualization of the network/neurons do we offer (as little as possible initially)
- [x] to be discussed: offer access to Python interface, and possibly even Jupyter integration (check if kernel already exists - https://www.neuron.yale.edu/phpBB/viewtopic.php?t=3858)?

**Comment by mguidon** [comment]
![IMG_20190612_085255.jpg](https://images.zenhubusercontent.com/5caef50eecad11531cc41319/5c0ca3fa-4756-4edd-bd62-851f7387128b)
