### ISSUE TITLE
Automatize Deployment (CI/CD)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#515]
**Background**
Changes to core-platform, dynamic and computational service should trigger a chain of events that automatically deploys updates into the production servers.

**Definition of Done**
- [ ] Procedures for all three services types are documented (branching, build-stages, versioning, images, Go NoGo points for production)
- [ ] Every change in the codebase (github/gitlab/external?) automatically triggers the CI/CD pipeline

**Comment by sanderegg** [comment]
so from now on following happens:

- SIM-Core platform:
  1. automatically built, tested and deployed to dockerhub by [Travis-CI](https://travis-ci.org/ITISFoundation/osparc-simcore)
  2. automatic deployment of platform services onto master, staging and production platforms using the [deployer service](https://github.com/ITISFoundation/osparc-ops)
- 3rd party services in github:
  1. automatically built, tested and deployed to dockerhub by [Travis-CI](https://travis-ci.org/ITISFoundation/osparc-services)
  2. internal gitlab pipeline polls dockerhub and deploys the services to the master/staging platforms if specified in a configuration file
- 3rd party services in gitlab (closed-source):
  1. automatically built, tested and deployed to internal docker registry
  2. automatically deployed to master/staging platforms
