### ISSUE TITLE
The webclient docker image does not fail when the qooxdoo compiler fails to compile the source code

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#519]
If the qooxdoo compiler fails to compile for whatever reason the webclient docker image does not fail compilation. Both production and devel mode.
The problem is only visible by looking at the logs in devel mode.

**Comment by pcrespov** [comment]
Solved with new qooxdoo-kit (see PR ITISFoundation/dockerfiles#10) that is integrated in PR #1055
