### ISSUE TITLE
MESA vs Hardware

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#520]
child of #505
How does this effect the performance for large models
Enable hardware acceleration for paraview.

We want to measure the frame rate that can be achieved for vip model sized datasets.

Do we need to go right away to server side multi resolution models ?

## Definition of Done:
Find limitations of this approach and a demo

**Comment by sanderegg** [comment]
in [sanderegg playground repo](https://github.com/sanderegg/playground) there is a demo to be run on the predator:
```bash
git clone https://github.com/sanderegg/playground.git
cd mesa_vs_hardware
make up
```
to generate latency and/or limit bandwidth call
```bash
# to add latency in ms
make network_latency latency=100
# to limit the bandwidth
make network_limit_bandwidth bandwith=1mbit
# to limit both
make network_very_bad_conditions latency=100 bandwidth=1mbit
# reset
make network_reset
```

**Comment by sanderegg** [comment]
demo done:
need a linux version of modeler to use nvidia backend
