### ISSUE TITLE
NeuronSimulator: From s4l project to service

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#522]
Child of #509
Copy xdlls and pyds into a windows docker image and test if it runs. This guarantees UI independence.

Definition of Done:
1. Run neuron python tutorial in windows/linux docker container.
2. As an outcome have a procedure/workflow to convert other s4l projects into services

**Comment by odeimaiz** [comment]
- [ ] Neuron follows demodularization protocol
- [ ] Can run Neuron from jupyter notebook
- [ ] Compile more modules. Assure S4L Desktop still works. Clone pulse prj for CI
- [ ] Py3 compatible (Step 2')
- [ ] Port to Linux (Step 3) + start linters
- [ ] Frontend logic
  - [ ] Simulator hierarchy = API hierarchy: NeuronSim/Setup, NeuronSim/Neurons
- [ ] Neuron simulator service: aiohttp + service

**Comment by odeimaiz** [comment]
![image](https://user-images.githubusercontent.com/33152403/53181790-8ae5fa80-35f8-11e9-8b52-e4a149546b37.png)

**Comment by mguidon** [comment]
Linux Porting

- [ ] acis
- [ ] boost
- [ ] carve
- [ ] curl
- [ ] dakota
- [ ] docker
- [ ] eigen
- [ ] flexlm
- [ ] freeimage
- [ ] geometrictools
- [ ] glew
- [ ] hdf5
- [ ] icu
- [ ] json
- [ ] minizip
- [ ] mkl
- [ ] netgen
- [ ] neuron
- [ ] numpy
- [ ] process
- [ ] python
- [ ] sqlite3
- [ ] ssh2
- [ ] ssl
- [ ] tbb
- [ ] threadpool
- [ ] thrift
- [ ] vtk
- [ ] zlib

**Comment by mguidon** [comment]
Todos:

- Python modules in linux
- OpenGL context's in linux
- pplx library
- Failing tests in XCoreMath --> Alessandro

**Comment by pcrespov** [comment]
@mguidon @colinRawlings I pass this to you so you can update or close it. Thx!

**Comment by mguidon** [comment]
Feels good to close. We have come a long way.
