### ISSUE TITLE
Frontend disk usage telemetry

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#5260]
The backend has a new telemetry module for the new style dynamic services. Currently the telemetry provides information about disk usage in real time.

In the backend it is possible to enable the telemetry via `enable_telemetry` setting inside `group_extra_propertires`.

Disk usage telemetry is published via socketio as such messages:

```
42["serviceDiskUsage",{"node_id":"7b6605b1-24ed-4e5d-9b55-8ba57a06b801","usage":{"/":{"used":117151211520,"free":882563502080,"total":999714713600,"used_percent":11.72},"/dy-volumes/home/jovyan/work/inputs":{"used":117151211520,"free":882563502080,"total":999714713600,"used_percent":11.72},"/dy-volumes/home/jovyan/work/outputs":{"used":117151211520,"free":882563502080,"total":999714713600,"used_percent":11.72},"/dy-volumes/home/jovyan/work/workspace":{"used":117151211520,"free":882563502080,"total":999714713600,"used_percent":11.72}}}]	1706175494.5952349
```

Each service publishes it's telemetry. There are multiple partitions from where this telemetry is published. On some special deployments, like s4l, these have disk limits, so their totals may vary. On all other deployments they will al be the same as the root "/" partition.

When above is enabled and when the user logs in, a new setting is provided in the preferences:
- `lowDiskSpaceThreshold` an integer default=5 (expressed in GB):  is the amount of disk space under wish if the disk goes the user will receive a warning

### Requests

Minimum:
- a message is displayed when the free disk space goes under `lowDiskSpaceThreshold`
- a message is displayed when the free disk space goes to 0 (zero)

Ideally:
- A disk space indicator should be displayed in the yellow circled area below
![Screenshot 2024-01-22 at 15 28 49](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/2998b0c6-1eba-4843-a60e-c298ea68307e)
- If the disk usage is under the `lowDiskSpaceThreshold ` a warning (maybe yellow) indication should be placed on the service card an in the column to the right (more or less where the yellow cross signs are placed)
![Screenshot 2024-01-22 at 15 30 25](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/1cdd6f5f-f499-4215-a5a4-d534173f24d1)
- similar to what happens above, if you run out of disk space instead an error (maybe red) indication should be placed in the same places

NOTE: since the user or the process can free up disk space, the above warning and error indications should be removed if the disk space is no longer under their respective thresholds

**Comment by mguidon** [comment]
Suggestion for the message:
```
Low Disk Space on "Service Filesystem" for $SERVICE_NAME/$NODE_NAME

The volume Service Filesystem has only 665 MB disk space remaining. You can free up disk space by removing unused files in your service. Alternatively, you can run your service with a pricing plan that supports your storage requirements.
```
Not sure how to name "Service Filesystem".
