### ISSUE TITLE
UI: Improvements on billing center tables

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5284]
![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/0db39cf2-68b5-4dc8-8734-624afe96d03e)

- **Cannot read comment** column! 
   - on hover show entire message?
- Status: button to **filter status** Success/Failed/Pending
- Success in other **color**?
- **Width** of the columns  (e.g. Comments should be larger and invoice should only have space for the icon?
- Fill the **large lower area** in the window with the table?
- Consider adding a **refresh button** in the table to explicitly ask to refresh listing

![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/7248be3f-16dd-4de3-84d1-7cf7017ae447)

**Comment by ignapas** [comment]
* Comment column was made larger... and a native tooltip is shown on hover (hacky: does not work if cell is selected: Qooxdoo intricacies sorry!)
* No need to filter if **Failed** and **Pending** statuses will disappear from the list. Note: front-end filtering is not possible with the current implementation for infinite scrolling, please make this filtering on the DB querying side (or at least before pagination params are calculated)
* Success can then remain white (I would not have changed it anyway...: green is out of the question and blue... then blue, red and is full of un-matching colors, idk...)
* Column width has been adapted
* The table cannot occupy more than its rows but it now goes further down if big enough
* Refresh button added
