### ISSUE TITLE
Flaky: Random failure tests/test_api_schemas_dynamic_sidecar_telemetry.py::test_disk_usage

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5324]
Not the first time I see this one. I wonder if is worth checking in case there is a bug in place :-) thx

![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/5c6932a9-71a3-4e86-9893-a34eeccc9d9f)

More details in https://github.com/ITISFoundation/osparc-simcore/actions/runs/7870983307/job/21473320434#step:8:1743

**Comment by pcrespov** [comment]
Again :-(
https://github.com/ITISFoundation/osparc-simcore/actions/runs/8001443324/job/21852672160?pr=5358#step:8:1743



![Image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/07855f4c-d97f-4712-9b61-8d8a67cb4888)

**Comment by pcrespov** [comment]
And again https://github.com/ITISFoundation/osparc-simcore/actions/runs/8003714266/job/21859612685#step:8:1755

**Comment by GitHK** [comment]
Ohh boy, this is a nasty one. Will check it later/tomorrow

**Comment by pcrespov** [comment]
@GitHK I am mostly worried that it might have an impact on the functionaltiy (i.e. a bug). If the test is not relevant just feel free to remove it :-)

**Comment by matusdrobuliak66** [comment]
22.2.2024 15:30
![image](https://github.com/ITISFoundation/osparc-simcore/assets/60785969/66819aa2-229b-4246-b99e-7e31ada2177f)

**Comment by pcrespov** [comment]
Again https://github.com/ITISFoundation/osparc-simcore/actions/runs/8006056147/job/21867021689#step:8:1755 
(See timestamp)

**Comment by matusdrobuliak66** [comment]
This morning https://github.com/ITISFoundation/osparc-simcore/actions/runs/8015264140/job/21895153684?pr=5363

**Comment by matusdrobuliak66** [comment]
FYI: `pytest.skip` was added for now
