### ISSUE TITLE
Create invoice in pdf and attach to to email

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5327]
- prepare a template with text and data to replace
- use template mechanism in place to render body
- produce html
- convert html to pdf
- add in notification email as attachement
- (extra) consider caching mechanism with TTL (similar to stripe) so we do not have to do so many pdfs

**Comment by matusdrobuliak66** [comment]
Here we start to receive the pdf link and also the invoice_id if we would like to integrate with Stripe https://github.com/ITISFoundation/osparc-simcore/pull/5402

**Comment by matusdrobuliak66** [comment]
For now users can download the invoice anytime from our UI and the link will be valid. https://github.com/ITISFoundation/osparc-simcore/pull/5537
