### ISSUE TITLE
Duration shows wrongly in Usage overview

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-simcore#5383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/ITISFoundation/osparc-simcore/assets/60785969/6cc6d4ee-d82f-4b28-8d8b-15bde86e8d33)

The project runs for 27 hours, but probably the front end ignores the 1 day when it goes over 1 day

**Comment by odeimaiz** [comment]
It was fixed https://github.com/ITISFoundation/osparc-simcore/pull/5329
