### ISSUE TITLE
🚀 [sim4life] Release v1.67.0

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-simcore#5396]
### Release version

1.67.0

### Commit SHA

`bed592156a9e5d8f9bd590fbc67c1ebde904dc7b`

### Previous pre-release

https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Schoggilebe3

### Did the commit CI suceeded?

- [X] The commit CI succeeded.

### Motivation

Release to sim4life.io

### Changes

* https://github.com/ITISFoundation/osparc-simcore/pull/5357 by @elisabettai
* https://github.com/ITISFoundation/osparc-simcore/pull/5361 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5362 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5368 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5366 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5371 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/5374 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5376 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5377 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5379 by @YuryHrytsuk
* https://github.com/ITISFoundation/osparc-simcore/pull/5350 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5378 by @ignapas
* https://github.com/ITISFoundation/osparc-simcore/pull/5352 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5385 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5388 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5389 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5329 by @ignapas
* https://github.com/ITISFoundation/osparc-simcore/pull/5387 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5381 by @jsaq007
* https://github.com/ITISFoundation/osparc-simcore/pull/5399 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5382 by @dependabot
* https://github.com/ITISFoundation/osparc-simcore/pull/5398 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5349 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5405 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5407 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/5406 by @dependabot
* https://github.com/ITISFoundation/osparc-simcore/pull/5392 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5409 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5408 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5411 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/5410 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5386 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5401 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5404 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5414 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5415 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5413 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/5417 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5412 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5309 by @jsaq007
* https://github.com/ITISFoundation/osparc-simcore/pull/5391 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5420 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5425 by @wvangeit
* https://github.com/ITISFoundation/osparc-simcore/pull/5423 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5426 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5421 by @jsaq007
* https://github.com/ITISFoundation/osparc-simcore/pull/5428 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5393 by @jsaq007
* https://github.com/ITISFoundation/osparc-simcore/pull/5430 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5433 by @odeimaiz

### DevOps after:
- [x] merge e2e portainer creds update (https://git.speag.com/oSparc/e2e-ops/-/merge_requests/214)

### Devops check 👷

- [ ] portainer works with new password @YuryHrytsuk 

### Summary 📝

- [x] Prepare release link
```cmd
make release-prod version=<M.m.0>  git_sha=<commit_sha>
```
- [x] Draft [release changelog](https://github.com/ITISFoundation/osparc-simcore/releases)
- [x] Announce maintenance ( ** ANNOUNCE AT LEAST 24 HOURS BEFORE ** )
- redis ``{"start": "2023-03-06T13:00:00.000Z", "end": "2023-03-06T15:00:00.000Z", "reason": "Release <vX.X.0>"}``
    - [ ] aws
    - [ ] dalco
    - [ ] tip
- status page (https://manage.statuspage.io/)
    - [ ] osparc
    - [ ] s4l
- mattermost channels
    - [x] maintenance
    - [ ] power users

### Releasing 🚀

- [ ] Maintenance page up.
```cmd
cd /deployment/production/osparc-ops-environments
make up-maintenance
make down-maintenance
```
- [ ] Release by publishing [draft](https://github.com/ITISFoundation/osparc-simcore/releases)
- [ ] Check release CI
- [ ] Check hanging sidecars. Helper command to run in director-v2 CLI `simcore-service-director-v2 close-and-save-service <uuid>`
- [ ] Check deployed
  - [ ] aws deploy
  - [ ] dalco deploy
  - [ ] tip deploy
- [ ] Check testing endpoint ex. `https://testing.osparc.speag.com/`
- [ ] Delete announcement
- [ ] Check e2e runs
- [ ] Announce
``` md
:tada: https://github.com/ITISFoundation/osparc-simcore/releases/tag/v<M.m.0>
```

**Comment by GitHK** [comment]
Actions to take during release by pr:
- https://github.com/ITISFoundation/osparc-simcore/pull/5361
  - 1. If this command works `curl -v https://storage.sim4life.io:443/v0/ -u admin:${SERVICES_PASSWORD}`; it provides a reply similar to  `{"data": {"name": "simcore_service_storage", "api_version": "0.3.0", "version": "0.3.0"}}`
  - [ ] set the following env var `DIRECTOR_V2_NODE_PORTS_STORAGE_AUTH='{"STORAGE_USERNAME": "admin", "STORAGE_PASSWORD": "__REPALCE_ME__", "STORAGE_HOST": "storage.sim4life.io", "STORAGE_PORT": "443", "STORAGE_SECURE": "1"}'` **NOTE STORAGE_PASSWORD should contain ${SERVICES_PASSWORD} the password in clear text** -> have a look at AWS master fo guidelines
  - [ ] in case it does not work, we need to ask @YuryHrytsuk why the traffic basic auth is not configured in a similar way as it is for AWS master.
- https://github.com/ITISFoundation/osparc-simcore/pull/5352
  - [x] I have rebated and merged the associated [MR](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/415)
  - [ ] check the running out of credits in a deployment and service shutdown

**Comment by matusdrobuliak66** [comment]
Release done 8.3.2024 11:30
