### ISSUE TITLE
Project cannot be saved (project update API call replies with 401 Unauthorised)

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#5400]
## What is happening?

Users visualise a message where the project could not be saved.

## What causes it?

After investigating the issue with @matusdrobuliak66 we have found out that the backend was replying `401 Unauthorised`. We are sure it's the `webserver` since in the response headers we have `aiohttp` as a server.

We could not find any trace of this in the web server logs (log level is warning). Note that no traceback was associated to this.

## Possible causes?

- issue with the webserver code
- the frontend, somehow, is not providing the authentication
- something strips it accidentally?

## Observations

- this does not always happen, so sometimes it works as expected, while other times it breaks

---

![image](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/0c4e9412-ee3d-48ce-82a8-4e788d35ba2f)
![asdas](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/72109add-5716-4234-abcb-64826ef637b9)![image3](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/f9c23513-7830-4d41-815f-a7b192e0d107)
![image4](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/975e2e77-78e5-4671-8875-9691207fecf7)
![image5](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/55f5009a-02dd-45fc-a227-a87efe9495ff)
![image6](https://github.com/ITISFoundation/osparc-simcore/assets/5694077/747ad978-b486-44d8-bb48-0515f964afa4)

**Comment by pcrespov** [comment]
1. 4XX errors (i.e. client errors) are not logged in the backend, therefore it is normal that you find no trace
2. I have seen something similar to your description happening in the e2e. There a group of requests are executed concurrently. The problem is that among those concurrent requests there is a `logout` and therefore some of the requests get randomly responded with a 401.
