### ISSUE TITLE
Inactivity does not work in most scenarios

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#5424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inactivity detection in the footed is used to detect when the user is no longer using the browser and prompt him to take action.

I have tested the following situations:
- windows showing but unfocused: 👍 
- minimised window: 👎 
- window not minimised but hidden behind other windows: 👎 
- tab not focused in the same window: 👎 

### Why is this a bad thing

The situation in which this does not work are those where we really want to shut down the service.

### Proposal solution

Move the detection logic to a webworker.

**Comment by elisabettai** [comment]
HI @GitHK, thanks a lot for testing! Two questions:
1. have you waited some minutes after seeing the inactivity warning message? I've tested the other day and it took some minutes to actually shut down.
2. The scenario I tested was: s4l open in a browser tab, leave it untouched ("unfocused" in your terminology) while working on other browser tabs in the meantime. What case is this for you? The 4-th bullet point?

**Comment by GitHK** [comment]
@elisabettai there are some issues which will be fixed by https://github.com/ITISFoundation/osparc-simcore/pull/5419 and it should expect as behaved. I have documented the changes in the PR

**Comment by elisabettai** [comment]
Ok. In sim4life.io didn't seem pretty buggy to me.

**Comment by GitHK** [comment]
By moving some logic to web worker apparently solves the issue. Here is a list of some combinations I have tried.

Running on macOS.

| Browser | Window State | On Screen | State |
|---|---|---|---|
| Safari | minimized | current screent| ok |
| Safaru | hidden behind othr windoes | current screen| ok |
| Safari | shwoing unfocused | current screent| ok |
| Safari | minimized | secondary screen |  |
