### ISSUE TITLE
🚀 [sim4life] Release v<1.68.0>

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-simcore#5457]
### Release version

1.68.0

### Commit SHA

`d7df63547efcabfe49ce212a7756377c94b5bf1e`

### Previous pre-release

https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Schoggilebe4

### Did the commit CI suceeded?

- [X] The commit CI succeeded.

### Motivation

Production Release v1.68.0

### Changes

* https://github.com/ITISFoundation/osparc-simcore/pull/5434 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5427 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5439 by @jsaq007
* https://github.com/ITISFoundation/osparc-simcore/pull/5333 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5443 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5444 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5432 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5422 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5402 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/5445 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5448 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5442 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5449 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5441 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5455 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5451 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/5460 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5452 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5456 by @jsaq007
* https://github.com/ITISFoundation/osparc-simcore/pull/5464 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/5462 by @jsaq007
* https://github.com/ITISFoundation/osparc-simcore/pull/5467 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/5468 by @odeimaiz

### Summary 📝

- [ ] Prepare release link
```cmd
make release-prod version=<M.m.0>  git_sha=<commit_sha>
```
- [ ] Draft [release changelog](https://github.com/ITISFoundation/osparc-simcore/releases)
- [ ] Announce maintenance ( ** ANNOUNCE AT LEAST 24 HOURS BEFORE ** )
- redis ``{"start": "2023-03-06T13:00:00.000Z", "end": "2023-03-06T15:00:00.000Z", "reason": "Release <vX.X.0>"}``
    - [ ] aws
    - [ ] dalco
    - [ ] tip
- status page (https://manage.statuspage.io/)
    - [ ] osparc
    - [ ] s4l
- mattermost channels
    - [ ] maintenance
    - [ ] power users

### Releasing 🚀

- [ ] Maintenance page up.
```cmd
cd /deployment/production/osparc-ops-environments
make up-maintenance
make down-maintenance
```
- [ ] Release by publishing [draft](https://github.com/ITISFoundation/osparc-simcore/releases)
- [ ] Check release CI
- [ ] Check hanging sidecars. Helper command to run in director-v2 CLI `simcore-service-director-v2 close-and-save-service <uuid>`
- [ ] Check deployed
  - [ ] aws deploy
  - [ ] dalco deploy
  - [ ] tip deploy
- [ ] Check testing endpoint ex. `https://testing.osparc.speag.com/`
- [ ] Delete announcement
- [ ] Check e2e runs
- [ ] Announce
``` md
:tada: https://github.com/ITISFoundation/osparc-simcore/releases/tag/v<M.m.0>
```

**Comment by matusdrobuliak66** [comment]
⚠️  ⚠️  ⚠️ 
- [ ] App Motion Gateway needs to be redeployed
- [ ] `PAYMENTS_GATEWAY_TAX_FEATURE_ENABLED` needs to be enabled
- [ ] `stripe_price_id` and `stripe_tax_rate_id` fields added to the `product_prices` table
- [ ] ADD currently paying users to the `users_pre_registration_details` table
