### ISSUE TITLE
More control over service metadata

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#5476]
### Updated User Story
Expose a ``Show Description only`` flag to the owner(s) in the Service card, it will be stored in the DB (disabled by default).

If the flag is on, the frontend will only display the description to the users (the owner(s) will still see the current UI). If the flag is off we display the current UI.

Regarding ``Resources``:
- If its a list of sub services its always confusing for the user. So maybe show the sum
- In a billable service with pricing units, these numbers might be overwritten, so don't show them
- If vendor Markdown is provided it should go away as well

Current UI:
![image](https://github.com/user-attachments/assets/42fa51fb-47af-4877-b63e-0a8651d46f5b)

### User Story

The owner of the service is currently displayed on the service card (`My Service` or the local-part of the owner's email address): 

![image](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/080a68e8-309b-46d2-807b-ca2a4f13c1e3)

The owner is deduced from the `contact` and `authors` label of the corresponding docker image (first match) in the backend. For commerical products this should be editable. We should not do that via the existing `owner`/`authors` fields because this may have implications on all deploys (e.g. the owner needs an account on all deploys/products, we might mess up existing logic)

Furthermore, the details page looks, eg. like this:

![image](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/c180b430-89dd-41ad-b3fa-ca121b5c8552)

Again, `CONTACT` and `AUTHORS` should be configureable via the database. While we are at it, what about

- Adding more information (CHANGELOG, Release Notes, Support Channels)
- Who cares about the Raw metadata? --> Owner cares. It is a good way to debug
- Resources will anyhow be overwritten via pricing plan in a commercial settings

```[tasklist]
### Eisbock
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6290
```

**Comment by sanderegg** [comment]
About the resources. Please pretty please do not create 2 paths with these. please unify selecting a machine and resources management. especially if we start sharing a machine for multiple services, this is far from being gone for good.
