### ISSUE TITLE
upstream branches to fix master builds

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#551]
new travis build runs ONLY on top of master
If fails, it means that fixes need to be done there
and it pollutes master with faulty commits

Possible solutions:
a) branching into some aux branch to do the fixes and only merge back when ok -> means travis needs to recognize

b) create an intermediary branch before master, e.g. develop. All PR go into develop. Travis master build becomes develop build ...

Check if [this branching strategy](https://nvie.com/posts/a-successful-git-branching-model/) in upstream makes sense for our problem

**Comment by sanderegg** [comment]
some other interesting reads are:
- [against git flow] (https://hackernoon.com/gitflow-is-a-poor-branching-model-hack-d46567a156e7)
- [summary of usual branching strategies](https://medium.com/@patrickporto/4-branching-workflows-for-git-30d0aaee7bf)
- [tools for gitflow](https://github.com/nvie/gitflow)
- [gitlab flow](https://docs.gitlab.com/ee/workflow/gitlab_flow.html#github-flow-as-a-simpler-alternative) - simpler than gitflow?
