### ISSUE TITLE
Strategy: Versioning, Releases

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#56]
**GOAL**
A strategy for versioning and releases is needed.

- [x] release strategy
- [x] versioning strategy
- [x] validation, QA strategy

**Comment by pcrespov** [comment]
@drniiken we have this in place. Should we close this issue?

**Comment by drniiken** [comment]
Dear @pcrespov , yes perfect. Let me close it.
Thanks and best wishes, Nik
