### ISSUE TITLE
✨ Add tip.science nicely styled maintenance page

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#5625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

 Add tip.science nicely styled maintenance page

### Definition of Done

 Added tip.science nicely styled maintenance page
 
 Asked YH if anything needs to be done for what devops call "the independent maintenance page" after the .html-file or styling is done

**Comment by jsaq007** [comment]
First iteration. Feedback welcome :)  

![Image](https://github.com/ITISFoundation/osparc-simcore/assets/903587/f3909852-b695-47df-836a-30d37e38fd4a)
