### ISSUE TITLE
computational scheduler: investigate using row lock mechanism and/or last_updated timestamp on rows to allow several dv-2 to schedule the pipelines

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5631]
If multiple instances of director-v2 are running they should ideally share the load among themselves.

options are:
1. use DB row lock mechanism
2. keep the last_updated_timestamp on rows
3. distribute jobs using a RabbitMQ queue

**Comment by GitHK** [comment]
@sanderegg is this issue still relevant? I see it tracked by the parent case

**Comment by sanderegg** [comment]
replaced by https://github.com/ITISFoundation/osparc-simcore/issues/6666
