### ISSUE TITLE
Change project access rights from JSON to a real table

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5647]
Currently the ```projects``` table contain a JSON row with the projects access rights. This is annoying as it lacks:
- relational DB use (e.g. the group ID can easily go out of sync)
- this is problematic in case of migrating data from one deployment to another
- performance wise poor

One should create a separate table with the ```projects_access_rights```

**Comment by matusdrobuliak66** [comment]
closing https://github.com/ITISFoundation/osparc-simcore/pull/6060
