### ISSUE TITLE
FrontEnd: some probes do not work

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

other (e.g. local)

### Current Behavior

I created this this project that connects all available parameters (inputs) to their corresponding probes (outputs). 
![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/4ea97913-9f5c-4cfe-b307-5345b87c5f6e)

### Expected Behavior

Note that:
 - some probes cannot be added (marked with arrows)
 - there is no automatic matching from parameters to probes of the same type, i.e. selected on parameter's outputs, there is not an automatic matching of their output with the probe's input

### Anything else?

Will provide more feedback on  design in a separate issue

**Comment by odeimaiz** [comment]
Removing the default value in their metadata, will fix them 👍
