### ISSUE TITLE
Front-end API documentation

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#571]
Publish front-end API documentation in Github pages.
Follow Qooxdoo approach

**Comment by oetiker** [comment]
you mean this ? 
https://github.com/qooxdoo/qxl.apiviewer/blob/master/.travis.yml

**Comment by odeimaiz** [comment]
I had this in mind:
https://github.com/qooxdoo/qooxdoo.github.io

But in the end what I would like to replicate is the API viewer

**Comment by oetiker** [comment]
look at the link I provided ... this is doing what you want ... the api viewer has recently been extracted into a contrib ... so now you should be able to follow the instructions here https://github.com/qooxdoo/qxl.apiviewer

**Comment by odeimaiz** [comment]
Thanks @oetiker. Yes that's exactly what we need and after playing around with it, I also realized that the compiler version we use at the moment is not creating the api-viewer output. I will check what compiler-sdk combination works.

**Comment by oetiker** [comment]
or upgrade the compiler ... lots of good things have happened ... I was planning on creating a PR for this this week anyway
