### ISSUE TITLE
Bad gateway errors from api server, very common at the moment

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore#5715]
I'm now very often getting a 502 Bad Gateway error. I don't think i saw this before. This happened after testing if we still get the old 404 error issue. 

![Screenshot 2024-04-23 at 13 36 12](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/80bc062c-5fe0-48b1-a605-b965dafee031)

As can be seen, these even happens after the scripts retries 5 times to create a job.
```[tasklist]
### Tasks
```

**Comment by wvangeit** [comment]
Chance of this happening seems to be 20% or so, on 100 parallel runs.

**Comment by bisgaard-itis** [comment]
> FYI, @bisgaard-itis . Any chance this is related to your fix in some way? (This is on the osparc-master that contains the fix)

It is definitely in the same endpoint. So I suspect this could be related. Do you by any chance have a script I could use to reproduce?
Did you by any chance check what's going on with the Webserver's OEC?

**Comment by wvangeit** [comment]
@bisgaard-itis I'm always using this script: https://github.com/wvangeit/osparc-pyapi-tests/blob/master/noninter1/README.md
I now added a 'make parallel' target for that script. Need to have the linux 'parallel' command installed for that etc.

**Comment by bisgaard-itis** [comment]
> I checked graylog, couldn't find the error, but i always could be doing something wrong

I also checked graylog and I also don't see the error. You are using https://osparc-master.speag.com/, right?

**Comment by wvangeit** [comment]
> > I checked graylog, couldn't find the error, but i always could be doing something wrong
> 
> I also checked graylog and I also don't see the error. You are using https://osparc-master.speag.com/, right?

Yep

**Comment by wvangeit** [comment]
I actually just found 1 OEC:
![Screenshot 2024-04-23 at 13 49 25](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/1a7532fc-5541-4668-acd4-aa045519faa7)

**Comment by wvangeit** [comment]
Looked at this with @bisgaard-itis 
It seems the error rate can be lowered when scaling up the storage server to 5 instances.

There is a variant of this error, that doesn't happen during job creation, but job start. The latter seems to persist after the storage server increase.

![Screenshot 2024-04-23 at 14 12 32](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/de4b5ee0-6836-4763-b7b5-7204eb5ac874)

**Comment by wvangeit** [comment]
@bisgaard-itis 
I added some extra retries and waiting times, but then I got hit by:
![Screenshot 2024-04-23 at 16 10 59](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/55edeee7-9439-431b-ba74-b983343fd36c)

**Comment by wvangeit** [comment]
Is there a way we can really debug if this an overload? Or something else? I'm still a bit suspicious it happens so often atm

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis I added some extra retries and waiting times, but then I got hit by: ![Screenshot 2024-04-23 at 16 10 59](https://private-user-images.githubusercontent.com/3098670/324868718-55edeee7-9439-431b-ba74-b983343fd36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODIzODQsIm5iZiI6MTcxMzg4MjA4NCwicGF0aCI6Ii8zMDk4NjcwLzMyNDg2ODcxOC01NWVkZWVlNy05NDM5LTQzMWItYmE3NC1iOTgzMzQzZmQzNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTQyMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQzZjkwOGRhOTVmZmI4MzE0NzhmNTJkOTFkMzg3N2E0Y2IxNjg3OGUzMGJhZTM1MTRkYTQ1ZWE3NDI5ZjAzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o3P-WxG_ZutRtgIHGtycL0p7IiDvbVdUwqLVngJMHeE)

Just to be sure we are on the same page: This error message comes from the client. It comes from the automatic retry policy built into the `osparc_client` package. Now, to figure out why the api-server is returning 502s I would have to look into the logs of the api-server. Perhaps one of the backend services need to be restarted. I can take a look. This is still on master, right?

**Comment by bisgaard-itis** [comment]
> Yep, osparc-master. From the client indeed, i also had enabled the retry option on the 502 errors in the api client config.
> 
> And FYI, this doesn't just happen once, but many time, something like 30% of the 100 requests.

All exception level log messaged I can see in the api server (and there are quite a lot of them) come from the fact that either the webserver or storage times out. But this should be solvable by scaling up. I will request from ops that we scale up these two guys in the next couple of days for testing.

**Comment by wvangeit** [comment]
FYI, I realized that this error in a sense is actually more common than seen above. My parallels script was limiting the number of workers to the number of cores on my machine, i.e. 32. When putting the parallel workers to 100, the issue gets amplified even more (which was to be expected I guess)

**Comment by sanderegg** [comment]
I quickly discussed with @pcrespov this issue so I am not sure I get everything correctly, but some facts:
- @matusdrobuliak66 showed me that storage was using a lot of CPU, but also that the DB behind was heavily used with some search calls (calls that I know are coming straight from the api-server) and that might be pretty costly if it is searching through the database a lot, so there might be leeway there to improve the code (I am not sure why there is a search call everytime),
- scaling the storage service is one option, but if there is a bad call that costs a lot going on, scaling storage will only make matters worse on the database side, I think scaling is important but if we are making calls that destroy the DB times the number of instances of storage, then it's very bad too,
- @wvangeit are you running this on AWS-master or internal master? In both case there are limitations, and I am not sure whether I understand the implications of your number of workers. 
  - for example on internal master the dask-sidecar only have so much CPUs/RAM available, so depending on what you try to run, the services will have to wait until there is enough resources to run (I can show you how much CPUs/RAM there is, and how to check your service needs),
  - on AWS-master, you are anyway limited to 5 machines = 5 jobs at a time, there is currently no machine/job sharing in the billable model at the moment,

**Comment by pcrespov** [comment]
well, i would not say "quickly"  ;-)

**Comment by wvangeit** [comment]
@sanderegg these are results of a test script that i'm using to mimick the map service. A 'worker' in this case a parallel process started by the GNU parallel command, in the latter part of the ticket it's starting 100 of these processes. Each process uses the osparc python api client to: upload two files, create a job from a study, start the study, inspect the study, delete the study when it finishes, and download the outputs. 

The study running is a single python runner that runs a simple python script that reads the input json file data, and dumps that same data in a json output file.

For this particular ticket I think i was mostly running on in-house master. The parent ticket has related issues running on aws-master and in-house master.

Wrt to resources, I'm not 100% convinced about hard limitations I'm hitting on inhouse-master. It's been going up and down when new issues got fixed. But there were times, especially at the start of this entire exercise days ago, that i could run these jobs with a 100% success rate, from time to time.

**Comment by pcrespov** [comment]
Notes from the discussion with @bisgaard-itis 
- storage is overloaded and different clients in the chain timeout i.e. webserver client in the api-server and storage client in webserver.
- Why it times out ???
- ACTION: need a mechanism to detect that a service is overloaded. This information should be fed back to the orchestrator that should react re-scaling the affected service/s (i.e. increase replicas/ computers)
	- e.g. detect drag in event-loop with an asyncio.sleep 
	- e.g. detect request
	- CPU
	- feedback mechanism that speaks to the swarm and ask to increase/decrease services
- rate limiting
	- per user
	- global
- cancellation chain

**Comment by pcrespov** [comment]
SEE why 502 reading the definition here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

**Comment by bisgaard-itis** [comment]
Currently it seems most/all 502 arrise from https://github.com/ITISFoundation/osparc-simcore/issues/5803, so I close this issue.
