### ISSUE TITLE
Move client_qx Dockerfile to itisfoundation/dockerfile

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#572]
- itisfoundation/osparc-simcore:services/web/client/Dockerfile is a **build** container used to compile and serve qx application/documentation and tests
- [x] Tooling repos need to be moved to itisfoundation/dockerfiles repo

@ignapas:
- [x] Compile client with [qooxdoo-kit](https://github.com/ITISFoundation/dockerfiles/tree/master/qooxdoo-kit)
- [x] Adapt [services docker-files](services) (i.e. remove ``webclient``) and  main [Makefile](Makefile)
- [x] Remove all docker related infrastructure under [services/web/client/Dockerfile](services/web/client/Dockerfile)

**Tips:**
``make build`` could pull [qooxdoo-kit](https://github.com/ITISFoundation/dockerfiles/tree/master/qooxdoo-kit) image from dockerhub registry and compile the client. See detailed explanation in services/web/client/README.md and probably look at #546, since it is related.

**Comment by oetiker** [comment]
qooxdoo kit v1 is merged. needs to be integrated into main build process now

**Comment by pcrespov** [comment]
Implementing this issue this case should solve issues #519 and #527! Please check after closing this case !
