### ISSUE TITLE
File uploads have a low likelihood to get stuck for a long time (forever?)

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore#5724]
When running the script 
https://github.com/wvangeit/osparc-pyapi-tests/blob/4730bc351d920fb69127bb94b377f08585d2c859/noninter1/run_study.py#L47
many times in parallel. It gets sometimes (<1%) stuck at the line in the link, or in the lines below that upload another file.
It gets stuck for at least 5 minutes, I never saw it return.

This happens both on osparc-master and aws master deployments

**Comment by wvangeit** [comment]
@pcrespov assigning to you, just so that you are aware

**Comment by pcrespov** [comment]
> @pcrespov assigning to you, just so that you are aware
this is still in master deploy, right?

**Comment by wvangeit** [comment]
Sorry, forgot to mention. I definitely saw it in osparc-master.
Am testing atm aws-master, i also saw that one hanging earlier, but am confirming that it is at the same lines.

**Comment by wvangeit** [comment]
Ok, it's also happening on aws-master. I have updated the ticket.

**Comment by pcrespov** [comment]
> Sorry, forgot to mention. I definitely saw it in osparc-master. Am testing atm aws-master, i also saw that one hanging earlier, but am confirming if it is at the same lines.

Can you please add some info that might help e.g. timestamps of the tests? logs ... 
This way i can check e.g. in graylog around that time.

**Comment by wvangeit** [comment]
> @wvangeit I assume you have set the dev env-var, right? In that case it would be interesting to see where it gets stuck inside that `upload_file` method. I am suspecting it could be when requesting the upload links because I remember experiencing such requests timing out when running a lot of jobs in parallel using one of Taylor's studies at some point.

Yes, I'm setting dev env-var. I'll see how I could see where the script is, might be a bit tricky in parallels. Will see if I can attach some debugger.

**Comment by wvangeit** [comment]
> > Sorry, forgot to mention. I definitely saw it in osparc-master. Am testing atm aws-master, i also saw that one hanging earlier, but am confirming if it is at the same lines.
> 
> @wvangeit Can you please add some info that might help e.g. timestamps of the tests? logs ... This way i can check e.g. in graylog, e2e-ci, etc around that time. Note that sometimes these deploys are also down without notice

Ok, yeah, i will take a screenshot next time of the hanging task, so that you have the timestamp of around what time it happens. Not sure I can give an project ids etc, because this is before the template is cloned.

**Comment by wvangeit** [comment]
![Screenshot 2024-04-24 at 16 05 57](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/089d5345-68ec-46b4-8aba-49cf41f5d00a)

This is a screenshot of hanging file upload @pcrespov (timestap is in the filename: Screenshot 2024-04-24 at 16 05 57)

**Comment by wvangeit** [comment]
It looks like this may have been caused by using the older API (osparc.api.FilesAPI).

![Screenshot 2024-04-24 at 16 32 52](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/335cdc8c-6a21-40df-ac1d-5c732d187e0b)

**Comment by bisgaard-itis** [comment]
Since the demo now runs through (albeit still with some errors) I close this.
