### ISSUE TITLE
UI/UX redesign

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#573]
Ideas and examples on how to improve the user experience
- [ ] Can we change this:

**Comment by ignapas** [comment]
Login form/forms in general: Yellow background inputs with square corners and no padding could be improved? I also like loading spinners on submit buttons. Maybe something like this would be cooler? https://cdn4.vectorstock.com/i/1000x1000/14/78/dark-black-login-form-design-with-creative-ui-vector-14301478.jpg

**Comment by odeimaiz** [comment]
![image](https://user-images.githubusercontent.com/33152403/55004706-fac21900-4fda-11e9-87fe-f7f3d094a7e0.png)

**Comment by pcrespov** [comment]
## New project on a single click

 - one click and new project (with all defaults) is created

We have:
![osparc-new-project](https://user-images.githubusercontent.com/32402063/55245160-e3856480-5242-11e9-8d6b-3c3d1aabf68b.gif)

I wish:
![google-new-project](https://user-images.githubusercontent.com/32402063/55245173-ea13dc00-5242-11e9-8380-ec6b08676dd9.gif)
