### ISSUE TITLE
Integration of 3rdParty computational services

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#574]
Kember, Clancy, Bornstein, Ward and Arya as use case to deduce workflows on how to integrate 3rd party services. CI/CD that gets these services into the framework

This should serve as a base to understand how to integrate supermash and s4l  (use ideas implemented in presentation of Clancy)

child of #515

**Comment by pcrespov** [comment]
- @oetiker proposed to provide the client a script that checks its services against the osparc-simcore framework. This script can be run on the client's CI (eg. travis) and he can independently check the compatibility against our platform

**Comment by odeimaiz** [comment]
![image](https://user-images.githubusercontent.com/33152403/53181617-317dcb80-35f8-11e9-953c-e3d32eb42e98.png)

**Comment by sanderegg** [comment]
- [x] [cookiecutter repo](https://github.com/ITISFoundation/cookiecutter-osparc-service) created that allows quick creation of new computational services :
    - base folder structure
    - docker runs in standard user mode (new)
    - creation of valid labels for the docker image
    - automatic creation of tests to test docker image labels, functionality
    - CI stub to be used in gitlab-CI
    - kember solver migrated, ucdavis singlecell migrated, ucdavis 1D 90% migrated
- [x] gitlab-CI first implementation, that is able to automatically push to a defined registry.

TODO:
- [ ] complete migration of computational services (1D, 2D UCDavis, Matlab, ...)
- [ ] use internal registry
- [ ] gitlab flow (master, production)
- [ ] dynamic services

**Comment by sanderegg** [comment]
status:
- [x] migrated UCDavis services
- [x] migrated Kember service
- [x] added mithra service
- [ ] gitlab flow to be tested

**Comment by sanderegg** [comment]
completed in internal gitlab
