### ISSUE TITLE
computational services shall not start if required input missing

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5820]
- needs https://github.com/ITISFoundation/osparc-issues/issues/1436
Once required inputs are defined as necessary, then computational services shall not be starteable unless the inputs are available

**Comment by sanderegg** [comment]
@odeimaiz @GitHK is this really a needed feature for computational services w.r.t TIP v3?

**Comment by odeimaiz** [comment]
Nope. In the pipeline we only have dynamic services exposed 👍

**Comment by sanderegg** [comment]
not necessary for now. closing.
