### ISSUE TITLE
Use S3 Endpoint

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-simcore#5865]
## Concept
Currently, we talk to S3 via the internet. We should use the S3 Endpoint which will talk directly within AWS network and without costs if it is in the same region & load balancing cost should decrease
- https://tomgregory.com/aws/when-to-use-an-aws-s3-vpc-endpoint/
- https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html
 
```[tasklist]
### Tasks
- [ ] Use S3 private VPC Endpoint to download solver results from comp jobs into rocket PCR
```

**Comment by mrnicegyu11** [comment]
On 27. Sept. 2024: Enabled AWS VPC S3 Gateway Endpoint for osparc-master-zmt.click via the AWS console (no terraform) in us-east-1

**Comment by pcrespov** [comment]
@YuryHrytsuk @mrnicegyu11 Could you please include here (or a link to it) some evidence (e.g., plots or metrics) that quantifies the extent of the improvement? This can be used for the review meeting. thx

**Comment by mrnicegyu11** [comment]
[DirtyS3APIBenchmark-Copy1.zip](https://github.com/user-attachments/files/17489714/DirtyS3APIBenchmark-Copy1.zip)
We have done cost and usage tests using the `S3 VPC Gateway Endpoint` cloud infrastructure, as also proposed by AWS Solution Architects in our in-person meeting. This comment is only concerned with evaluating whether the usage of the S3 Endpoint will lead to increased pulling/pushing speeds.

To test this, we have enabled the `S3 VPC Gateway Endpoint` on aws-master, and test for potential speedups w.r.t. osparc-staging.io, that does not have the S3 Endpoint activated. The test is done using the osparc public python API client to download and upload files via osparc. The testcode is executed inside a jupyter-math on the respective osparc platforms.

The jupyter notebook code executed is attached to this comment.

In our tests we see no speedup of aws-master w.r.t. osparc-staging.io. 


`time to upload&download a 256MB file, 10 attempts, time in seconds - osparc-staging.io`:
![Image](https://github.com/user-attachments/assets/5999d32c-6499-44c5-a3ec-23b080c3ea98)


`time to upload&download a 256MB file, 10 attempts, time in seconds - aws-master`:
![Image](https://github.com/user-attachments/assets/dce523e1-ecc1-4c14-a1f6-469259d77eaf)


@mguidon FYI

**Comment by mguidon** [comment]
Also, @mrnicegyu11 On what ec2 instance type have you been running those tests?

**Comment by mguidon** [comment]
@mrnicegyu11 Can this be closed?

**Comment by mrnicegyu11** [comment]
Yes this can be considered done, thx
