### ISSUE TITLE
Connections between computational services disappear when closing study and reopening it while comp service is running

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore#5896]
This issue is not 100% guaranteed to happen, but has a high likelihood

I have a study with exclusively computational services. Sometimes, while one of the services is running, and I go back to the dashboard, and come back to the same study (even in the same tab / relatively quickly), the computational service is still running, but 'all' the connections between services became dashed, and all have to be reconnected by hand.

This is a screenshot of the study after being reopened. Right before I left the study, all the arrows were full blue without the dash, and the pipeline ran correctly:
![Screenshot 2024-05-30 at 13 03 39](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/a867f513-b19f-472d-96fc-7bb17d145325)

(don't mind the grey-dashed connections, these are still underdevelopment)

The time:
![Screenshot 2024-05-30 at 13 03 54](https://github.com/ITISFoundation/osparc-simcore/assets/3098670/d105955f-8754-4f42-b3a5-b5ab68f89776)

deployment: osparc.io
project id: b9f0e9d4-18e2-11ef-a423-0242ac17192a

**Comment by wvangeit** [comment]
FYI @pcrespov @elisabettai 
What do you think, is this most likely frontend? (Assign to Odei maybe?)

**Comment by wvangeit** [comment]
I noticed that when this happens, it's while some services are running.
At least once, I managed to get the full arrows back by waiting for all services to end, and then to reload the study from the dashboard

**Comment by odeimaiz** [comment]
Fixed here
https://github.com/ITISFoundation/osparc-simcore/pull/6259
