### ISSUE TITLE
Pass oSparc API necessary environment to all services

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5925]
After some testing the passing of the parent Study ID and Node ID automatically via the osparc client works.

Now the question is:
- can we make the setting of the OSPARC_API_KEY,_SECRET, OSPARC_STUDY_ID, OSPARC_NODE_ID available to all dynamic services? or is there something against that?

Let's discuss first and then take actions.

**Comment by bisgaard-itis** [comment]
It would be nice to expose these as `readonly` variables, which should be possible via the bash `readonly` command. That would prevent users from changing them
```bash
╭─mads@bisgaard-wkst ~/Development/oSparc/osparc-pyapi-tests/noninter1 ‹master → origin {1} U:1 ?:4 ✗›
╰─$ help readonly
readonly: readonly [-aAf] [name[=value] ...] or readonly -p
    Mark shell variables as unchangeable.
    
    Mark each NAME as read-only; the values of these NAMEs may not be
    changed by subsequent assignment.  If VALUE is supplied, assign VALUE
    before marking as read-only.
    
    Options:
      -a	refer to indexed array variables
      -A	refer to associative array variables
      -f	refer to shell functions
      -p	display a list of all readonly variables or functions,
    		depending on whether or not the -f option is given
    
    An argument of `--' disables further option processing.
    
    Exit Status:
    Returns success unless an invalid option is given or NAME is invalid.
```

**Comment by pcrespov** [comment]
> It would be nice to expose these as `readonly` variables, which should be possible via the bash `readonly` command. That would prevent users from changing them
> 
> ╭─mads@bisgaard-wkst ~/Development/oSparc/osparc-pyapi-tests/noninter1 ‹master → origin {1} U:1 ?:4 ✗›
> ╰─$ help readonly
> readonly: readonly [-aAf] [name[=value] ...] or readonly -p
>     Mark shell variables as unchangeable.
>     
>     Mark each NAME as read-only; the values of these NAMEs may not be
>     changed by subsequent assignment.  If VALUE is supplied, assign VALUE
>     before marking as read-only.
>     
>     Options:
>       -a	refer to indexed array variables
>       -A	refer to associative array variables
>       -f	refer to shell functions
>       -p	display a list of all readonly variables or functions,
>     		depending on whether or not the -f option is given
>     
>     An argument of `--' disables further option processing.
>     
>     Exit Status:
>     Returns success unless an invalid option is given or NAME is invalid.
> Not sure this can be propagated through docker though. To be checked...

Apparently `environments` in the compose-specs do not support that. An alternative would be to use secrets or mount a read-only file that explicitly callse `readonly` on this file in the CMD  or ENTRYPOINT
