### ISSUE TITLE
Remember me

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#593]
Implement a "remember me" login option.

Front end
* A checkbox is added to the login form
* The value (true/false) of the checkbox is sent to the server together with the login credentials.

Backend
* Depending on the value of *rememberMe*
  * FALSE - The cookie that stores the session token doesn't have an expiration date. This way, it gets deleted when the browser is closed.
  * TRUE - Sets an expiration date for the cookie. That will define the duration of the session, as the cookie will persist between browser sessions.

**Comment by pcrespov** [comment]
wont do
