### ISSUE TITLE
Expose ​/v0​/credits-price from webserver to api-server for tip.science

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-simcore#5943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

I would like to be able to automatically calculate the cost of a personalization run and display it to the users of tip.science. I can display the credits but I would like to also convert it into the cost in dollars to make it more intuitive for users. Since the conversion rate could be changed down the line, I would like to access it via the API.
![image](https://github.com/ITISFoundation/osparc-simcore/assets/61539759/c0cd40fa-132a-45d4-9fa1-76308eac87ba)

### Definition of Done

Credits-price is accessible via the api.

**Comment by bisgaard-itis** [comment]
@Konohana0608 is it not the `currentCostPerUnit` here which you need?

![image](https://github.com/ITISFoundation/osparc-simcore/assets/126242332/96261f02-01d7-44c3-a00f-068c7c61e72c)

This is a screen shot of the api-server api
