### ISSUE TITLE
Load test api-server

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-simcore#5953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Planned changes

While doing metamodeling we have seen that the osparc deployments can get overloaded. In particular `storage` comes under pressure when cloning projects. Hence we should load test api-server endpoints. The requirements are:

- It should be easy to change the number of calls done to individual endpoints.
- It should be easy to change deployments which are tested.
- It should run in the CI

One option is to use https://github.com/wvangeit/osparc-pyapi-tests another option is to use https://github.com/itisfoundation/osparc-simcore/blob/90910149193a84c6716c615ebf2ae07e9e06c7fc/tests/performance

**Comment by pcrespov** [comment]
- what about using locust in https://github.com/itisfoundation/osparc-simcore/blob/90910149193a84c6716c615ebf2ae07e9e06c7fc/tests/performance

**Comment by bisgaard-itis** [comment]
> * what about using locust in https://github.com/itisfoundation/osparc-simcore/blob/90910149193a84c6716c615ebf2ae07e9e06c7fc/tests/performance

Yep, that was the second option which was supposed to be mentioned in the description, but I can see I forgot to add the link. That's done now. Thanks

**Comment by bisgaard-itis** [comment]
This was resolved by adding the load test here: https://github.com/ITISFoundation/osparc-simcore/pull/6014
