### ISSUE TITLE
docker registry @z43 for internal images

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#597]
A docker registry equivalent to dockerhub to store only accessible @z43
 - propietary service images
 - tooling images

Access and maintenance (e.g. backup) should be analogous to git repos

**Comment by sanderegg** [comment]
Have a look at Gitlab, it seems it provides a docker registry service for its CI/CD so maybe we could make use of that.

**Comment by pcrespov** [comment]
@oetiker would it be possible to have a summary (at gitlab internal repo) of the links to running services. Kind of what is there? where to find it? E.g. portainer, docker, devpi, portus ... ???
Thx!

**Comment by pcrespov** [comment]
@sanderegg you were using this repo ... should we close this case? can you also comment on my request above? THX

**Comment by sanderegg** [comment]
So, the following was setup by @oetiker :
- docker registry is available at registry.speag.com through portus
- you can log in as usual
- is backed up internally
