### ISSUE TITLE
Postgres DB: migration and backup

### ISSUE THREAD

**Issue by ehzastrow** [ITISFoundation/osparc-simcore#60]
- [x] Set up storage for Postgres database
 - [x] Persist database from Postgres container on node (beyond life of the container)
 - [x] Backup database data (beyond life of cluster)
- [x] handle migration of database structure

**Comment by ignapas** [comment]
DB migration tool: http://www.liquibase.org/

**Comment by sanderegg** [comment]
play with ZFS for snapshots

**Comment by mguidon** [comment]
Check with Tobi if snapshots are already being created.
