### ISSUE TITLE
Flaky test_workflow_with_outages_in_process_running_deferred_manager

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#6041]
Randomly fails (happened to me a couple of times so far)

<img width="1063" alt="image" src="https://github.com/ITISFoundation/osparc-simcore/assets/32402063/5d5a6664-3592-4d11-9167-c999525f50fc">

SEE https://github.com/ITISFoundation/osparc-simcore/actions/runs/9856902402/job/27215175446?pr=6027#step:10:2303

**Comment by GitHK** [comment]
I think this was addressed, costing as I have not seen it lately
