### ISSUE TITLE
Metrics for startup and shutdown of services

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#6095]
As a platform maintainer I would like to be able to reply to the following questions more easily:
- how much does it take for services to start or stop
- Are they slower than yesterday?

For these purposes I would like to have some metrics at my disposal, possibly a Grafana dashboard
```[tasklist]
### Tasks
- [x] Create metrics @GitHK
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6416
```

**Comment by sanderegg** [comment]
completed. new issues will be opened for new needs.
