### ISSUE TITLE
frontend testing fails in master

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#614]
front-end testing fails in master build. The originating PR does not have any changes in web-client and the test does not find qx built code in ``web/client/build-output``

https://travis-ci.org/ITISFoundation/osparc-simcore/jobs/500629766#L270

See ``$(CLIENT_WEB_OUTPUT)`` target in ``Makefile`` as a possible way to solve it.

**Comment by sanderegg** [comment]
fixed with #713 
travis only deploys the frontend if running on ITISFoundation github repo
