### ISSUE TITLE
Director fails while retrieving services

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#616]
``aiohttp.web_exceptions.HTTPInternalServerError: Expecting property name enclosed in double quotes: line 1 column 112 (char 111)``

**Comment by ignapas** [comment]
```
Traceback (most recent call last):
  File "/devel/services/director/src/simcore_service_director/rest/generated_code/routing.py", line 29, in __handle_errors
    response = await handler(request)
  File "/home/scu/.local/lib/python3.6/site-packages/aiohttp_apiset/swagger/route.py", line 90, in handler
    response = await self._handler(**parameters)
  File "/devel/services/director/src/simcore_service_director/rest/handlers.py", line 40, in services_get
    raise web_exceptions.HTTPInternalServerError(reason=str(err))
aiohttp.web_exceptions.HTTPInternalServerError: Expecting property name enclosed in double quotes: line 1 column 112 (char 111)
INFO:aiohttp.access-477: 10.0.0.4 [04/Mar/2019:10:09:49 +0000] "GET /v0/services HTTP/1.1" 500 374 "-" "Python/3.6 aiohttp/3.3.2"
DEBUG:simcore_service_director.rest.handlers-28: Client does services_get request <Request GET /v0/services > with service_type None
```

**Comment by ignapas** [comment]
![Screenshot from 2019-03-04 11-32-14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c66dbab31df0f0013af7b7b/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f3783dd5b768ee1336525d424fa853444d04bea6d37ef5f22e7a985959ee806c5925c33b11fdbb8a1dbf01bb748a1e87bfe9895edcfa7f74b9dfd0126754505a9bf54f34a8934acd5df74de84853a413336ae4647b.png)

**Comment by sanderegg** [comment]
This issue happens when the docker image of a service has badly formatted json.
In that case one of the raw-graphs services had some missing } or similar, thus the json.loads throws an exception which is not catched.

- [ ] create a test for this case
- [ ] if json.loads throws skip the bad service and log an error so it's traceable

**Comment by pcrespov** [comment]
use ``json.safe_load`` !
