### ISSUE TITLE
Use deterministic zipping for inputs/outputs folders

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#6244]
Reference: https://github.com/ITISFoundation/osparc-issues/issues/1619

As discussed in above issue, using deterministic zipping would ensure the SHA of the resulting zipping of a folder does not change with the timings.

- [x] ~~try to use the solution proposed in https://zerostride.medium.com/building-deterministic-zip-files-with-built-in-commands-741275116a19~~ there is a similar solution in python which works https://github.com/drivendataorg/repro-zipfile
- [x] check if the SHA generated is kept similar

This would reduce the need for uploading outputs when files inside the outputs did not change.
```[tasklist]
### MartinKippenberger
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6474
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6571
```

**Comment by GitHK** [comment]
Apparently there is a library for this in python https://github.com/drivendataorg/repro-zipfile

**Comment by sanderegg** [comment]
completed
