### ISSUE TITLE
Flaky tests/test_redis.py::test_lock_acquired_in_parallel_to_update_same_resource

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#6280]
for example: https://github.com/ITISFoundation/osparc-simcore/actions/runs/10632181878/job/29474725659

**Comment by pcrespov** [comment]
This looks like a real bug and not just a flaky
https://github.com/ITISFoundation/osparc-simcore/actions/runs/10669817137/job/29572548671#step:10:1195

**Comment by pcrespov** [comment]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/10671236860/job/29576660143#step:10:943
thx

**Comment by GitHK** [comment]
Here's an attempt to fix the issue https://github.com/ITISFoundation/osparc-simcore/pull/6292
