### ISSUE TITLE
Webserver: remove/review automatic unhealthyness for delayed calls

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#6321]
# Problem description
- The webserver currently automatically sets itself as unhealthy if the average of the API calls delays too much (e.g. it computes the mean response time/latency and if that latency goes too high, it deems itself as unhealthy)
- The docker healthcheck runs periodically to check the healthyness of containers, it discovers the webserver in a bad state and will then restart it

This was done at a time where the webserver had some kind of leakage, which was solved by periodically restarting the webserver.

--> It seems that this mechanism triggers when for example the director-v2 does not return response fast enough, although this has nothing to do with the webserver. so why restart it?
--> Is it really such a good idea? if the webserver is loaded, it might respond slower, does it need to restart because of that?

# Resolution
- review the mechanism, disable it or make it at least diseabable.

**Comment by giancarloromeo** [comment]
I'm not aware of the entire mechanism, but is sounds that the _Circuit Breaker pattern_ is the right friend in this case :) We can have a look together, if you want
