### ISSUE TITLE
UI tab label and icon missing

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#635]
![image](https://user-images.githubusercontent.com/32402063/54283311-086cad00-459e-11e9-9015-559be1be7d59.png)

**Comment by odeimaiz** [comment]
By adding the following line in the compile.json (applications/qxapp) file, will change the title in the tab.
"title": "oSPARC"

@oetiker will give the solution to the favicon

**Comment by odeimaiz** [comment]
fixed few years ago
