### ISSUE TITLE
Ensure isolation in unit-tests

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#638]
Our CI provides three levels of testing: unit, integration and system testing.

Unit tests are suppose to have NO dependencies at all to other services. This isolation allows the CI to skip runs if a commit has no changes in a given unit.

In unit-tests, the interaction with other services MUST be instead mimic by fixtures/mockup objects

Currently, at least the webserver does not follow this criteria.

This issue should check all services to comply and provide tools to ensure this criteria is fulfilled when tests are created by the developer.

**Comment by sanderegg** [comment]
webserver is now following these criteria as do the others.
