### ISSUE TITLE
APIT (implementation plan)

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#641]
As presented by Tolga, there is a project to create a dedicated, specialized workflow for passive implant MRI-safety assessment.
Users can upload a passive implant and get EM (FDTD) and thermal simulation results for a setup, where the implant is placed inside an ASTM phantom and exposed to MRI RF fields.

**Definition of Done**
- [ ] By the end of this sprint, an implementation plan is demanded.

We should see this a opportunity to explore the potential of using osparc technology to present specialized apps (not involving all the osparc gui).

to keep in mind: there might be overlap with Novocure demands.

**Comment by drniiken** [comment]
Paused for the very moment. Will be addressed again by the end of May.
