### ISSUE TITLE
REST response status code of osparc errors are 302 instead of 5xx

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#6477]
FYI also the REST response status code is not an error but 302. This error should be a 500-status code I guess.

![image](https://github.com/user-attachments/assets/8a15e7f3-f8e1-4bde-9395-083b3445d39c)

_Originally posted by @mrnicegyu11 in https://github.com/ITISFoundation/osparc-simcore/issues/6476#issuecomment-2385100661_

**Comment by pcrespov** [comment]
NOTE: to detect that there is an error automatically, you cannot rely on the backend response. You could either detect the fragment or that the front-end has shown the error page
