### ISSUE TITLE
Migrate Waffle to Github

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#649]
![image](https://user-images.githubusercontent.com/32402063/54605363-650e1300-4a49-11e9-989b-0b685dcfeb8d.png)

https://help.waffle.io/waffle-shutdown/migration-to-github-projects/migrate-to-github-projects

https://help.zenhub.com/support/solutions/articles/43000493006

**Comment by sanderegg** [comment]
migration to Zenhub:
- invitation to all team members
- install zenhub extension in chrome/firefox
- use [black theme](https://github.com/StylishThemes/GitHub-Dark)
- migrated entries from waffle to zenhub
