### ISSUE TITLE
Infinite update loop

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#6490]
I am stuck with this. I click it and the I hit F5 again and shows up over and over

![image](https://github.com/user-attachments/assets/41fadac8-b7bc-4075-90cc-0337165a73ff)

**Comment by odeimaiz** [comment]
@mguidon Do you hit F5 before getting the latest version??

**Comment by mguidon** [comment]
Maybe? I dont remember what I did.

**Comment by odeimaiz** [comment]
The ``Reload`` button will reload the page forcing a no-cache request, no need to press the reload button in the browser.

I've never seen such a behaviour, if it happens again, ping me please.

Closing for now.
