### ISSUE TITLE
Frontend does not display correctly error message with 5XX

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#6503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

development (master)

### Current Behavior

ON a 5XX response, the front-end does nto display the error message in the respons

### Expected Behavior

On a 5XX response, if there is an error message in the response, it should be shown, otherwise use a default message

### Steps To Reproduce

In order to reproduce an unexpected error, build and local, checkout master on commit https://github.com/ITISFoundation/osparc-simcore/commit/997eeb3129754d3295ddbca13afb788f78386a31

1. `git checkout 997eeb3129754d3295ddbca13afb788f78386a31`
1. `make build`
2. `make up-prod`
1. in the db select a product (e.g. `osparc`)
3. remove the `groups_extra_properties` row associated to that `product` -> this will make the configuration invalid and in this commit this error was not handled correctly.
4. try to login 
5. it will fail displaying a strange message

![image](https://github.com/user-attachments/assets/13f8da79-5123-41af-ac67-89b88e6c6332)

### Anything else?

From https://github.com/ITISFoundation/osparc-simcore/pull/6432, the response is standard

I did a reference to it in https://github.com/ITISFoundation/osparc-simcore/pull/6485#pullrequestreview-2342714936 as well.

**Comment by odeimaiz** [comment]
Fixed in master
![ErrorMessage](https://github.com/user-attachments/assets/02333491-f3ef-4d0b-a2b6-5ce8d55c2717)
