### ISSUE TITLE
Update file in filepicker doesn't force pipeline rerun

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore#6505]
When i file is update in a filepicker, the entire pipeline stays blue, i.e. it doesn't realize computational services need to be rerun.

I noticed this is study 96ff449e-8551-11ef-b5f6-0242ac174ade, but I assume it's a general issue.
```[tasklist]
### Event Horizon
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6973
```

**Comment by matusdrobuliak66** [comment]
Can you please specify in which deployment this happened? Thanks 🙏
