### ISSUE TITLE
Authentication failing when only s4l product is present

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#6506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

development (master AWS)

### Current Behavior

When I launch a dynamic service on `AWS master`, in the `s4l` product, I am no longer able to view the content of the iframe.

This happened to YH's account and used to work on mine.

Works if:
- `user primary group`, `everyone group`, `s4l group` and `osparc group` are present

Does not work if:
- `user primary group`, `everyone group`, `s4l group` are present

### Expected Behavior

I should always be able to view the contents of the iframe, without having some other extra "magic" group assigned in users_to_groups

**Comment by YuryHrytsuk** [comment]
Thought :bulb: 
* Shall we create a test to robustly capture this in the future. We got lucky this time since I only have s4l product but it would be nice to have a test for this case

**Comment by YuryHrytsuk** [comment]
> All e2e tests are failing because there is an issue in the code. I guess we managed to capture it nicely.

Ah, correct!

**Comment by pcrespov** [comment]
- Related to https://github.com/ITISFoundation/osparc-simcore/pull/6484
