### ISSUE TITLE
Persistency

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#651]
Goal:
persistency seems to be an important feature we want to have, before beta users start accessing osparc. however, i understand that there might be developer timeline related preferences to still shift that out a bit. please, decide at the developer level where a good compromise between reasonable timeline and urgency shoud be defined.

As a user:
- [x] users can logout from a study and login again to it at a later point
- [x] the status of services (nodes) is saved too (e.g., script in python service, loaded model, settings...)

**Comment by drniiken** [comment]
works for some services. will at least be required as well for paraview, rawgraph, and other ISAN use-cases (#xxx)

**Comment by pcrespov** [comment]
@sanderegg  please add a new section in external services metadata (both dynamic (DS) and computational (CS)services) to determine the "quality of service". This shall be a place where the framework can get some hints about different characteristics of the service he is about to run. For instance: does it implements *persistency*? Is it validated? What is the average/min/max runtime for standard input?  ...  Some of it will come later. For the moment we use the "Persistency" check as the first entry of this "quality of service" section.

I guess there should also be a way to coordinate the labeling of [CS](https://github.com/ITISFoundation/cookiecutter-osparc-service/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker/labels) and [DS](https://github.com/ITISFoundation/osparc-simcore/blob/master/services/dy-jupyter/docker-compose.yml)
