### ISSUE TITLE
Flaky tests/integration/01/test_garbage_collection.py::test_t2_cleanup_resources_after_browser_is_closed

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-simcore#6774]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/11929049592/job/33247843348

```
FAILED tests/integration/01/test_garbage_collection.py::test_t2_cleanup_resources_after_browser_is_closed - AssertionError: assert '7LDMma6iDAx7o36rAAAB' not in ['7LDMma6iDAx7o36rAAAB']
```

**Comment by matusdrobuliak66** [comment]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/11930931272/job/33253848214

**Comment by pcrespov** [comment]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/12071606434/job/33665302978?pr=6655#step:11:1227

**Comment by pcrespov** [comment]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/12109110688/job/33757970527?pr=6655#step:11:1216

**Comment by matusdrobuliak66** [comment]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/12119250990/job/33786374841?pr=6872

**Comment by matusdrobuliak66** [comment]
https://github.com/ITISFoundation/osparc-simcore/actions/runs/12128879206/job/33833188217?pr=6874
