### ISSUE TITLE
Show support email for a product on Frontend

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-simcore#6879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

Whenever I have some questions wrt the product (e.g. sim4life or osparc) I want to be able to find a support email to send my questions to

### Definition of Done

1. Click on my user logo / icon
2. Go to `about ${product}`
3. See support email in shown text

**Comment by odeimaiz** [comment]
About TIP dialog is missing @calys

**Comment by odeimaiz** [comment]
This is the ``About Sim4Life``:

![AboutS4L](https://github.com/user-attachments/assets/d0e8cced-5b90-4433-8122-9e45d71976c8)

**Comment by calys** [comment]
What about something like this, for TIP?

> TIP (TI Planning Tool) is an innovative online platform designed to optimize targeted neurostimulation protocols using temporal interference (TI) stimulation. Developed by IT'IS Foundation, TIP simplifies the complex process of planning deep brain stimulation 
>
> Powered by o²S²PARC technology, TIP utilizes sophisticated electromagnetic simulations, detailed anatomical head models, and automated optimization to generate comprehensive reports with quantitative and visual information. This tool is invaluable for neuroscientists and brain stimulation experts, especially those with limited computational modeling experience, enabling them to create effective and safe stimulation protocols for their research
> 
> For more information about TIP, please visit [itis.swiss](https://itis.swiss/tools-and-systems/ti-planning/overview).
>
> To review license agreements, click [here](https://itisfoundation.github.io/ti-planning-tool-manual/#/docs/support/license).
