### ISSUE TITLE
logger window column width gets reset after resizing side panel

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#701]
From NIH review:
1. change the column width in the logger window
2. play with the width of the side panel
-> column width is reset to default

**Comment by ignapas** [comment]
This is not a but. Resizing the container of a Qooxdoo table makes it reset the sizes of all columns, as seen in this example: http://www.qooxdoo.org/current/demobrowser/#table~Table_Resize_Columns.html
I tag this as an enhancement, an put it back to the New Issues panel. There should be possible extend the base Table widget, keep the width of every column and update it when the user resizes them, that way we would be able to restore it when the table dimensions change.

**Comment by ignapas** [comment]
I change the title from "logger window column width gets reset after **filtering**"
