### ISSUE TITLE
reverse proxy for all dynamic services

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#710]
- move information from code to service labels (reverse proxy settings)
- review all reverse proxy plugins: paraview, rawgraph, modeler

look at aiohttp code for getting the get method, and hdrs.UPGRADE to write cleaner code [aiohttp](https://aiohttp.readthedocs.io/en/v0.18.2/_modules/aiohttp/websocket.html):
```python
f do_handshake(method, headers, transport, protocols=()):
    """Prepare WebSocket handshake.

    It return http response code, response headers, websocket parser,
    websocket writer. It does not perform any IO.

    `protocols` is a sequence of known protocols. On successful handshake,
    the returned response headers contain the first protocol in this list
    which the server also knows.

    """
    # WebSocket accepts only GET
    if method.upper() != hdrs.METH_GET:
        raise errors.HttpProcessingError(
            code=405, headers=((hdrs.ALLOW, hdrs.METH_GET),))

    if 'websocket' != headers.get(hdrs.UPGRADE, '').lower().strip():
        raise errors.HttpBadRequest(
            message='No WebSocket UPGRADE hdr: {}\n Can '
            '"Upgrade" only to "WebSocket".'.format(headers.get(hdrs.UPGRADE)))

    if 'upgrade' not in headers.get(hdrs.CONNECTION, '').lower():
        raise errors.HttpBadRequest(
            message='No CONNECTION upgrade hdr: {}'.format(
                headers.get(hdrs.CONNECTION)))
```

NOTE: I guess whether the all external services should be labeled in a similar fashion, regardless their nature. Currently we do it like this for [CS](https://github.com/ITISFoundation/cookiecutter-osparc-service/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker/labels) and [DS](https://github.com/ITISFoundation/osparc-simcore/blob/master/services/dy-jupyter/docker-compose.yml)

**Comment by pcrespov** [comment]
I guess there should also be a way to coordinate the labeling of [CS](https://github.com/ITISFoundation/cookiecutter-osparc-service/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker/labels) and [DS](https://github.com/ITISFoundation/osparc-simcore/blob/master/services/dy-jupyter/docker-compose.yml)

**Comment by sanderegg** [comment]
paraview now has a reverse proxy from version 2.11.0

**Comment by pcrespov** [comment]
All trafic from custom backend services is now managed by a standalone traffik service and removed from the webserver. this case is not needed anymore
