### ISSUE TITLE
user access management for ISAN

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#712]
This was branched of #19 .
for isan, we only need limited functionality: 
- [x] a non-login (default user) that can only access predefined studies (tbd), modify parameters, run the studies, and look at results. no editing of connections, no scripting, no saving
- [x] access with a user login that provides access to own studies and to all services we decide to make available to beta users.

**Comment by drniiken** [comment]
make the access restrictions more fine grained for the anonymous user (i.e., possibility to restrict editable properties in services - only selected parameters shall be modifiable by anonymous users).
