### ISSUE TITLE
explorer knowledge graph API

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#716]
- understand what is a knowledge graph
- define templates for ISAN
- inject templates for ISAN

**Comment by mguidon** [comment]
For metaddata meeting:
- [ ] Where are the labels (json), input
- [ ] Example should be Kember + Postprocessor
- [ ] Demo for Esra/Martone/Banderovski

**Comment by mguidon** [comment]
It is clear now how to get out metadata into the portal and proper this has become a political only issue. Please reprioritze.

**Comment by pcrespov** [comment]
@mguidon this is obsolete, right? If not please reopen.
