### ISSUE TITLE
Permission policies

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#728]
- [x] create minimal openapi specs for server
- [x] create Identity and Access Management (IAM) as webserver subsystem (see login subsystem) or uservice
- [x] **UPDATE** create users, ~~groups~~ and roles policies ~~(define knowledge graph)~~
- [x] front end: add permission checks for actions in list (e.g. running a service requires ``service.run`` permission)
- [x] **NEW** some of the service settings can be blocked at study level (e.g. changing the value of the permittivity in a EM simulator service). These restrictions do not belong to the platform but to the template study itself. Restrictions can be checked in both sides:
  - [x] Front-end
  - [x] Back-end

**DEFINITION OF DONE**
- Can create all ISAN template with read/write permissions on services 
- Use template with different roles and achieve desired degree of access
- Should achieve the access level for all workflows of ISAN

**Comment by odeimaiz** [comment]
DASHBOARD
studies.read (Backend)
templates.read (Backend)
services.read (Backend)
storage.datcore.read (Backend)
studies.create

PREFERENCES
preferences.token.create
preferences.token.delete

EDITOR
dashboard.mainview.open (=study.create)
study.node.create
study.node.delete
study.node.rename
study.node.start
study.node.data.pull (download)
study.node.data.push (upload)
study.node.data.delete
study.edge.create
study.edge.delete
study.start
study.stop
study.update (retrieve)

CATALOGUE
Show all checkbox (List of services (Backend))
Re-update services (studies.read)

FILE-PICKER
storage.datcore.read

FILE-MANAGER
study.node.data.*

**Comment by odeimaiz** [comment]
https://blog.nodeswat.com/implement-access-control-in-node-js-8567e7b484d1#2405

**Comment by odeimaiz** [comment]
"anonymous": [
  "studies.templates.read",
  "services.read",
  "study.node.data.pull",
  "study.start",
  "study.stop",
  "study.update"
],
"user": [
  "studies.user.read",
  "studies.user.create",
  "storage.datcore.read",
  "preferences.token.create",
  "preferences.token.delete",
  "study.node.create",
  "study.node.delete",
  "study.node.rename",
  "study.node.start",
  "study.node.data.push",
  "study.node.data.delete",
  "study.edge.create",
  "study.edge.delete"
],
"tester": [],
"moderator": [],
"admin": []

**Comment by odeimaiz** [comment]
```json
"anonymous": [
  "studies.templates.read", *
  "services.filtered.read", *
  "study.node.data.pull", *
  "study.start", *
  "study.stop", *
  "study.update" *
],
"user": [
  "studies.user.read", *
  "studies.user.create", *
  "storage.datcore.read", *
  "preferences.token.create", *
  "preferences.token.delete", *
  "study.node.create", *
  "study.node.delete", *
  "study.node.rename", *
  "study.node.start",
  "study.node.data.push", *
  "study.node.data.delete", *
  "study.edge.create", *
  "study.edge.delete" *
],
"tester": [
  "services.all.read" *
],
"moderator": [],
"admin": []
```

**Comment by ignapas** [comment]
We should maybe think about implementing this kind of blocks as a part of the UI component. For example, extending the Button class in an  ActionButton (?) that is in charge of changing its rendering depending on the user's permissions.
