### ISSUE TITLE
frontend does not send description field in project payload, although it is required by project jsonschema

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#737]
- create a new project
- observe the chrome debugger:
![Screenshot from 2019-04-29 18-19-06.png](https://images.zenhubusercontent.com/5c9260c7d76ef51f6b0fe785/ebfaca38-31a3-4aaf-a7a9-675f6a210e74)
- webserver logs:
![Screenshot from 2019-04-29 18-19-43.png](https://images.zenhubusercontent.com/5c9260c7d76ef51f6b0fe785/da179bcf-b897-4fe3-a00c-81e5461a2a9e)

Either change the jsonschema, or pass the payload as the schema defines

**Comment by odeimaiz** [comment]
Fixed in #739
