### ISSUE TITLE
opening the services catalog should automatically grab keyboard focus

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#740]
2x click to get the services catalog

then I have to click in the box...
Also allowing using the up/down cursor arrow to select the service would be cool...
actually there could be a shortcut also to get the services catalog...

**Comment by ignapas** [comment]
Focus is on text filter when opening the window.
Using the arrows is not supported (although it might be possible), but the TAB key is.
Service catalog is opened with Ctrl+N.
