### ISSUE TITLE
share template studies with everybody

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#745]
- [ ] serve front-end under ``/study/{uuid}`` as well
- [ ] copy study to user account
- [ ] create anonymous user if not logged it.

**Comment by ignapas** [comment]
Hi Pedro, do you think we could use [this](https://app.zenhub.com/workspaces/osparc-5c9260f3d76ef51f6b0fe78d/issues/itisfoundation/osparc-simcore/730) already created issue? Or you prefer to keep things seprated?

**Comment by pcrespov** [comment]
Duplicate of #730
