### ISSUE TITLE
Dependency errors in qx container at server/client

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#746]
``` command line
$ cd services/web/client
$ docker-compose build qx
...
$ docker-compose run qx compile --target=build
```

![screenshot](https://user-images.githubusercontent.com/32402063/57154280-ceb76600-6dd8-11e9-9c0a-9346883efaad.png)

It is strange since I thought we had all pinned down. In any case, it would be good to move all this to the dockerfile repo as agreed ... probably this way we can have more control on these changes

**Comment by oetiker** [comment]
I am working on the new image but unfortunately installing npm packages can be pretty tricky ... getting there ...

**Comment by pcrespov** [comment]
Hi @oetiker,  this is happening again...

Cannot ``qx compile`` my client! :-( 
Any hint??

```console
$ cd osparc-simcore/services/web/client
$ docker-compose build --no-cache qx
...
Successfully tagged client_qx:development
```
...
$ docker-compose run qx compile
WARNING: The BUILD_DATE variable is not set. Defaulting to a blank string.
WARNING: The VCS_REF variable is not set. Defaulting to a blank string.
WARNING: The VCS_URL variable is not set. Defaulting to a blank string.
WARNING: The VCS_REF_CLIENT variable is not set. Defaulting to a blank string.
WARNING: The VCS_STATUS_CLIENT variable is not set. Defaulting to a blank string.
Booting qooxdoo ...
- script dir:  /home/scu/client/docker/
- client dir:  /home/scu/client/
- fonts dir :  /home/scu/client/source/resource/iconfont/
Installing qooxdoo contrib ...
- script dir:  /home/scu/client/docker/
- client dir:  /home/scu/client/
- fonts dir :  /home/scu/client/source/resource/iconfont/
~ ~/client
qooxdoo and compiler versions

| /home/scu
| 
+-- qooxdoo-sdk@6.0.0-alpha-20190409-f79cc78 
|   The JS Framework for Coders
|   git+https://github.com/qooxdoo/qooxdoo.git
|   http://qooxdoo.org
`-- qxcompiler@0.3.0-alpha.20190423-1234
  | node.js based replacement for the Qooxdoo python toolchain
  | git+https://github.com/qooxdoo/qooxdoo-compiler.git
  | https://github.com/qooxdoo/qooxdoo-compiler
  `-- UNMET DEPENDENCY qooxdoo-sdk@6.0.0-alpha-20181226-a3c2b0b 

npm ERR! missing: qooxdoo-sdk@6.0.0-alpha-20181226-a3c2b0b, required by qxcompiler@0.3.0-alpha.20190423-1234

| /home/scu
| 
`-- qxcompiler@0.3.0-alpha.20190423-1234 
    node.js based replacement for the Qooxdoo python toolchain
    git+https://github.com/qooxdoo/qooxdoo-compiler.git
    https://github.com/qooxdoo/qooxdoo-compiler

~/client
~/client ~/client
Updating contributions ...
(node:39) ExperimentalWarning: The fs.promises API is experimental
Downloading cache from GitHub ...
Found 236 releases of libraries.
Run 'qx contrib list' in the root dir of your project to see which versions of these libraries are compatible.
Listing contributions ...
...
...
Running 'qx compile' ...
(node:72) ExperimentalWarning: The fs.promises API is experimental
One or more libraries not found - trying to install them from library repository...
Error: Error: Empty Manifest.json in library at /home/scu/client/contrib/ITISFoundation_qx-iconfont-material_v0_1_4
    at qx.tool.compiler.files.Utils.correctCase.then.then.then.data (/home/scu/node_modules/qxcompiler/lib/qx/tool/compiler/app/Library.js:149:19)
From previous event:
    at Function.__callStaticMethod (/home/scu/node_modules/qxcompiler/node_modules/qooxdoo/qx-oo.js:24164:64)
    at Function.all (/home/scu/node_modules/qxcompiler/node_modules/qooxdoo/qx-oo.js:23750:25)
    at defaultConstructor.createMakerFromConfig (/home/scu/node_modules/qxcompiler/lib/qx/tool/cli/commands/Compile.js:603:24)
```

**Comment by pcrespov** [comment]
obsolete. solved in qooxdookit in ITISFoundation/dockerfile
