### ISSUE TITLE
Reload Website

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#752]
## Long story short
This is maybe an obvious comment:
Once I do a reload of my website, it always brings me back to the entry/login site. Without warning me or anything. If possible, this could be more user friendly.
## Expected behaviour
Once I do a reload, I actually should get a refresh of my current site/state ... and not go to the login page again. Or at least it shall give me a warning that I'm doing so.
## Actual behaviour
When I'm doing a reload page, I get again to the login site and have to start fron scratch. Maybe lost state and project?
## Steps to reproduce
Do reload page :-)
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/"
  },
  {
    "name": "osparc-simcore UI ['clean']",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "0.3.0-alpha.20190423-1234",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "qxapp",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-alpha-20190409-f79cc78",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.0.6",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.1.2",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.43.2",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "gridster",
    "version": "0.7.0",
    "url": "https://github.com/dsmorse/gridster.js"
  },
  {
    "name": "svg.js",
    "version": "2.6.4",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by ignapas** [comment]
This behaviour was improved with [#730](https://github.com/ITISFoundation/osparc-simcore/issues/730). Now we are able to login with a session token, so the user's session is remembered and the user does not have to log in every time. When a user reloads the page, he is taken to his study browser. Currently the cookie expires with the browser session, so if the user closes the browser, he will have to log in again.
Recovering the exact application state and displaying the same GUI the user was seeing before the reload is something we cannot do at the actual state of the application.

**Comment by drniiken** [comment]
Nice! Thanks!
