### ISSUE TITLE
GUI Ideas/Suggestions Collection List from Testing

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#759]
## "Hint" to Double Click in Empty Workbench
- [x] I want a cool way of "hinting" the user to double click in order to get the services window

![2019-05-09_22-46-33](https://user-images.githubusercontent.com/32800795/57485693-b8b01680-72ac-11e9-999e-8f5e257532e7.png)
![2019-05-09_22-45-11](https://user-images.githubusercontent.com/32800795/57485694-b8b01680-72ac-11e9-8165-46a5e60daaff.gif)

Could be a vibrating circle, a "tooltip", whatever looks great (and can be reused at different locations and for different purposes in the GUI).

## Different Levels of Black in Dashboard
Hard to see, but there are different intensities of black used. (1) different from (2) background.

- [x] I want the same black.
;-)

![2019-05-09_23-01-35](https://user-images.githubusercontent.com/32800795/57486686-ded6b600-72ae-11e9-8e2f-f77a7d9441b9.png)

## Arrangement/Datastructure of Files on S3
The arrangement in nested folders is not very nice.
- [ ] I want a representation/structure like in the Datcore section.

![2019-05-10_00-35-05](https://user-images.githubusercontent.com/32800795/57491138-f0728a80-72bb-11e9-90cd-f8528c5fa31c.png)

## ISAN: Thumbnails in Dashboard
- [ ] I guess for ISAN we need to put appropriate thumbnails/images for the Studies in the Dashboard.

![2019-05-10_00-59-39](https://user-images.githubusercontent.com/32800795/57491963-409f1c00-72bf-11e9-8a3d-0d4757b1e5e8.png)

## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/"
  },
  {
    "name": "osparc-simcore UI ['clean']",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "0.3.0-alpha.20190423-1234",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "qxapp",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-alpha-20190409-f79cc78",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.0.6",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.1.2",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.43.2",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "gridster",
    "version": "0.7.0",
    "url": "https://github.com/dsmorse/gridster.js"
  },
  {
    "name": "svg.js",
    "version": "2.6.4",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by ignapas** [comment]
Hi Nik,
Regarding the template thumbnails, who should I reach to get them?
Thank you

**Comment by ignapas** [comment]
The thing with the IDs in the file picker -> @mguidon 
Relevant thumbnails in dashboard are tackled in: https://github.com/ITISFoundation/osparc-simcore/issues/855

**Comment by ignapas** [comment]
@drniiken All these issues are already fixed or waiting for your input

**Comment by drniiken** [comment]
Moving this to closed ... we'll rather reopen a new GUI collection or make single cases ... best, Nik
