### ISSUE TITLE
ISAN Use Case UCD 1D, 2D: Movie Not Shown

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#762]
## Long story short
Enter CC 2D and open the cc-2d-viewer. Then retrieve and refresh -> the movie should properly show within the Jupyter notebook.
-> The movie is not shown, does not work.

## Expected behaviour
The movie in the Jupyter notebook should properly show.

## Actual behaviour
Please see recording as follows:

![2019-05-10_20-49-34](https://user-images.githubusercontent.com/32800795/57550253-1eaca480-7366-11e9-8da5-f48feba4191e.gif)

## Steps to reproduce
Please see above.

## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "cfc73c1",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/cfc73c1/"
  },
  {
    "name": "osparc-simcore UI ['clean']",
    "version": "cfc73c1",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/cfc73c1/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "0.3.0-alpha.20190423-1234",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "qxapp",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-alpha-20190409-f79cc78",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.0.6",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.1.2",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.43.2",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "gridster",
    "version": "0.7.0",
    "url": "https://github.com/dsmorse/gridster.js"
  },
  {
    "name": "svg.js",
    "version": "2.6.4",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by sanderegg** [comment]
From the attached GIF, I could find out the following:
project-id: 1988f800-9a06-4a15-9290-5c28dab627ba
looking in S3 under 1988f800-9a06-4a15-9290-5c28dab627ba/4c065c01-65f7-4fcc-a0da-1cedf8dcbc73:
- The file aps.tgz is present but empty, therefore the 2D post-processor cannot use any file.

Further analyzing the pipeline, it seems __no__ input file was attached to the 2D solver input parameters.
This issue should be closed and an enhancement should be opened to give the user a better feedback whether an input file was selected, or also required parameters on algorithms should be defined to allow the frontend to prevent running pipelines before all the inputs are selected.
