### ISSUE TITLE
OpenCOR: Computational service

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#764]
- [x] Create public repository using cookiecutter-osparc-service
- [x] Obtain OpenCOR service (as code, github or dockerfile)
- [x] Update to latest version
- [x] Add tests to guarantee it runs

**Definition of done:**
OpenCOR service runs in SIM-CORE

**Comment by pcrespov** [comment]
### ospacr-opencor service in catalog
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/5410bb94-38e0-4578-a0e9-1af5cd032ca4)

### pipeline for ISAN2019 parametrized template study
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/e650de33-7b09-4dc0-8260-ede83858463d)

### Detail of input set with a ``{{ .. }}`` expression (as in [jinja2](http://jinja.pocoo.org/docs/2.10/templates/#expressions) )

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/409b43bd-0e1e-4cc2-8740-a125c85d013e)

**Comment by pcrespov** [comment]
Added 0.2.2 in master's docker registry
