### ISSUE TITLE
OpenCOR: Communication MAP-Core/SIM-Core

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#766]
1. Pass the data to run the template in a HTTP request (as body or query?)
2. Create or update a study and adapt the study with the received data for pushing and pulling 
    Explore the different options

Proposal (discussed with@sanderegg and @mguidon )
- [x] Extend study link with parameters (in the query, so it stays as a link). Link might look like ``study/{uuid}/?p1=3&p2=55&hook_target={url}``
- [x] The server creates the user and the study as we already do, but it also generates it taking into account the input parameters.
- [ ] Create web-hooks feature on every service that produce output data. Create notification for completion with status, and download-link for data in the body
- [ ] output data of a service is automatically uploaded to S3 and a presigned link is passed to the hook so notified client can download the results
- [ ] create a prototype of the concept and send a written proposal to MAPCORE <-------!!!

### Definition of done:
1. The user can click a link that creates the project in SIM-Core where he/she can press run
2. The results gets uploaded somewhere, and notifies MAP-Core where to download it (explore options)

**Comment by ignapas** [comment]
To include the parameters in the templates we could add an unique id field to each node, and then target each parameter inside from the URL in this way: ``?nodeId.parameterKey=value`` (URLencoded)
