### ISSUE TITLE
persistency shall serialize input/output data as well

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#781]

**Comment by ignapas** [comment]
@sanderegg please update status, move to the right panel

**Comment by sanderegg** [comment]
as the frontend calls retrieve automatically when the service is started, the inputs are implicitely re-imported in the node.
currently not sure how to implement that without uploading/downloading all the time...

**Comment by sanderegg** [comment]
currently in a working state.
