### ISSUE TITLE
Simcore Part of Portal Website

### ISSUE THREAD

**Issue by oetiker** [ITISFoundation/osparc-simcore#786]
- Backend: FLASK
- Fronend Vue
- Check and see how far Datacore is

-  nih-sparc data-portal fork @ ITISFoundation: https://github.com/ITISFoundation/data-portal
- online dev demo at http://dev-sparc-portal.sparc.science/

**Comment by pcrespov** [comment]
online in https://data.sparc.science/sim/#/
