### ISSUE TITLE
Password strength hint

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#813]
Decide whether to implement a password strength hint visual component in the client, for account creation and profile editing.
Currently there is some server-side library in place but this should probably be done exclusively in the client to avoid unnecessary calls to the server and allow the user to have an immediate password strength hint.
Do not confuse with the password acceptance rules which must be validated server-side and just return whether a password is acceptable or not. This is just to help the user create a stronger password.

A stronger implementation of this is in #814

**Comment by ignapas** [comment]
For the moment, once we decide the password rules (minimum length, containing special characters, etc...) we just add a small label below the password field to inform the user about those rules.

**Comment by pcrespov** [comment]
won;t do

**Comment by pcrespov** [comment]
won;t do
