### ISSUE TITLE
Window positioning in Workbench

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#823]
Solve detected problems in NodeUI/Service catalogue positioning.

* New nodes stack and only the last on is seen (the rest are below).
* Service catalogue sometimes partially renders outside the view.
* New nodes added with the service catalogue when it is opened with Ctrl+N could add outside the view.

![windows.gif](https://images.zenhubusercontent.com/5caefb2eecad11531cc41380/a9939711-96b5-4eaf-9147-4435cc9e94ed)

**Comment by odeimaiz** [comment]
deprecated
