### ISSUE TITLE
Cannot create a study

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#831]
- go to osparc01
- create a study
- nothing happens... no workbench.

**Comment by ignapas** [comment]
Yes, I was having this problem on Friday, after merging from master. Do you get any error message?

**Comment by sanderegg** [comment]
I get this on the frontend side:
{"data": null, "error": {"logs": [{"message": "Bad Request", "level": "ERROR", "logger": "user"}], "errors": [{"code": "HTTPBadRequest", "message": "Bad Request", "resource": null, "field": null}], "status": 400}}

on the backend there is a failed validation error on the project payload:
2019-06-03T07:37:37.786029464Z jsonschema.exceptions.ValidationError: 'workbench' is a required property

**Comment by odeimaiz** [comment]
@sanderegg merci!
@ignapas Pedro and I will take care of this one
