### ISSUE TITLE
Hangs while showing spinner - The "just refresh the page" issue

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#880]
After login, retrieving the services fail and the page freezes showing the loading spinner. The only way out is to refresh the page.
Identify the problem and fix it.

@sanderegg Sees it happening in other screens and almost every time in prod.

**Comment by ignapas** [comment]
![Screenshot 2019-06-13 at 10.26.32.png](https://images.zenhubusercontent.com/5caefb2eecad11531cc41380/c59b52f3-e650-4d14-ab0a-47ada251dda7)

**Comment by odeimaiz** [comment]
Webserver side:
![image](https://user-images.githubusercontent.com/33152403/59926005-9c6dd080-9439-11e9-9174-8b45212dc8ad.png)

**Comment by sanderegg** [comment]
now the director is pretty fast in retrieving services and also caches the services every 15minutes
