### ISSUE TITLE
Modeling: Primitives and simple operations

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#9]
The framework provides simple modeling operations within the 3D window:
- [x] Rotate
- [x] Pan
- [x] Create cylinder
- [x] Implement cut operation (e.g., also via boolean subtraction)

**Comment by mguidon** [comment]
1. Branch from SuperMash master for extension of thrift interface
2. Identify minimal dependencies
3. Containerize in linux

**Comment by sanderegg** [comment]
1. branched from supermash.
2. updated to thrift 0.11 (important python bugfixes)

**Comment by drniiken** [comment]
3. Modeling@z43
OM

* modeling application on the web
* qxdoo
* generate primitive
* move them
* moving free style
* pick entities
* create entities interactively
* scene can be saved and loaded
* also option to create mesh in S4L and render it in other scene
* snapping onto objects
* remotely loading a ViP model
* client and server based handling
* bring S4L into microservices

* check ACIS license in use of remote, online !
* big motivation to switch to Linux
* add issue in backlog

* major issues
* sending around big data, amazon
* cost
* how to solve
* test it, locally remotely run

**Comment by drniiken** [comment]
* SA

* port 8080

* move and rotate objects
* live demo

* from frontend to S4L machine (boolean done using ACIS in S4L service)
* for boolean operations
* unite, intersect, subtract

* boolean = new
* S4L service has been dockerized
* docker swarm, SA system + machines in basement
* issues with flex licensing
* modeling is serviced and dockerized

* node.js will be replaced then by python, e.g., tornado
* boilerplate approach
* node.js then switch off at one point
