### ISSUE TITLE
(SimCoreUser) will be the new user for host&container in order to avoid being root. ID with a very high number. Mechanism that the user in the host and in docker image are the same one.

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#90]
- [x] **scu** (SimCoreUser) will be the new user for host&container in order to avoid being root. ID with a very high number. Mechanism that the user in the host and in docker image are the same one. 
- [x] adapt director
- [x] adapt sidecar (connected to PR #199)
- [ ] remove the need of export RUN_DOCKER_ENGINE_ROOT=1 in Makefile and export DOCKER_GID=1042
export HOST_GID=1000

requires #215
links #300

**Comment by pcrespov** [comment]
- Implemented in web/server & clients on PR #110 (actually via PR to @mguidon )
   - **username: scu**
   - **uid: 8004**
- Added some notes and samples about the concept in [non-root-users](https://github.com/pcrespov/dockerfiles/tree/master/sandbox/non-root-users)

**Comment by pcrespov** [comment]
- [ ] adapt director
- [ ] adapt sidecar

**Comment by pcrespov** [comment]
The trick with /tmp + entrypoint should avoid having to add config variables in the makefile or .env:
```
export DOCKER_GID=1042
export HOST_GID=1000
```

**Comment by pcrespov** [comment]
Developed a non-intrusive [solution]  (https://github.com/pcrespov/dockerfiles/tree/master/usage/non-root-users/dev-target). Key ideas are:
 - Every build stage uses a different workdir
 - Entrypoint is used to deduce user's runtime configurations (e.g. host id/gid or docker gid)
