### ISSUE TITLE
User Manual for oSPARC Platform

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#926]
**STORY**

In particular for ISAN (however, obviously also in general) we need a web-based User Manual (later also Tutorial, etc.) which allows oSPARC users to find easy access/usability into our platform.

The content will be provided by, e.g., by Nik and possibly others (AppTeam, etc.). Initially it will be very basic (for ISAN) and then grow continuously with time ...

For this we'll need a clever and easy to use infrastructure (e.g., embedded into automation, CI/CD system for documentation) which allows also "digital natives from the early days" ;-) to be operated and maintained.

- [x] setup of documentation infrastructure/system
- [x] introduction/ short training on how to use it (to Nik)
- [x] generation of User Manual, documentation for ISAN (Nik)

**Comment by pcrespov** [comment]
Setup repo and tooling in https://github.com/ITISFoundation/osparc-manual
