### ISSUE TITLE
Update requirements in services/dy-jupyter-extensions

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#927]
See security alerts : 
 - https://requires.io/github/ITISFoundation/osparc-services/requirements/?branch=master
 - https://github.com/ITISFoundation/osparc-services/network/alerts

I tried to do it myself, but I have the impression you forgot to commit ``services/dy-jupyter-extensions/neuron/requirements/base.in`` file!

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/01b6faa7-f75c-4b32-86ee-bce0f111d8b8)

**Comment by mguidon** [comment]
Done
