### ISSUE TITLE
Check if development docker containers for front-end (qx compile --watch) works

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#93]

**Comment by odeimaiz** [comment]
From https://github.com/moby/moby/issues/30105

> [This is a known limitation of Docker for Windows](https://docs.docker.com/docker-for-windows/troubleshoot/#/inotify-on-shared-drives-does-not-work)

**Comment by odeimaiz** [comment]
Workaround
http://blog.subjectify.us/miscellaneous/2017/04/24/docker-for-windows-watch-bindings.html
