### ISSUE TITLE
Access to Tools on osparc.io

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#945]
Make sure developers can access the relevant tools in staging/production

- [ ] registry.osparc.io
- [ ] storage.osparc.io
- [ ] storage-staging.osparc.io
- [ ] adminer.osparc.io
- [ ] adminer-staging.osparc.io
- [ ] monitoring.osparc.io
- [ ] maintenance.osparc.io

**Comment by pcrespov** [comment]
this is done
